.gitignore, CONTRIBUTING.md, LICENSE, README.md, akka-http-core/build.sbt, akka-http-core/src/test/scala/akka/http/impl/util/One2OneBidiFlowSpec.scala, akka-http-core/src/test/scala/akka/stream/testkit/Coroner.scala, akka-http-core/src/test/scala/akka/stream/testkit/TestUtils.scala, akka-http-core/src/test/scala/akka/stream/testkit/Utils.scala, akka-http-core/src/test/scala/akka/testkit/AkkaSpec.scala, akka-http-core/src/test/scala/akka/testkit/Coroner.scala, akka-http-marshallers-java/akka-http-jackson/build.sbt, akka-http-marshallers-scala/akka-http-spray-json/build.sbt, akka-http-marshallers-scala/akka-http-xml/build.sbt, akka-http-testkit/build.sbt, akka-http-tests/build.sbt, akka-http/build.sbt, akka-parsing/build.sbt, akka-parsing/src/main/scala/akka/parboiled2/ErrorFormatter.scala, akka-parsing/src/main/scala/akka/parboiled2/support/OpTreeContext.scala, build.sbt, project/CliOptions.scala, project/Dependencies.scala, project/Doc.scala, project/Formatting.scala, project/Github.scala, project/Publish.scala, project/build.properties, project/plugins.sbt, version.sbt
@ktoso WDYT? Built from your starting point, I didn't keep your commits for the build, hope that's ok.
=> Build setup

akka-http-core/src/main/java/akka/http/javadsl/model/FormData.java
Port of http://github.com/akka/akka/pull/21344
=> Add javadsl FormData.create(Iterable) overload #21303 (#21344)

akka-http-core/src/test/scala/akka/http/impl/util/One2OneBidiFlowSpec.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
=> =htk cleanup imports

akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/MarshallingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CodingDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/coding/Encoder.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToResponseMarshallers.scala
Forward port from akka/akka 
Resolves https://github.com/akka/akka-http/issues/21
Thanks @gosubpl
=> =htc don't encode known to be empty entities (#21393) (#21396)

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpResponseParser.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala
This stage is no longer required since 9dc474a1 converted HttpResponseParser
to a GraphStage.
=> =htc Relocate HttpResponseParser.stage to tests

project/ValidatePullRequest.scala, project/plugins.sbt
I think I've ported everything connected to validatePullRequest - behaved in sensible way locally :pray:. Excluded MultiNode thing.
=> Ported validatePullRequest to this repo (#311).

README.md
This might need some touch ups from the core team but this should bring it closer.
=> =pro Update README to include intro and fix links (#319)

akka-http-core/src/main/scala/akka/http/impl/engine/ws/FrameEventRenderer.scala, akka-http-core/src/main/scala/akka/http/impl/engine/ws/FrameOutHandler.scala, akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocket.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/FramingSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala
This is code twice lost that is converting FrameOutHandler and FrameEventRenderer to GraphStage(s).
=> =htc FrameOutHandler and FrameEventRenderer as graph stages (#341)

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/BufferedOutletSupport.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ByteFlag.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameParser.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameRenderer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Protocol.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/rendering/HttpResponseHeaderHpackCompression.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/HPackSpecExamples.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FramingSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/package.scala, akka-http2-support/src/test/scala/akka/http/scaladsl/Http2ServerTest.scala, project/Dependencies.scala
@ktoso here's a bit more progress. We can now properly read/write SETTINGS frames and I started working on keeping track of WINDOW_UPDATEs.
(btw. I try to keep the commits self-contained, so no need to squash. Otherwise, I'll get conflicts all the time if I (or you) already have started building on top of this PR))
=> more http2 progress

docs/src/main/paradox/scala/http/handling-blocking-operations-in-akka-http-routes.md
=> Improve language in docs on blocking operations

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
Fixes #367, not sure about other potential consequences though.
=> Close blueprint on no body early complete

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/BufferedOutletSupport.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/scaladsl/Http2ServerTest.scala
Here's a set of changes which weren't yet merged.
=> Yet unmerged http/2 changes

CONTRIBUTING.md, docs/src/main/paradox/index.md, docs/src/main/paradox/security.md, docs/src/main/paradox/security/2016-09-30-windows-directory-traversal.md
Please review @patriknw @jrudolph
=> +doc security page about recent vunerability

docs/src/main/paradox/scala/http/routing-dsl/directives/index.md
=> Add documentation for Tuple extraction in Scala DSL (#283)

akka-http/src/main/scala/akka/http/javadsl/server/directives/PathDirectives.scala, docs/src/main/paradox/java/http/migration-guide/index.md, docs/src/main/paradox/java/http/migration-guide/migration-from-old-http-javadsl.md, docs/src/main/paradox/java/http/migration-guide/migration-guide-2.4.x-3.0.x.md, docs/src/main/paradox/scala/http/migration-guide/index.md, docs/src/main/paradox/scala/http/migration-guide/migration-from-old-http-javadsl.md, docs/src/main/paradox/scala/http/migration-guide/migration-from-spray.md, docs/src/main/paradox/scala/http/migration-guide/migration-guide-2.4.x-3.0.x.md
Resolves https://github.com/akka/akka-http/issues/361
=> !htp #361 fix usage of Scala Function in JavaDSL in PathDirectives

akka-http-core/src/test/scala/akka/http/javadsl/HttpExtensionApiSpec.scala, docs/src/test/java/docs/http/javadsl/server/HttpServerExampleDocTest.java
Resolves https://github.com/akka/akka-http/issues/333
=> =htp #333 increase timeout, 1 second is too little on jenkins

akka-http-tests/build.sbt, akka-http-tests/src/multi-jvm/scala/akka/remote/testkit/MultiNodeConfig.scala, akka-http-tests/src/multi-jvm/scala/akka/remote/testkit/PerfFlamesSupport.scala, akka-http-tests/src/multi-jvm/scala/akka/testkit/TestTags.scala, akka-http-tests/src/multi-jvm/scala/org/scalatest/extra/QuietReporter.scala, build.sbt, project/Dependencies.scala, project/MultiNode.scala, project/plugins.sbt
Makes https://jenkins.akka.io:8498/view/Performance/job/akka-http-perf/205/console work again
=> Wip perf jenkins working

docs/src/main/paradox/java/http/client-side/client-https-support.md, docs/src/main/paradox/scala/http/client-side/client-https-support.md
=> =doc amending Tls suffix to Https #441

docs/src/main/paradox/java/http/client-side/index.md, docs/src/main/paradox/java/http/common/index.md, docs/src/main/paradox/java/http/index.md, docs/src/main/paradox/java/http/migration-guide/index.md, docs/src/main/paradox/scala/http/client-side/index.md, docs/src/main/paradox/scala/http/common/index.md, docs/src/main/paradox/scala/http/index.md, docs/src/main/paradox/scala/http/migration-guide/index.md
Helps with https://github.com/akka/akka-http/issues/436
=> =doc #436 naively improve docs searchability by more TOC

akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolConductor.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolSlot.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/ByteStringSinkProbe.scala
This is to fix connection pool crashing entirely in case of response entity future failing.
=> =htc #416 fix for connection pool crash

project/Dependencies.scala, project/Doc.scala
No needed after upgrading to 2.4.12
=> Remove custom akka api mapping

akka-http-core/src/main/scala/akka/http/impl/util/LogByteStringTools.scala
I use this all the time. It's not http specific but it's very useful here.
=> =htc add LogByteStringTools to impl.util to have it ready during debugging

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/BufferedOutletSupport.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameParser.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/parsing/HttpRequestHeaderHpackDecompression.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/model/http2/Http2StreamIdHeader.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/parsing/HttpRequestHeaderHpackDecompressionSpec.scala
Initial step to resolve #384 
I'll continue to work on this during the next days I think.
@jrudolph's suggestion to put stuff into the Demuxer was very good!
Review as entire thing, not individual commits - I'll squash later.
=> Initial steps for HTTP/2 incoming Entity support

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ClientConnectionSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/impl/util/LogByteStringTools.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ClientConnectionSettings.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ClientConnectionSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala
Resolves #509
@jrudolph, it this what you have meant in #509 :-)?
=> HTTP server/client layer is extended by exchange byte logging based on configuration (#509).

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameParser.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FramingSpec.scala
PriorityFrame HTTP2 model, without renderer atm
=> +ht2 #245 parse PriorityFrame but without rendering

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/util/LogByteStringTools.scala
A small follow up to @rbudzko excellent #523.
=> =htc #509 slightly improve wording and DRY up setting

.travis.yml, akka-http-tests/build.sbt, akka-http-tests/src/test/java/akka/http/javadsl/server/directives/RouteDirectivesTest.java, build.sbt, project/Publish.scala, project/build.properties, project/plugins.sbt, version.sbt
This enables automatic artifact publish process when a new tag is created (either from GitHub releases or pushing a new tag from local clone).
https://github.com/akka/alpakka is being published this way as well.
=> Publish to bintray and sync to Maven Central on tag

.travis.yml, RELEASING.md, akka-parsing/build.sbt, build.sbt, project/Formatting.scala, project/Publish.scala
Addresses https://github.com/akka/akka-http/pull/534#issuecomment-261211873
=> Add release instructions

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameParser.scala, build.sbt
Resolves #499
Also some smaller build cleanup
=> =pro #499 prepare for publishing Akka HTTP X, dont publish tests

docs/src/main/paradox/index.md
Resolves the comment @jonas made on #435 
Anything else we _must_ do before stable and if we don't the sky will fall? :)
=> =doc top level title determines page title, made it HTTP

akka-http-marshallers-scala/akka-http-spray-json/src/main/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonByteStringParserInput.scala, akka-http-marshallers-scala/akka-http-spray-json/src/test/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupportSpec.scala, project/Dependencies.scala
Resolves #564 
I'm somewhat stuck on adding the scalatest dependency there though... any ideas, maybe @2m or @akka/akka-team ?
=> =spray-json #564 fix decoding emoji, port from spray-json patch 

akka-http-core/src/main/scala/akka/http/impl/util/JavaAccessors.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala, akka-http-core/src/test/scala/akka/http/impl/util/StreamUtilsSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CacheConditionDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/HeaderDirectives.scala, project/Dependencies.scala, project/Doc.scala, project/MultiNode.scala, project/Publish.scala, project/Version.scala
I know the `() => (()))` are not super nice, but the warnings is somewhat distracting.
Note I didn't test the MultiJvm sbt changes. Is there anything specific I need to do to run those tests?
=> Fix compilation warnings

docs/src/main/paradox/java/http/routing-dsl/directives/path-directives/index.md, docs/src/main/paradox/java/http/routing-dsl/directives/path-directives/path.md, docs/src/main/paradox/java/http/routing-dsl/directives/path-directives/pathEnd.md, docs/src/main/paradox/java/http/routing-dsl/directives/path-directives/pathEndOrSingleSlash.md, docs/src/main/paradox/java/http/routing-dsl/directives/path-directives/pathPrefix.md, docs/src/main/paradox/java/http/routing-dsl/directives/path-directives/pathSingleSlash.md, docs/src/main/paradox/java/http/routing-dsl/directives/path-directives/rawPathPrefix.md, docs/src/main/paradox/scala/http/routing-dsl/directives/path-directives/index.md, docs/src/main/paradox/scala/http/routing-dsl/directives/path-directives/path.md, docs/src/main/paradox/scala/http/routing-dsl/directives/path-directives/pathEnd.md, docs/src/main/paradox/scala/http/routing-dsl/directives/path-directives/pathEndOrSingleSlash.md, docs/src/main/paradox/scala/http/routing-dsl/directives/path-directives/pathPrefix.md, docs/src/main/paradox/scala/http/routing-dsl/directives/path-directives/pathSingleSlash.md, docs/src/main/paradox/scala/http/routing-dsl/directives/path-directives/rawPathPrefix.md
Issue: #474
Add comparative between path directives and link to this comparative in all mentioned directives docu page
=> add comparative between path directives

docs/src/main/paradox/scala/http/routing-dsl/directives/coding-directives/encodeResponse.md
Fix rendering of code
http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/coding-directives/encodeResponse.html#example
=> [docs] Small update encodeResponse.md

akka-http-core/src/main/mima-filters/10.0.0.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/HttpConnectionIdleTimeoutBidi.scala, akka-http-core/src/main/scala/akka/http/impl/engine/HttpConnectionTimeoutException.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/util/package.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Resolves https://github.com/akka/akka-http/issues/505 though also needs a PR in Akka itself,
and then an update to this piece of code
=> Idle timeout improvements

CONTRIBUTING.md
=> Add information about developing with Akka `master`

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MarshallingDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToResponseMarshallers.scala
This fixes a regression introduced in #297
=> =htc don't ignore failed future for NoContent responses (#589)

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameParser.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameRenderer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FramingSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> +ht2 added rendering to PriorityFrame model and test case (#245)

CONTRIBUTING.md, LICENSE
=> Update year in Contributing

akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
A race between completion and cancellation towards the TCP stream endpoints
might lead to the connection being canceled (= RST frames sent) when an HTTP
connection is regularly closed (e.g. when the client sets `Connection: close`
in the request).
We now prevent cancellation from reaching the TCP stream at all and rely
on closing the connection from the write side.
Fixes #459.
=> =htp #459 prevent "Connection closed by peer" errors during connection closure

docs/src/main/paradox/scala/http/common/http-model.md
=> Add documentation for Raw-Request-URI synthetic header

docs/src/main/paradox/java/http/routing-dsl/index.md, docs/src/test/java/docs/http/javadsl/server/FileUploadExamplesTest.java
Issue: #592
Add CSV file upload and video upload examples to Java documentation
=> [Java Docs] Add File upload java example

build.sbt, project/ValidatePullRequest.scala
Weird that it wasn't... must have been a mistake somewhere.
=> =pro disable MiMa in HTTP2 project, experimental

docs/src/main/paradox/java/http/routing-dsl/rejections.md, docs/src/main/paradox/scala/http/routing-dsl/rejections.md, docs/src/test/java/docs/http/javadsl/server/directives/ExecutionDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala
Resolves https://github.com/akka/akka-http/issues/743
=> +doc #743 add more advanced handleNotFound example

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameParser.scala
Fixes h2spec suites: 6.7
Size checks added to:
* PingFrame
StreamId checks added to:
* PingFrame
=> h2spec compliance - size check added to PingFrame (#245)

akka-http/src/main/scala/akka/http/javadsl/common/PartialApplication.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameParser.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Compliance.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
One more baby step towards compliance 😉
=> +ht2 render FRAME_SIZE_ERROR when SETTINGS ACK has payload

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameLogger.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala
A somewhat simple optional extra logging stage.
Already based on #762.
=> =ht2 add framelogger for more concise frame logging

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameParser.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameRenderer.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FramingSpec.scala
Just a little push to get a few of the existing tickets finished so we can focus on the high-level things.
=> Add PUSH_PROMISE parsing / rendering

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameLogger.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/FrameRenderer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/framing/Http2FramingSpec.scala
I extracted these changes from your #764, @ktoso to make it easier to discern what was changed and what was just moved around. Will merge after validation and then continue to see how to merge #764.
=> Groundwork for #764

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/framing/Http2FramingSpec.scala
Here's a first set of actual changes I extracted from #764. I think they are good as they are so we can merge them after pr validation.
=> A set of smaller changes related extracted from #764

akka-http-marshallers-scala/akka-http-spray-json/src/main/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupport.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/EntityStreamingSpec.scala, akka-http/src/main/mima-filters/10.0.1.backwards.excludes, akka-http/src/main/scala/akka/http/javadsl/common/EntityStreamingSupport.scala, akka-http/src/main/scala/akka/http/javadsl/common/PartialApplication.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/FramedEntityStreamingDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToResponseMarshallers.scala, docs/src/main/paradox/scala/http/routing-dsl/source-streaming-support.md, docs/src/test/java/docs/http/javadsl/server/directives/BasicDirectivesExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/MiscDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/JsonStreamingFullExamples.scala
Resolves https://github.com/akka/akka-http/issues/424
=> =core #424 fix stream marshalling, better errors, more examples

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Compliance.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Validating window value, small little addition that I added while I was looking at flow control handling.
=> +ht2 validate that WINDOW_UPDATE must be > 0

project/Dependencies.scala
=> Update jetty-alpn-agent to support JDK 8u121

docs/src/main/paradox/scala/http/routing-dsl/source-streaming-support.md
Issue: #797 
Snippet of code for source streaming support is broken
=> Fix broken snip link in source streaming support #797

akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/ResponseRenderingSpec.scala
=> http2 default response headers

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/BufferedOutletSupport.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
This is groundwork for upcoming changes. The multiplexer now has a defined interface. This will helps with code organization but might also allow to try out alternative implementations.
=> =ht2 refactor multiplexer side of demux into its own class

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> Keep SETTINGS_MAX_CONCURRENT_STREAMS in demuxer 

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, docs/src/main/paradox/security.md, docs/src/main/paradox/security/2016-09-30-windows-directory-traversal.md, docs/src/main/paradox/security/2017-01-23-denial-of-service-via-leak-on-unconsumed-closed-connections.md
=> Merge changes from v10.0.2 into master

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> header parser added to http2 workflow (#755)

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Protocol.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> Enforce upper limit of SETTINGS_INITIAL_WINDOW_SIZE 

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Refs #758, only the allowing part. 
Also added debug information to all GOAWAYs
=> +ht2 #758 allow early priotity frames

akka-http/src/main/scala/akka/http/javadsl/server/Route.scala, akka-http/src/main/scala/akka/http/scaladsl/server/Route.scala, docs/src/test/scala/docs/http/scaladsl/ModelSpec.scala
=> Explain consequences of using Route.seal better in scaladoc

docs/src/main/paradox/scala/http/introduction.md
just to avoid the scenario of someone landing on this page, only seeing `2.11` and assuming there's no `2.12` support
=> add "or 2.12" in the introduction.md to make clear it's supported

docs/src/main/paradox/_template/page.st
Issue: #842 
Include search input when screen is small
=> Show search input in small screens #842

akka-http-tests/src/test/java/akka/http/javadsl/server/MinimalHttpApp.java, akka-http-tests/src/test/java/akka/http/javadsl/server/SneakHttpApp.java, akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/HttpAppSpec.scala
Issue: #824 
Attempt to fix this issue, and make tests more reliable.
reduce calls, to save threads
=> Improve HttpApp stability #824

docs/src/main/paradox/scala/http/routing-dsl/directives/custom-directives.md
Just found a couple of issues in the Custom Directives docs, thought I'd quickly submit a patch.
=> Fixing some typos and grammatical issues.

project/plugins.sbt
Issue: #883
In order to be able to modify filters without reloading the project
=> Upgrade MiMa dependency #883

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/util/LogByteStringTools.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
=> =htc #516 fix pull/push twice in server ControllerStage

akka-http/src/main/mima-filters/10.0.3.backwards.excludes, akka-http/src/main/scala/akka/http/scaladsl/server/HttpApp.scala
Easy binary compatibility for HttpApp
Add exclusion to MiMa
=> Transform HttpApp to abstract class

docs/src/main/paradox/scala/http/routing-dsl/directives/custom-directives.md
=> Fix broken link on custom-directive-page #900

RELEASING.md, docs/src/main/paradox/release-notes.md, project/MiMa.scala
(Will fail until 10.0.4 has made it to maven central)
=> =pro add 10.0.4 to mima

akka-http-tests/src/test/scala/akka/http/scaladsl/server/BasicRouteSpecs.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ExecutionDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FutureDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/RouteDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/SecurityDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala, docs/src/main/paradox/java/http/routing-dsl/exception-handling.md, docs/src/main/paradox/scala/http/routing-dsl/exception-handling.md, docs/src/test/scala/docs/http/scaladsl/HttpAppExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/RouteDirectivesExamplesSpec.scala
Comments on @jrudolph's suggestion to log stack traces completely ([as stated in the original issue](https://github.com/akka/akka-http/issues/887#issuecomment-281658746)) are welcome.
=> Speculative PR: Make default ExceptionHandler more informative #887

akka-http-core/src/main/mima-filters/10.0.4.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolConductor.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolFlow.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterfaceActor.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolSlot.scala, akka-http-core/src/main/scala/akka/http/impl/util/package.scala, akka-parsing/src/main/scala/akka/macros/LogHelper.scala, build.sbt
This adds lots of logging around pools, so that we hopefully find bugs in long-running pools more easily.
Refs #912.
=> =htc #912 add logging for pool events

akka-http-core/src/main/scala/akka/http/javadsl/Http.scala, docs/src/main/paradox/java/http/common/http-model.md, docs/src/main/paradox/scala/http/common/http-model.md, docs/src/test/java/docs/http/javadsl/CustomMediaTypesExampleTest.java, docs/src/test/java/docs/http/javadsl/CustomStatusCodesExampleTest.java
Issue: #761
Documentation for:
* Limiting message entity lenght
* Registering Custom Media Types
* Registering custom Status Codes
* The Uri Model
Additionally, fixed some typos and wordings
=> Provide Http Model documentation for Java #761

akka-http/src/main/java/akka/http/javadsl/server/HttpApp.java, akka-http/src/main/scala/akka/http/scaladsl/server/HttpApp.scala
* Prevent immediate shutdown when STDIN is not present, e.g. under sbt-revolver;
* Shutdown the server upon JVM termination;
Couldn't find immediate way of writing a test for the change without introducing indirection of JVM shutdown hook and `StdIn`. Does anyone have any suggestions? I obviously verified the expected behavior in both sbt-revolver (shutdown via C-c) and console (via ENTER).
I will update the `javadsl` implementation as well if this is going in the right direction.
=> Shutdown HttpApp without STDIN #914

CONTRIBUTING.md
FYI, I looked that up in the source code of the plugin.
=> =doc clarify admin/whitelisting of Jenkins PR validation

docs/src/main/paradox/java/http/routing-dsl/directives/marshalling-directives/entity.md, docs/src/main/paradox/scala/http/routing-dsl/directives/marshalling-directives/entity.md
=> fix entity directive doc format

docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
Also included a `myBids` as in memory storage for easy testing
=> fix[#950] add missing `~`

akka-http-core/src/main/mima-filters/10.0.4.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolConductor.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/BodyPartParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/ParserOutput.scala, akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocket.scala, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/stream/testkit/Utils.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/RangeDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/MultipartUnmarshallers.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, docs/src/test/java/docs/http/javadsl/HttpServerActorInteractionExample.java
=> Changes need to make akka-http compile with both 2.4 and 2.5

akka-http-core/src/test/scala/akka/stream/testkit/Utils.scala
Last minute updates gone wrong.
=> =htc remove useless declarations

akka-http-core/src/main/java/akka/http/javadsl/model/headers/ModeledCustomHeader.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/ModeledCustomHeaderCompanion.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/ModeledCustomHeaderFactory.java, docs/src/main/paradox/java/http/common/http-model.md, docs/src/test/java/docs/http/javadsl/CustomHeaderExampleTest.java
Issue: #761 triggered in PR #844
First attempt to offer Custom Header Support
Add docs and javadoc
=> Custom Header Support #761

akka-http-tests/src/test/java/akka/http/javadsl/server/UnmarshallerTest.java, akka-http/src/main/scala/akka/http/javadsl/unmarshalling/Unmarshaller.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/Unmarshal.scala
Issue: #967
Port of the equivalent of `Unmarshal#to` to javadsl
Add test
=> Enable javadsl to unmarshal with default ec #967

docs/src/main/paradox/release-notes.md
Issue: #975
Provide release notes for release 10.0.5
=> Add release notes for 10.0.5 #975

akka-http-core/src/main/scala/akka/http/scaladsl/model/RemoteAddress.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
=> =htc #440 Exclude port when rendering X-Forwarded-For and X-Real-Ip

docs/src/main/paradox/java/http/client-side/pool-overflow.md, docs/src/main/paradox/scala/http/client-side/pool-overflow.md
=> =doc #997 fix setting path in pool-overflow docs

docs/src/main/paradox/java/http/common/http-model.md, docs/src/main/paradox/scala/http/common/http-model.md, docs/src/test/java/docs/http/javadsl/server/directives/CustomHttpMethodExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/CustomHttpMethodSpec.scala
Refs #954 
Adding description and a code example for HTTP custom methods in doc.
=> Add HTTP custom method example to doc

docs/src/main/paradox/java/http/routing-dsl/directives/header-directives/headerValue.md, docs/src/test/java/docs/http/javadsl/server/directives/HeaderDirectivesExamplesTest.java
Issue: #639
Java example on how to provide a default value for a header extractor using directive composition
Reformatted the code
=> Extract headerValue with default value Java #639

akka-http/src/main/scala/akka/http/javadsl/marshalling/Marshaller.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/Marshaller.scala
=htp #1017 document marshalling behaviour of oneOf
=> =htp #1017 document marshalling behaviour of oneOf

akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterfaceActor.scala
Before, the log source was the descriptive string that describes
the pool but that can be hard to match on in logging backends. Now,
logging backends will see "PoolGateway" as the source for all pool
logging statements (still not quite the common practice but will
simplify to filter on all messages relating to the client pool).
Fixes #1013.
=> =htc #1013 make sure pool logs have set "PoolGateway" as logClass

akka-http/src/main/scala/akka/http/scaladsl/marshalling/Marshaller.scala
Small cleanup following up to https://github.com/akka/akka-http/pull/1019
=> =htc inline lambdas in Marshaller

akka-http/src/main/scala/akka/http/scaladsl/marshalling/Marshaller.scala, project/plugins.sbt
I have this nagging feeling this could be made more elegant by doing something
other than making these anonymous `Marshaller` subclasses and overriding
'compose', but for now this'll do :).
=> Some more lambda inlining (#1019)

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/AlpnSwitch.scala
This technically is very similar to CoupledTerminationFlow,
however since it's "sub" sources/sinks we could not directly use that.
Resolves https://github.com/akka/akka-http/issues/886
I may have overdone the binding of completions/cancels, however I'd rather do it this way now than omit a case. The important one is when downstream cancels net AFAIR - that is enough to make curl testing not leak.
=> =h2 #886 fix leaks in ALPN switcher

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/AlpnSwitch.scala
=> =h2 #886 Remove unnecessary complete call

docs/src/main/paradox/scala/http/routing-dsl/directives/index.md, docs/src/test/scala/docs/http/scaladsl/server/DirectiveExamplesSpec.scala
Added one example of `concat` combinator usage.
=> Added an example of route.concat usage, fixes #1020

akka-http-core/src/main/scala/akka/http/impl/engine/Http2Shadow.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http2-support/src/test/scala/akka/http/scaladsl/Http2BindingViaConfigSpec.scala
Review follow up from https://github.com/akka/akka-http/pull/1062
=> =htc move Http2Shadow to impl package

akka-http-core/src/main/mima-filters/10.0.6.backwards.excludes, project/ValidatePullRequest.scala
and also trigger PR validation when Mima.scala changes.
=> Add missing 10.0.6 mima rules

akka-http-core/src/test/scala/akka/http/javadsl/HttpExtensionApiSpec.scala
so we dont have too many servers running at the same time, which may have been a reason for
tiem timeouts - just too many servers active at the same time perhaps
The timeouts max is 10 seconds, but usually it won't take that long, but is better than failing once in a while randomly
Resolves https://github.com/akka/akka-http/issues/1071
=> =htc #1071 increase timeout and wait for unbind

docs/src/main/paradox/_template/page.st, project/plugins.sbt
Depends on https://github.com/lightbend/paradox/pull/110
=> Add 'canonical' link

docs/src/main/paradox/scala/http/common/xml-support.md
Issue: #1111 
Use same style for dependency as on the other pages
Some rewordings
=> =docs fix dependency text and minor wordings for xml support #1111

build.sbt, project/AkkaDependency.scala, project/Dependencies.scala
Introduce an `akkaVersion` sbt setting to make it easier to run tests
againt both Akka version 2.4 and 2.5 in preparation of #826. Change the
Akka version with the following command:
sbt> set akka.Dependencies.akkaVersion in ThisBuild := "2.5.1"
Also bump the Akka version to 2.4.18 and the Scala version to 2.11.11 to
avoid Scala version update warnings as reported in #1101.
---
The goal is to fix #826, by enabling us to configure Jenkins to run the test suite for both latest Akka version 2.4 and 2.5. I am not sure if this is compatible with how ValidatePullRequest is invoked in Jenkins.
Example usage:
```
> sbt
akka-http-root > akkaVersion
[info] akka-http-testkit/*:akkaVersion
[info] 	2.4.18
[info] akka-http-core/*:akkaVersion
[info] 	2.4.18
...
akka-http-root > akka-http-core/compile …
```
=> Make the Akka artifact version configurable

project/build.properties, project/plugins.sbt
To fix the incompatibility with current akka master.
=> =pro update to latest sbt and sbt-paradox-akka

docs/src/main/paradox/release-notes.md
Thought to add info right away
=> Add info about seed templates

build.sbt, project/plugins.sbt
Based on akka/akka#22987.
---
Fixes #1129 by upgrading to first officially released version.
=> =doc Fix #1129: Use paradox akka-theme artifacts from jcenter

akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala, akka-http/src/main/scala/akka/http/scaladsl/server/Route.scala
Smallish optimization for base routing infrastructure.
=> Optimize route sealing

docs/src/main/paradox/release-notes.md
=> release notes for 10.0.7

docs/src/test/scala/docs/http/scaladsl/server/FullSpecs2TestKitExampleSpec.scala
=> Replaced wrong equals assertion in docs #1136

docs/src/test/java/docs/http/javadsl/server/directives/CustomHttpMethodExamplesTest.java
=> Setup timeout in CompletableFuture.

akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaRange.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MarshallingDirectivesSpec.scala
=> Add specific handling for `charset` param when comparing MediaTypes #1139

akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/JUnitRouteTest.scala
=> =htk #1147 don't reference JUnitSuiteLike in Java JUnit testing infrastructure

akka-http-core/src/main/java/akka/http/javadsl/model/MediaTypes.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/LastEventId.java, akka-http-core/src/main/java/akka/http/javadsl/model/sse/ServerSentEvent.java, akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/sse/ServerSentEvent.scala, akka-http-core/src/test/java/akka/http/javadsl/model/sse/ServerSentEventTest.java, akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/sse/ServerSentEventSpec.scala, akka-http-tests/src/test/java/akka/http/javadsl/marshalling/sse/EventStreamMarshallingTest.java, akka-http-tests/src/test/java/akka/http/javadsl/unmarshalling/sse/EventStreamUnmarshallingTest.java, akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/sse/EventStreamMarshallingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/UnmarshallingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/sse/BaseUnmarshallingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/sse/EventStreamUnmarshallingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/sse/LineParserSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/sse/ServerSentEventParserSpec.scala, akka-http/src/main/scala/akka/http/javadsl/marshalling/sse/EventStreamMarshalling.scala, akka-http/src/main/scala/akka/http/javadsl/unmarshalling/sse/EventStreamUnmarshalling.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/sse/EventStreamMarshalling.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/sse/EventStreamParser.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/sse/EventStreamUnmarshalling.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/sse/LineParser.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/sse/ServerSentEventParser.scala
Docs still need to be written, but before I'm going down that bumpy road I'd like to get the OK for the code.
=> Include Akka SSE

docs/src/main/paradox/scala/http/routing-dsl/index.md
=> Typo in docs

docs/src/main/paradox/scala/http/common/http-model.md
It must be a link to the companion, previous link was 404
=> =doc fix link to companion object docs in http model

akka-http-core/src/main/resources/reference.conf
=> Removed proxy from conf per #1227

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameRendering.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala
=> Http2 debug logging using StageLogging

.gitignore, build.sbt, docs/src/main/paradox/java/http/compatibility-guidelines.md, docs/src/main/paradox/java/http/index.md, docs/src/main/paradox/scala/http/compatibility-guidelines.md, docs/src/main/paradox/scala/http/index.md
Explained in depth a bit about how to use 2.5 with 10.0 as well as linked to bin compat rules.
The question keeps coming up so good to have it in docs
=> =doc explain compatibility with akka 2.5

akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/HttpAppSpec.scala, akka-http/src/main/java/akka/http/javadsl/server/HttpApp.java, akka-http/src/main/scala/akka/http/scaladsl/server/HttpApp.scala, docs/src/main/paradox/scala/http/routing-dsl/HttpApp.md, docs/src/test/java/docs/http/javadsl/server/HttpAppExampleTest.java, docs/src/test/scala/docs/http/scaladsl/HttpAppExampleSpec.scala
Issue: #1294
Add overloaded HttpApp.startServer method
Add docs for this new method
Add tests for this new method
=> +htp Provide overloaded HttpApp.startServer method with system #1294

docs/src/main/paradox/java/http/routing-dsl/testkit.md, docs/src/main/paradox/scala/http/routing-dsl/testkit.md, docs/src/test/java/docs/http/javadsl/server/testkit/MyAppFragment.java, docs/src/test/java/docs/http/javadsl/server/testkit/TestKitFragmentTest.java, docs/src/test/java/docs/http/javadsl/server/testkit/WithTimeoutTest.java, docs/src/test/scala/docs/http/scaladsl/server/TestKitFragmentSpec.scala
Issue: #1152
* Provide Snippet for Java
* Provide Snippet for Scala
* Add docs for both.
=> =doc Explain how to increase default timeout on tests #1152

akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/HttpChallenge.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
=> Fixes rendering of HttpChallenge if no realm is set

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
=> Reject CONNECT requests gracefully

project/plugins.sbt
As the features in the forked release are now in sbt-bintray upstream https://github.com/sbt/sbt-bintray/pull/113
=> #1355 Upgrade to latest sbt-bintray

akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
=> Prevent early connection closure over https #1219

akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
There's an unlikely race condition that requests might not get
scheduled to one connection each but several requests to one slot. In
that case that slot will open more than one connection. However, with
`Connection: close`, we will need to accept more than the `minConnections`
manually accepted connections.
Using `autoAccept` should make the test more robust.
(Hopefully) fixes #299.
=> =htc #299 use autoAccept for failing test case

RELEASING.md, build.sbt, docs/src/main/paradox/scala/http/compatibility-guidelines.md, docs/src/main/paradox/scala/http/introduction.md, project/Dependencies.scala
=> =doc add more prominent instructions about how to run with Akka 2.5

docs/src/main/paradox/scala/http/common/http-model.md
=> =doc Change Multipart.Bodypart to Multipart.BodyPart for issue #1414

akka-http-tests/src/test/scala/akka/http/scaladsl/Main.scala, akka-http/src/main/java/akka/http/javadsl/server/HttpApp.java, akka-http/src/main/scala/akka/http/scaladsl/server/HttpApp.scala, build.sbt, docs/src/main/paradox/scala/http/routing-dsl/HttpApp.md, docs/src/test/java/docs/http/javadsl/server/HttpAppExampleTest.java, docs/src/test/scala/docs/http/scaladsl/HttpAppExampleSpec.scala
We had received some questions from customers regarding whether the system will be terminated when provided to the HttpApp. This adds a clarification and also points to Coordinated Shutdown for more elaborate shutdown scenarios.
=> Clarify system lifecycle when provided to HttpApp

docs/src/main/paradox/java/http/common/unmarshalling.md, docs/src/main/paradox/scala/http/common/unmarshalling.md
=> =doc Change marshallers to unmarshallers #1422

akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/HeaderDirectives.scala, build.sbt, docs/src/main/paradox/scala/http/common/http-model.md, docs/src/main/paradox/scala/http/common/json-support.md, docs/src/main/paradox/scala/http/common/xml-support.md, docs/src/main/paradox/scala/http/routing-dsl/directives/custom-directives.md, docs/src/main/paradox/scala/http/routing-dsl/testkit.md, docs/src/main/paradox/scala/http/server-side/http2.md, project/plugins.sbt
=> Update Paradox and docs to use new features

akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
That is we are simulating a TLS truncation attack here. Before
https://github.com/akka/akka/pull/21786 the TLS stage just got stuck
(I tested again an old Akka version).
Now, all streams are properly closed and also the response entity
stream is completed. A stricter version would actually fail the response
entity stream when TLS truncation is detected. If that is worthwhile is
actually questionable. See https://github.com/akka/akka-http/issues/235
for more information.
Finally fixes #380.
=> =htc #380 add test case for server->client missing close_notify scenario

docs/src/main/paradox/scala/http/sse-support.md
=> Minor fix on sse support docs

docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/SprayJsonExampleSpec.scala
* one for "HTTP client API"
* another for "Routing DSL for HTTP servers"
=> Add two runnable examples for issue #1408.

akka-http-core/src/main/scala/akka/http/impl/util/LogByteStringTools.scala
Small improvement in logging so it's more understandable.
=> =htc slight logging tag improvement in wire logging stage

akka-http-core/src/main/mima-filters/10.0.10.backwards.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/ConnectionContext.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Fixes #1449.
Makes default http and https ports set via configuration file.
=> Default http and https port configurations.

CONTRIBUTING.md, README.md
Also link to CoC on our README
=> Rename "community" label to "help wanted" as suggested by Github

akka-http-core/src/main/scala/akka/http/impl/util/LogByteStringTools.scala
Padding looked weird for me and the result was not a string but a Vector
whose toString looked not quite right ;)
=> =htc Fix logToStringBidi

docs/src/main/paradox/scala/http/compatibility-guidelines.md
Because a BUG in https://github.com/lightbend/paradox/issues/161 , the empty line is breaking the format.
Previous change was related with https://github.com/akka/akka-http/pull/1483
=> Remove empty lines because Pradox bug

akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/CacheDirective.scala
This updates the link of the http. immutable response to the latest RFC.
=> =doc update link for http immutable response (#1512)

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
Fixes #1515
Ensures that we only push to the WebSocket handling flow if it has first pulled.
I've tested this against the reproducer for this that we had in Lagom (https://github.com/lagom/lagom/pull/1054), and I haven't been able to reproduce after several test runs, whereas before I was reproducing on every test run.
=> Fix race condition in WebSocket switch

docs/src/main/paradox/scala/http/migration-guide/migration-from-spray.md
=> =doc #1505 be less drastic about whether akka http still uses actors

docs/src/test/scala/docs/http/scaladsl/server/directives/DebuggingDirectivesExamplesSpec.scala
=> Refine type in logRequestResult documentation example #1520

akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/HttpAppSpec.scala
.. and suppress it while we're at it
=> Be explicit about expected logging

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MarshallingDirectivesSpec.scala
And filter it out of the output
=> Explicitly expect log message during test

akka-http-bench-jmh/README.md, akka-http-bench-jmh/src/main/scala/akka/BenchRunner.scala, akka-http-bench-jmh/src/main/scala/akka/http/scaladsl/unmarshalling/sse/LineParserBenchmark.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/sse/LineParserSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/sse/LineParser.scala, build.sbt
Minor change improving the performance of the LineParser for SSE Unmarshaller
=> Improve performance of LineParser for SSE unmarshalling #1508

project/Dependencies.scala
- akka 2.5.6 -> 2.5.7
- akka 2.4.19 -> 2.4.20
- cross Scala 2.12.3 -> 2.12.4
=> Dependency updates

akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/sse/LineParser.scala
A small follow up to #1510 renaming other instances of the new flag and moving comments for better readability. Also changed the constants to upper letters according to our standards.
/cc @kennedyoliveira
=> =htp #1508 cosmetic changes: rename remaining var and move comments

akka-http-core/src/main/mima-filters/10.0.10.backwards.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ParserSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ParserSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ParserSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Do you think that would suffice for now, @richdougherty?
/cc @richdougherty
=> +htc #1550 allow disabling of parsing to modeled headers

akka-http-tests/src/test/java/akka/http/javadsl/server/MinimalHttpApp.java, akka-http-tests/src/test/java/akka/http/javadsl/server/SneakHttpApp.java, akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/HttpAppSpec.scala
=> =htp #1569 avoid relying on racy temporaryHostNameAndPort()

build.sbt, docs/src/main/paradox/scala/http/compatibility-guidelines.md, docs/src/main/paradox/scala/http/introduction.md, docs/src/main/paradox/scala/http/release-notes.md
Not sure it even builds like this currently, so lets see where we can get with this.
=> Make akka-actor / akka-stream a provided dependency

akka-http-caching/src/main/mima-filters/10.0.11.backwards.excludes, akka-http-caching/src/main/scala/akka/http/caching/LfuCache.scala, akka-http-caching/src/main/scala/akka/http/caching/scaladsl/Cache.scala, akka-http-caching/src/test/scala/akka/http/caching/ExpiringLfuCacheSpec.scala
(Tentatively) fixes #1536
(cc: @ktoso, @ben-manes)
=> Add non-lambda-capturing getOrLoad method to Cache (#1536)

project/plugins.sbt
=> sbt-api-mappings 2.0.1

project/ParadoxSupport.scala
=> =pro #1633 run class scanner only once per run

akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Refs #492
I guess there could have been a delay between the moment the request was taken
from the connection and the moment it was passed to the handler?
=> Harden ClientServerSpec

docs/src/main/paradox/scala/http/release-notes.md
=> =doc #1603 add note to 10.0.11 release notes about top-level HTTP API changes

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
Refs: #1623
Changed the return type to the corresponding Scala DSL one
I think this is Binary compatible
=> =htc Fix return type for `withStatus` methods #1623

akka-http-core/src/main/resources/reference.conf
ConnectionPoolSpec is already/still ran for both
=> Set default connection-pool to 'new'

akka-http-core/src/main/java/akka/http/javadsl/model/Authority.java, akka-http-core/src/main/java/akka/http/javadsl/model/ContentTypes.java, akka-http-core/src/main/java/akka/http/javadsl/model/HttpEntity.java, akka-http-core/src/main/java/akka/http/javadsl/model/HttpHeader.java, akka-http-core/src/main/java/akka/http/javadsl/model/HttpMessage.java, akka-http-core/src/main/java/akka/http/javadsl/model/Uri.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/Host.java, akka-http-core/src/main/mima-filters/10.0.11.backwards.excludes, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/Uri.scala, docs/src/test/java/docs/http/javadsl/server/directives/BasicDirectivesExamplesTest.java
These were discovered while working on a play-ws Akka Http backend.
=> Add more Java Api

akka-http-core/src/main/java/akka/http/javadsl/model/HttpResponse.java, docs/src/main/paradox/client-side/request-level.md, docs/src/test/java/docs/http/javadsl/HttpClientExampleDocTest.java, docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala
Adds collecting headers examples for Java and Scala client-side API
=> Documentation for collecting headers (#205)

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CodingDirectivesSpec.scala
=> Increased timeout for coding spec 

project/build.properties
This fixes the build problem that Akka had as well: https://github.com/akka/akka/issues/23859
=> Update SBT and fix the spurious NPE errors in javac

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FutureDirectivesSpec.scala, docs/src/test/java/docs/http/javadsl/server/directives/FutureDirectivesExamplesTest.java
=> Circuitbreaker directive test failures fix

akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
=> More logging for #1667

project/build.properties
I just realized we had RC4 in `project/build.properties`
=> =pro Update to sbt 1.1.0

akka-http-core/src/main/java/akka/http/javadsl/model/StatusCodes.java, akka-http-core/src/main/scala/akka/http/scaladsl/model/StatusCode.scala
Status code document at https://tools.ietf.org/html/rfc7540#section-9.1.2
=> Add HTTP status code 421

docs/src/main/paradox/routing-dsl/directives/index.md
=> =doc change the formation of the & operator

akka-http-core/src/main/scala/akka/http/impl/engine/ws/Utf8Encoder.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/Utf8CodingSpecs.scala
=> =htc #1760 fix utf16 surrogate pair decoding in utf8 encoder

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala
=> =htc #1774 ignore "request entity completed" in state WaitingForResponseDispatch

CONTRIBUTING.md, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HttpsProxyGraphStageSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerTestSetupBase.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/PrepareRequestsSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/ByteStringSinkProbe.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketIntegrationSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/TightRequestTimeoutSpec.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/WSProbe.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/DontLeakActorsOnFailingConnectionSpecs.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, docs/src/main/paradox/contributing.md
And accidentally also fixed #510  :)
=> Cleaning up some tests

akka-http-core/src/main/java/akka/http/javadsl/model/headers/UserAgent.java, akka-http-tests/src/test/java/akka/http/javadsl/server/directives/HeaderDirectivesTest.java
This was found while working on https://github.com/playframework/play-ws/pull/227
=> Add UserAgent header parse Java Api

akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
=> =htc #1790 loosen timeout in ClientServerSpec

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
=> Log the timed out request

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpAttributes.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/AlpnSwitch.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> Add `Tls-session-info` header for http/2

akka-http-testkit/src/test/java/akka/http/javadsl/testkit/JUnitRouteTestTest.java, akka-http-tests/src/main/java/akka/http/javadsl/server/examples/simple/SimpleServerApp.java, akka-http-tests/src/test/java/akka/http/javadsl/server/CompleteTest.java, akka-http-tests/src/test/java/akka/http/javadsl/server/JavaRouteTest.java, akka-http-tests/src/test/java/akka/http/javadsl/server/directives/RouteDirectivesTest.java, akka-http-tests/src/test/java/docs/http/javadsl/server/HandlerExampleDocTest.java, akka-http/src/main/scala/akka/http/javadsl/server/directives/FutureDirectives.scala, docs/src/test/java/docs/http/javadsl/JacksonExampleTest.java, docs/src/test/java/docs/http/javadsl/server/FileUploadExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/BasicDirectivesExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/FileUploadDirectivesExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/FutureDirectivesExamplesTest.java
Doesn't usually seem necessary?
=> Do we need/want javadsl onSuccess to take a Supplier?

akka-http-core/src/main/scala/akka/http/scaladsl/model/Uri.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala
=> Uri.Path ?/ operator #1793

akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/ByteStringSinkProbe.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala, akka-http-core/src/test/scala/akka/http/impl/util/WithLogCapturing.scala, akka-http-core/src/test/scala/akka/http/scaladsl/SslConfigWarningsSpec.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala, akka-http/src/main/scala/akka/http/javadsl/unmarshalling/Unmarshaller.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToResponseMarshallers.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/BasicDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/GenericUnmarshallers.scala, akka-parsing/src/main/scala/akka/parboiled2/ErrorFormatter.scala
- akka.stream.impl.ConstantFun => akka.util.ConstantFun
- ''' => '\''
- Left.a => Left.value
- Remove unused imports
=> Fix a few warnings

docs/src/test/java/docs/http/javadsl/RespondWithHeaderHandlerExampleTest.java
=> =doc fix copyright header

docs/src/main/paradox/common/caching.md, docs/src/main/paradox/routing-dsl/directives/caching-directives/index.md, docs/src/main/paradox/routing-dsl/testkit.md, docs/src/main/paradox/server-side/http2.md
Like in https://github.com/akka/akka/pull/24418
=> Make sure dependencies show up in ToC

docs/src/main/paradox/_template/search.st
/cc @2m Can you remember why you removed it in https://github.com/akka/akka-paradox/commit/4e95359edc579ce52c6593c69c086047feed5d74#diff-9633475f0a69337a44c2cddc976c2844?
Refs #1587.
=> =doc #1587 override search.st from akka-paradox to add back version filter

build.sbt
Previous code assumed a certain order of entries returned by the
`unidoc` task. We now search the entries for "java" and take this one
as javadoc and the other one as scaladoc.
Fixes #1712.
=> =pro #1712 fix API doc upload

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
Moved creation of `AsyncCallback` one level up so that it won't be created each time `grab(requestIn)` is invoked.
Addresses comment on issue #1575
=> Removing creation of callback per grabbed request

akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala
=> Allows Sec-WebSocket-Extensions in requests

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/PathDirectivesSpec.scala, docs/src/main/paradox/routing-dsl/path-matchers.md
resolves https://github.com/akka/akka-http/issues/1861
adds some more docs for the confusing case
=> +doc #1861 add docs and tests for combining | with / in paths

README.md
=> =pro #1185 Add note to README for purpose of Github Issues

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala
=> Support for trailing response headers in HTTP/2

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpMessageSpec.scala
=> return 400 instead of 500 for requests with invalid URI scheme #36

akka-http-core/src/main/java/akka/http/javadsl/model/HttpMessage.java, akka-http-core/src/main/mima-filters/10.0.11.backwards.excludes, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpMessageSpec.scala, docs/src/test/java/docs/http/javadsl/HttpClientExampleDocTest.java, docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala
Refs: #1731
Java implementation is duplicated but I can't make type checker happy otherwise
Update examples in docs
=> +htc Add headers and getHeaders method to HttpMessage #1731

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Fixes the problem reported in #1882.
=> =ht2 #1882 fix HTTP/2 trying to send even if stream window was depleted

.travis.yml, akka-http-core/src/main/mima-filters/10.0.11.backwards.excludes, akka-http/src/main/mima-filters/10.0.11.backwards.excludes, build.sbt, docs/src/main/paradox/compatibility-guidelines.md, docs/src/main/paradox/introduction.md, project/AkkaDependency.scala, project/Dependencies.scala
This will simplify the jenkins setup.
=> =pro introduce "-Dakka.build.version=master" to build against Akka git master

docs/src/main/paradox/server-side/server-https-support.md, docs/src/main/paradox/server-side/websocket-support.md, project/AkkaDependency.scala
=> update akka version to 2.5.11 and fix docs #1892

akka-http-core/src/main/mima-filters/10.0.11.backwards.excludes, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/TypedActorSystemSpec.scala, build.sbt
As per https://github.com/akka/akka-http/issues/1873#issuecomment-367655223
=> create internal actors in the system namespace

akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
=> =htc #1757 create a new server binding for each new test to avoid interaction between test cases

akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
To help troubleshooting failures.
Refs #1886.
=> =htc #1886 add WithLogCapturing and log more in failure cases

akka-http-core/src/main/mima-filters/10.0.11.backwards.excludes
=> =htc #1905 fix mima failure in 2.11

akka-http-caching/src/main/scala/akka/http/scaladsl/server/directives/CachingDirectives.scala, docs/src/main/paradox/compatibility-guidelines.md, docs/src/test/scala/docs/ApiMayChangeDocCheckerSpec.scala, project/Dependencies.scala
Refs: #1106
Add the list of APIs that are marked as `@ApiMayChange`
=> List APIs that may change #1106

build.sbt, project/AutomaticModuleName.scala
I think I didn't miss any.
Resolves https://github.com/akka/akka-http/issues/1853
=> =pro #1853 automatic module names

build.sbt
Fixes the 'other' half of #1895
=> Add javadoc generation for akka-http-caching

akka-http-core/src/main/scala/akka/http/scaladsl/settings/ConnectionPoolSettings.scala
Yes, moving lines around is the only thing necessary here...
=> =pro fix javadoc generation

akka-http-core/src/main/java/akka/http/impl/util/Util.java, akka-http-core/src/main/java/akka/http/javadsl/model/Uri.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/LinkParams.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/LinkValue.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/Location.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/Referer.java, akka-http-core/src/main/mima-filters/10.1.0.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/model/JavaUri.scala
backport of https://github.com/akka/akka-http/pull/1950
=> BACKPORT Support conversion between scaladsl.Uri and javadsl.Uri (#1950)

akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala
Backports https://github.com/akka/akka-http/pull/1860
=> BACKPORT Allows Sec-WebSocket-Extensions in requests

docs/src/test/java/docs/http/javadsl/server/directives/CachingDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/CachingDirectivesExamplesSpec.scala
=> Cache docs: more explicit imports, create cache once

.travis.yml
Produces so much output it interferes with the job.
=> Skip travis cleanup

project/plugins.sbt
=> Update to the latest MiMa

docs/src/main/paradox/routing-dsl/index.md, docs/src/test/java/docs/http/javadsl/HttpServerDynamicRoutingExampleTest.java, docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
=> Add dynamically updating routes example (#1471)

.travis.yml, akka-http-core/src/main/mima-filters/10.0.1.backwards.excludes, akka-http-core/src/main/mima-filters/10.1.1.backwards.excludes, akka-http-core/src/main/scala/akka/http/javadsl/model/ws/Message.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/ws/Message.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
Revives @rbudzko's  https://github.com/akka/akka-http/pull/611
I agree with Johannes about adding better API https://github.com/akka/akka-http/issues/1979 however this PR was good by itself as well and would improve status quo.
=> WebSocket toStrict

akka-http2-support/src/test/scala/akka/http/h2spec/H2SpecIntegrationSpec.scala
But skip those that are currently not yet passing
=> Run h2spec integration tests

project/AkkaDependency.scala
resolves https://github.com/akka/akka-http/issues/2009
=> Update akka dependency to 2.5.12

akka-http-core/src/main/java/akka/http/javadsl/model/MediaTypes.java, docs/src/main/paradox/routing-dsl/source-streaming-support.md, docs/src/test/java/docs/http/javadsl/server/directives/JsonStreamingFullExample.java
and additional example for JAVA API (was missing in documentation).
Refs: #2008
=> Adds missing methods for creating custom binary MediaTypes (#2008)

project/build.properties, project/plugins.sbt
* sbt-jmh - bump to 0.3.4 for GraalVM
* sbt-paradox-akka - use the same version at Akka
* sbt-header - use the same version at Akka
=> Update sbt and sbt-plugins

akka-http-core/src/main/scala/akka/http/impl/model/parser/CommonActions.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/HeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ParserSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
=> Backport: Support parameters for custom media types

project/build.properties
Will then cherry pick this on the release-10 branch to allign it with akka so that the release-10/akka-master build works again
=> Upgrade to sbt 1.1.6

project/Dependencies.scala
I ran sbt-updates to check if we had dependencies that could be bumped, and I found these 2
=> =pro Update specs and gson dependencies

project/build.properties
To fix the release-10 / akka master build
=> [backport from master] Upgrade to sbt 1.1.6

akka-http-core/src/main/mima-filters/10.1.2.backwards.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/ServerTerminator.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/ServerBinding.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, akka-http-core/src/test/java/akka/http/javadsl/GracefulTerminationCompileTest.java, akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
Resolves: https://github.com/akka/akka-http/issues/188
Relates to https://github.com/akka/akka/pull/18475
Still some pondering to do in the terminating phase in the terminator, but generally seems correct.
I also will clean up documentation, but please review already
=> "Graceful" Server Termination #188

akka-http-tests/src/test/java/akka/http/javadsl/server/directives/ParameterDirectivesTest.java, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ParameterDirectivesSpec.scala, akka-http/src/main/scala/akka/http/javadsl/server/Rejections.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/ParameterDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/Rejection.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/ParameterDirectives.scala, docs/src/main/paradox/routing-dsl/directives/parameter-directives/parameters.md, docs/src/test/java/docs/http/javadsl/server/directives/ParameterDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/ParameterDirectivesExamplesSpec.scala
and updates documentation
Refs: #2025
=> Adds missing parameter with required value directive for Java API (#2025)

docs/src/main/paradox/common/caching.md, docs/src/test/java/docs/http/javadsl/server/directives/CachingDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/CachingDirectivesExamplesSpec.scala
This PR is meant to improve the code snippets provided for the caching module as mentioned in #2060
=> improve caching code sample

akka-http-core/src/main/scala/akka/http/impl/engine/server/ServerTerminator.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
We forgot to remove the terminators once a connection has terminated.
Resolves #2067
=> =htc #2067 fix memory leak in server terminators

akka-http-core/src/main/scala/akka/http/impl/engine/server/ServerTerminator.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
=> Avoid eagerly failing connections when request closes

akka-http-caching/src/main/scala/akka/http/javadsl/server/directives/CachingDirectives.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-core/src/main/scala/akka/http/javadsl/ConnectionContext.scala, akka-http-core/src/main/scala/akka/http/scaladsl/ClientTransport.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/pool/SlotStateSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/settings/PreviewServerSettingsSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/util/FastFutureSpec.scala, akka-http-tests/src/multi-jvm/scala/akka/http/AkkaHttpServerLatencyMultiNodeSpec.scala, akka-http-tests/src/multi-jvm/scala/akka/remote/testkit/MultiNodeConfig.scala, akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/CustomMediaTypesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/HttpAppSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, akka-http2-support/src/test/scala/akka/http/h2spec/H2SpecIntegrationSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/scaladsl/Http2BindingViaConfigSpec.scala
Went through some no-brainer warning fixes within the project
=> Fix some warnings

CONTRIBUTING.md
Fix a missing space
Add information on the when is OK to ignore MiMa pointing to the `@InternalApi`, `@DoNotInherit`, and `@ApiMayChange`
Convert a couple of words from British English to American English (I think we mainly use American English)
=> Add info in MiMa ignore section about @InternalApi and co

akka-http-tests/src/test/java/docs/http/javadsl/server/RouteJavaScalaDslConversionTest.java, akka-http-tests/src/test/scala/akka/http/scaladsl/RouteJavaScalaDslConversionSpec.scala, akka-http/src/main/mima-filters/10.1.3.backwards.excludes, akka-http/src/main/scala/akka/http/javadsl/server/Route.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteAdapter.scala, docs/src/main/paradox/routing-dsl/routes.md
Resolves https://github.com/akka/akka-http/issues/891
=> +htp #891 allow java/scala conversion for Routes for users

akka-http-core/src/main/java/akka/http/javadsl/model/headers/ModeledCustomHeader.java, docs/src/main/paradox/common/http-model.md
* removes offending scala/java directives
=> remove misplaced directives

docs/src/test/scala/docs/http/scaladsl/server/directives/RouteDirectivesExamplesSpec.scala
in Scala code example for 'complete'
=> Show off GenericMarshallers.futureMarshaller

docs/src/main/paradox/server-side/index.md
This PR is about fixing a small typo in server side.
=> Fix Typo In Doc For Server Side.

docs/src/main/paradox/routing-dsl/directives/security-directives/authenticateBasic.md, docs/src/main/paradox/routing-dsl/directives/security-directives/authenticateBasicAsync.md
=> updated outdated SecurityDirectives documentation

akka-http-testkit/src/main/resources/reference.conf, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/MarshallingTestUtils.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/ScalatestUtils.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/MarshallingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/MultipartUnmarshallersSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/UnmarshallingSpec.scala, docs/src/main/paradox/server-side/low-level-api.md
@ktoso this is the PR on the timeout (we were chatting about it in gitter) - I think this should work but you were mentioning about requiring an implicit actor system so I'm not sure if I'm missing something here
=> Refactored out the 1 seconds marshalling timeout from MarshallingTestUtils so it can be configured (#2127)

akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocketClientBlueprint.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketClientSpec.scala
Refs #2151.
I would've liked to add a test that checks whether this still works when the
second message is sent partially, but I couldn't figure out who to convince
WebSocketClientSpec to exchange multiple messages even in the simple case...
=> Accept websocket headers in parts

akka-http-core/src/main/java/akka/http/javadsl/model/sse/ServerSentEvent.java, akka-http-core/src/test/java/akka/http/javadsl/model/sse/ServerSentEventTest.java, akka-http-core/src/test/scala/akka/http/scaladsl/model/sse/ServerSentEventSpec.scala
Refs: #2187
Add tests for both Java and Scala DSL for heartbeat
=> Add missing ServerSentEvent.heartbeat for JavaDSL #2187

akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
=> Introduce a sleep to make sure termination propagated

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
=> Enable HTTP/2 chunked responses #2217

akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
=> Disable maxRetries test for Legacy client pool

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala
Also makes sure that state var is only mutated in a controlled way
=> =htc log time spent in a pool slot for simpler spotting of slow transition periods

build.sbt, docs/src/main/paradox/release-notes/10.1.x.md
Refs: #2262
Add info about this in release notes
=> Make akka-stream-testkit dependency provided for akka-http-testkit #2262

akka-http-core/src/main/scala/akka/http/javadsl/ConnectionContext.scala
Even better would be to actually show Java code here
=> Remove implementation from javadsl API docs

akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala, project/ValidatePullRequest.scala
=> Perform null check when constructing RawHeader

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/javadsl/settings/ConnectionPoolSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HighLevelOutgoingConnectionSpec.scala, docs/src/main/paradox/client-side/connection-level.md, docs/src/main/paradox/client-side/host-level.md, docs/src/main/paradox/common/timeouts.md
=> Clarify client-side pipelining is not supported

akka-http/src/main/scala/akka/http/javadsl/server/directives/CodingDirectives.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/CookieDirectives.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/MiscDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RouteResult.scala
I tried to remove what seems it unnecessary.
=> Remove toSeq

docs/src/main/paradox/common/unmarshalling.md
With this note I think we can demote #17 from 'bug' to 'enhancement'
=> Clarify unmarshallers should consume or cancel the entity body

akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala, project/AkkaDependency.scala
Should fix compiling tests on java 11, #2243
=> Update akka to 2.5.19

project/Dependencies.scala
Refs https://github.com/akka/akka-http/issues/2329
=> [10.0 backport] Dependency upgrades

docs/src/main/paradox/release-notes/10.0.x.md
(will cherry-pick this to also apply it to master after review/merge)
=> 10.0.15 release notes

docs/src/main/paradox/release-notes/10.0.x.md
=> 10.0.15 release notes (#2362)

akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala
=> Be more lenient in hash performance difference expectation

akka-http-core/src/main/scala/akka/http/scaladsl/model/ErrorInfo.scala, akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala, docs/src/main/paradox/routing-dsl/exception-handling.md, docs/src/test/java/docs/http/javadsl/RespondWithHeaderHandlerExampleTest.java, docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala
=> Do not include error details in HTTP response

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala
Previously, the error message was only triggered if the first space (0x20)
character was found before `maxMethodLength`. Now, it will trigger in all
cases when the first character of the request is 0x16.
Fixes #1886.
=> =htc more reliable detection of HTTPS => HTTP connection attempts, fixes #1886

LICENSE, akka-http-core/src/main/java/akka/http/javadsl/model/headers/RetryAfter.java, akka-http/src/main/boilerplate/akka/http/javadsl/server/JavaPathMatchers.scala.template, akka-http/src/main/boilerplate/akka/http/scaladsl/server/util/ApplyConverterInstances.scala.template, akka-http/src/main/boilerplate/akka/http/scaladsl/server/util/ConstructFromTupleInstances.scala.template, akka-http/src/main/boilerplate/akka/http/scaladsl/server/util/TupleAppendOneInstances.scala.template, akka-http/src/main/boilerplate/akka/http/scaladsl/server/util/TupleFoldInstances.scala.template, project/AkkaDependency.scala, project/AutomaticModuleName.scala, project/CliOptions.scala, project/CopyrightHeader.scala, project/Dependencies.scala, project/Doc.scala, project/Formatting.scala, project/Github.scala, project/MiMa.scala, project/MultiNode.scala, project/ParadoxSupport.scala, project/Publish.scala, project/SbtInternalAccess.scala, project/ValidatePullRequest.scala, project/VersionGenerator.scala, project/Whitesource.scala
Found some stragglers after #2377
=> Update copyright headers to 2019

project/ValidatePullRequest.scala
See https://github.com/akka/akka/pull/25264 for the PR that breaks this build.
Fixes #2387.
=> =pro adopt to recent changes in akka buld to fix builds against akka master source, fixes #2387

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
=> Include path in early response warning

docs/src/main/paradox/routing-dsl/directives/future-directives/onSuccess.md
=> Improve `onSuccess` docs to explain Tupler magic #993

docs/src/main/paradox/extensions.md
=> Add links endorsing support projects #1968

akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpRequestRendererFactory.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala
=> Allow raw header User-Agent #2277

akka-http/src/main/scala/akka/http/scaladsl/server/Directive.scala
Just stumbled this (probably my) mistake from way back.
It appears to be the only occasion in the code base.
Trivial fix but unfortunately not fully binary compatible (or is it? Maybe at least "sufficiently compatible"?).
=> =htp Turn `Directive.SingleValueModifiers` into a value class

akka-http-core/src/test/scala/akka/stream/testkit/Utils.scala
To stay compatible with akka master.
=> =htc move to akka-stream-testkit version of assertAllStagesStopped, #2421

docs/src/main/paradox/routing-dsl/testkit.md
=> Add note about akka-stream-teskit is a provided dep #2428

akka-http-core/src/test/java/akka/http/javadsl/model/EntityDiscardingTest.java, akka-http-core/src/test/java/akka/http/javadsl/model/UriTest.java, akka-http-core/src/test/java/akka/http/javadsl/model/sse/ServerSentEventTest.java, akka-http-core/src/test/java/akka/http/javadsl/settings/ClientConnectionSettingsTest.java, akka-http-core/src/test/java/akka/http/javadsl/settings/ConnectionPoolSettingsTest.java, akka-http-core/src/test/java/akka/http/javadsl/settings/ParserSettingsTest.java, akka-http-core/src/test/java/akka/http/javadsl/settings/ServerSettingsTest.java, akka-http-tests/src/test/java/akka/http/javadsl/settings/RoutingSettingsTest.java, akka-http-tests/src/test/java/akka/http/javadsl/unmarshalling/sse/EventStreamUnmarshallingTest.java, docs/src/test/java/docs/http/javadsl/server/HttpAppExampleTest.java, docs/src/test/java/docs/http/javadsl/server/HttpsServerExampleTest.java, project/Dependencies.scala
see https://github.com/akka/akka/pull/26387;
this is similar
=> adapt to ScalaTest changes

akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpRequestRendererFactory.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala
=> Allow RawHeader Host

akka-http-core/src/main/java/akka/http/javadsl/model/MediaTypes.java, akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala
Tiny addition of a new predefined `MediaType` that is used increasingly often.
=> +htc Add `application/cbor` as predefined MediaType

akka-parsing/src/main/scala/akka/parboiled2/CharUtils.scala
And fix broken (and unused) CharUtils.toUpperCase.
=> Speedup CharUtils.toLowerCase

akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-core/src/test/scala/akka/http/impl/util/StreamUtilsSpec.scala
=> Fix int overflow in sliceBytesTransformer (#2440)

docs/src/main/paradox/configuration.md
And add a link from Configuration to Introduction
=> Link from 'configuration' to 'introduction'

build.sbt, project/plugins.sbt
* Add canonical URL
* Add description tag
* Use Paradox 0.5.3 via Akka theme 0.17
=> Latest Paradox template; add canonical URL and description

project/Doc.scala
Make Scaladoc generate a page title and include the version.
References https://github.com/akka/akka/pull/26632
Improve site quality for akka.io
=> Scaladoc: title and version

docs/src/main/paradox/routing-dsl/directives/security-directives/authenticateOAuth2.md
Documentation Amendment
Updated description for authenticateOAuth2 security directive
=> Documentation Amendment: Updated description for authenticateOAuth2 security directive

akka-http-tests/src/test/java/akka/http/javadsl/marshalling/sse/EventStreamMarshallingTest.java, docs/src/test/java/docs/http/javadsl/CustomMediaTypesExampleTest.java, docs/src/test/java/docs/http/javadsl/HttpClientExampleDocTest.java
=> Use ByteString.emptyByteString

akka-http/src/main/scala/akka/http/javadsl/marshalling/Marshaller.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteDirectives.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/SecurityDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/Rejection.scala
Found some TODOs
optimize few java to scala conversions
=> Optimize few java to scala conversions

project/Dependencies.scala, project/MiMa.scala
(might interfere with playframework nightlies, let's check before merging)
=> Update to Scala 2.13.0-RC3

project/Dependencies.scala, project/MiMa.scala
=> Update Scala to 2.13.0

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Protocol.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ProtocolSwitch.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/ProtocolSwitchSpec.scala
https://github.com/akka/akka-http/pull/2543#discussion_r287314992
https://github.com/akka/akka-http/pull/2543#discussion_r290989734
=> Add some Prior Knowledge switch tests

project/plugins.sbt
Update sbt-scalariform to 1.8.3, removing a workaround.
Follow-up from #2534
=> Update sbt-scalariform to 1.8.3

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileUploadDirectives.scala
=> Support 'streaming back' an uploaded file

docs/src/main/paradox/release-notes/10.1.x.md
Found by @ennru
References #xxxx
=> Fix slight formatting error in the release notes

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala
Making it compile with Scala 2.11 again
=> Remove trailing comma from FileUploadDirectivesSpec

docs/src/main/paradox/implications-of-streaming-http-entity.md, docs/src/test/java/docs/http/javadsl/HttpClientExampleDocTest.java, docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala
=> Add example showing consuming a stream of requests

akka-http-compatibility-tests/README.md, akka-http-compatibility-tests/src/main/scala/akka/http/scaladsl/server/directives/CompatFormField.scala, akka-http-compatibility-tests/src/test/scala/akka/http/scaladsl/server/directives/CompatFormFieldSpec.scala, build.sbt
It allows to write code in src/main against the previous version and run tests
in src/test with the new source code version on the classpath.
=> +pro add compatibility test module

project/Doc.scala
Containing some fixes to the javadoc generation
=> Update genjavadoc to 0.13

notes/release-train-issue-template.md
Update the links to the Lightbend Platform documentation.
=> Release train updates

build.sbt, docs/src/main/paradox/client-side/host-level.md, docs/src/main/paradox/routing-dsl/HttpApp.md, docs/src/main/paradox/routing-dsl/directives/basic-directives/extractActorSystem.md, docs/src/main/paradox/routing-dsl/index.md, docs/src/test/scala/docs/http/scaladsl/HttpServerWithTyped.scala, docs/src/test/scala/docs/http/scaladsl/HttpServerWithTypedSpec.scala
This PR adds examples on how Akka HTTP and Akka Typed interact with each other.
References #2584
Only the Scala example is there at the moment. Java one is missing.
There will be some build problems I suppose
=> [WIP] Akka typed examples

build.sbt, docs/src/main/paradox/routing-dsl/index.md, docs/src/test/scala-2.12+/docs/http/scaladsl/HttpServerWithTypedSpec.scala, project/AkkaDependency.scala
=> docs: fix typed example not to fail against Akka 2.6 and/or Scala 2.11

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
https://www.lightbend.com/conduct
=> Update to Lightbend Community Code of Conduct

project/AkkaDependency.scala, project/Dependencies.scala, project/plugins.sbt
=> Bump up dependencies.

docs/src/main/paradox/release-notes/10.0.x.md
#2710
It's not available in scaladoc since it's not public
=> Link to StreamPrioritizer javadoc

docs/src/main/paradox/migration-guide/migration-from-old-http-javadsl.md, docs/src/main/paradox/server-side/server-https-support.md
#2710
@apidoc[Http] does not exist for scala
=> Avoid hidden-but-invalid links

docs/src/main/paradox/common/http-model.md, docs/src/main/paradox/routing-dsl/directives/security-directives/authorize.md
=> Fix links to objects

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/WithPriorKnowledgeSpec.scala
=> Allow sending an ack SETTINGS frame immediately

docs/src/main/paradox/introduction.md, project/plugins.sbt, project/project-info.conf
=> Upgrade akka paradox + project info

docs/src/main/paradox/introduction.md, notes/release-train-issue-template.md
Reopened #2772 by @vitojeng. Still a good idea, since we renamed these projects a long while ago.
=> docs: fix broken links for bootstrap a new sbt project

docs/src/main/paradox/routing-dsl/path-matchers.md, docs/src/test/java/docs/http/javadsl/server/directives/PathDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/PathDirectivesExamplesSpec.scala
=> Slight improvements to the pathmatcher docs

akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
The logs had this exception:
```
| [DEBUG] [11/04/2019 02:23:20.569] [AkkaSpecWithMaterializer-akka.actor.default-dispatcher-24] [akka://AkkaSpecWithMaterializer/system/Materializers/StreamSupervisor-101/flow-75-0-mapAsyncUnordered] Aborting tcp connection to /127.0.0.1:57810 because of upstream failure: java.lang.NullPointerException
| akka.http.impl.engine.client.ConnectionPoolSpec$$anon$10.mapServerSideOutboundRawBytes(ConnectionPoolSpec.scala:292)
| akka.http.impl.engine.client.ConnectionPoolSpec$TestSetup$$anonfun$7.applyOrElse(ConnectionPoolSpec.scala:644)
| akka.http.impl.engine.client.ConnectionPoolSpec$TestSetup$$anonfun$7.applyOrElse(ConnectionPoolSpec.scala:644)
```
which is likely caused by the counter not yet being initialized yet when
the first request hits the handler for …
=> core: fix race condition in ConnectionPoolSpec, fixes #2796

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, docs/src/test/scala/docs/http/scaladsl/Http2Spec.scala
fixes #2791
fixes #2791
Did the changes as described #2791
=> Fix HTTP/1.1 ALPN negotiation #2791

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpEntitySpec.scala
=> htc: clear some warnings

build.sbt
=> Allow deployRsync for publishing snapshot docs

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/ResponseParsingMergeSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
=> core: improve "Entity stream truncation" error message

akka-http-tests/src/test/java/akka/http/javadsl/server/directives/RouteDirectivesTest.java, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MiscDirectivesSpec.scala
Fixes #2827 by reflecting the change in #2823
=> Fix test expectations

project/ValidatePullRequest.scala
Fixes #2831. Spent a while on that, I forgot that I had to make the same change in sbt-dependency-graph before.
=> Fix PR validation dependency check

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala
Failure is normal.
Fixes https://github.com/akka/akka-http/issues/2830
=> Tone down the connection failure warning

RELEASING.md, scripts/release-train-issue-template.md
Some tweaks to the release procedure
=> Update release script

docs/src/main/paradox/common/marshalling.md
=> Small typo in docs/src/main/paradox/common/marshalling.md

build.sbt, project/Dependencies.scala
We can split them up again if we ever want to let them diverge again
=> Use one Jackson version field

.scala-steward.conf
see https://github.com/akka/akka/issues/26985
=> Don't automatically update Akka

build.sbt, project/MiMa.scala
=> build: always use latest for compatibility tests

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala
Not entirely sure this is the right place to do it but couldn't figure out where else it would go.
=> Add the remote address in parse errors when possible

akka-http-marshallers-java/akka-http-jackson/src/main/java/akka/http/javadsl/marshallers/jackson/Jackson.java, akka-http-marshallers-java/akka-http-jackson/src/test/java/akka/http/javadsl/marshallers/jackson/JacksonTest.java, project/Dependencies.scala
=> jackson: better JSON validation error when unmarshalling

akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala
Will be silenced by WithLogCapturing
Refs #2919
=> core: log more by default in MessageSpec

akka-http-core/src/test/scala/akka/http/scaladsl/model/EntityDiscardingSpec.scala
The error message got more details in 2.6
=> core: fix EntityDiscardingSpec expected error message, fixes #2929

docs/src/test/scala/docs/http/scaladsl/HttpServerWithTypedSample.scala
=> docs: fix HttpServerWithTypedSample compilation against 2.6

akka-http-core/src/test/scala/akka/http/scaladsl/TightRequestTimeoutSpec.scala
=> core: remove temporaryServerHostnameAndPort in TightRequestTimeoutSpec

akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/HttpAppSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/RoutingSpec.scala, docs/src/test/resources/application.conf
Turns out those have been pure testing issues
=> Fix tests failing against akka master / 2.6

akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
=> core: prevent initialization NPE which might fail all retries quickly

akka-http-bench-jmh/src/main/scala/akka/http/impl/model/parser/UriParserBenchmark.scala, akka-http-bench-jmh/src/main/scala/akka/http/scaladsl/unmarshalling/sse/LineParserBenchmark.scala
Initial work for https://github.com/akka/akka-http/issues/2854
=> bench: add UriParser benchmarks

akka-http-caching/src/test/scala/akka/http/caching/ExpiringLfuCacheSpec.scala
Fixes #2950
The rational here is that it only fails on the additional Jenkins nodes I spwan sometimes. On my main `johannes` node the test usually runs for ~0.2 seconds, but on the other nodes it usually runs for ~0.9 seconds. Maybe those nodes are more noisy so it go also go to > 5 seconds? Doesn't seem like a super good explanation, but since I might have to sunset the `johannes` node sooner or later, let's try to figure it out.
=> cache: try to harding ExpiringLfuCacheSpec

project/Common.scala, project/project-info.conf
Make sure the project info gets hold of the correct version number.
Fixes https://github.com/lightbend/sbt-paradox-project-info/issues/15
=> Docs: set the correct version for project info

akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
Previously we introduced a synthetic delay for reporting failures so it would
trigger the cancellation race condition more reliably. However, with the
default 5 retries that pushed the final failure of the request over the 1
second mark that ensureConnectionIsClosed expects.
=> core: fix GracefulTerminationSpec, fixes #2991

akka-http-core/src/test/scala/akka/http/impl/engine/client/ClientCancellationSpec.scala
=> Avoid 'address already in use' in ClientCancellationSpec

akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
release-10.1 backport of #2993
Previously we introduced a synthetic delay for reporting failures so it would
trigger the cancellation race condition more reliably. However, with the
default 5 retries that pushed the final failure of the request over the 1
second mark that ensureConnectionIsClosed expects.
(cherry picked from commit 9f99363ab304400f639032787c9d353aa693faff)
=> [backport] core: fix GracefulTerminationSpec, refs #2991

akka-http-core/src/test/scala/akka/http/scaladsl/model/MultipartSpec.scala
Might help to diagnose #3015 later.
=> core: enable WithLogCapturing for MultipartSpec

akka-http-core/src/test/scala/akka/http/scaladsl/model/MultipartSpec.scala
Might help to diagnose #3015 later.
(cherry picked from commit 715996acb04b9219ebd5a913228e238a9cb578b5)
=> [backport] core: enable WithLogCapturing for MultipartSpec

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala
That seems excessive even at debug level
=> Reduce http2 buffer debug logging

build.sbt, docs/src/main/paradox/routing-dsl/routes.md, project/AkkaDependency.scala
=> docs: link to major/minor Akka docs

project/Whitesource.scala, project/plugins.sbt
=> Avoid jgit, replace with git commandline invocation

build.sbt, project/AkkaDependency.scala
=> build: test against published snapshots instead of source deps

project/AkkaDependency.scala
Even if the sbt flag asks for it
Refs https://github.com/akka/akka-http/pull/3055#issuecomment-614033698
=> Don't build the docs with Akka 2.5

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
=> Make `transparent-head-requests` opt-in

akka-http-caching/src/test/scala/akka/http/scaladsl/server/directives/CachingDirectivesSpec.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala, akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/Specs2RouteTestSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FutureDirectivesSpec.scala, akka-http/src/main/scala/akka/http/javadsl/server/Route.scala, docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
=> Simplify implicits for RouteTest

build.sbt, docs/src/main/paradox/routing-dsl/index.md, docs/src/test/scala/docs/http/scaladsl/HttpServerWithActorsSample.scala, docs/src/test/scala/docs/http/scaladsl/HttpServerWithTypedSample.scala
=> docs: update to make HttpServerWithTypedSample more 2.6-style

akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/3022-fix-server-side-cancellation-races.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerWithExplicitSchedulerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
So far we have only fixed the client-side cancellation race. This will be a fix for the server-side.
So far, I have reproduced the problem as described in #2116 which is suspected to be due to the race condition.
=> Fix server-side cancellation race

akka-http/src/main/scala/akka/http/javadsl/server/directives/MiscDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/MiscDirectives.scala, docs/src/main/paradox/routing-dsl/directives/misc-directives/extractClientIP.md
=> Update extractClientIP.md to adapt `akka.http.server.remote-address-attribute`

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/package.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
Seems to be a byte->char conversion problem. Since someone finally provided a reproducible test case, I had a quick look. Still needs proper tests.
Refs #1484
=> Fix HeaderParser Unicode issue

.scala-steward.conf
=> build: bundle scala steward dependencies updates to once a week

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala, docs/src/main/paradox/implications-of-streaming-http-entity.md
References #3050 
I am not sure what needs to be done for a PR in this project, I did a simple `grep -nrw "Response entity"` adjusted the corresponding places and run `sbt test` afterwards. Let me know if there are things which need to be done in addition
=> #3050 improve error message about unconsumed entity

akka-http/src/main/mima-filters/10.1.x.backwards.excludes/remove-deprecated-formfielddirectives-methods.backwards.excludes, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala
=> Remove deprecated FormFieldDirectives methods

akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/remove-deprecated-methods-taking-implicit-materializers.backwards.excludes, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
=> Remove deprecated methods taking implicit materializers

akka-http/src/main/scala/akka/http/javadsl/server/Route.scala, docs/src/main/paradox/introduction.md, docs/src/main/paradox/routing-dsl/index.md, docs/src/test/java/docs/http/javadsl/HttpServerWithActorsSample.java, docs/src/test/java/docs/http/javadsl/JobRepository.java, docs/src/test/java/docs/http/javadsl/JobRoutes.java, docs/src/test/scala/docs/http/scaladsl/HttpServerWithActorsSample.scala
References #2664
Not tested yet, and not formatted - ~I didn't realize we don't have sbt-java-formatter configured here. Should we?~ (we shouldn't, #3080)
=> Actor interop Java example

akka-http-core/src/main/scala/akka/http/scaladsl/model/ws/Message.scala, akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala, akka-http-core/src/test/scala/akka/testkit/AkkaSpec.scala, akka-http-core/src/test/scala/akka/testkit/Coroner.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/TestFrameworkInterface.scala, akka-parsing/src/main/scala/akka/shapeless/hlists.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/HeaderDirectivesExamplesSpec.scala
Fixes compilation error https://github.com/akka/akka-http/issues/3129
=> Fix more Scala 2.13 warnings

akka-http/src/main/scala/akka/http/scaladsl/server/Route.scala, docs/src/test/scala/docs/http/scaladsl/Http2Spec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/JsonStreamingFullExamples.scala
=> Provide Route.toFunction as alternative to Route.asyncHandler

docs/src/main/paradox/routing-dsl/index.md, docs/src/main/paradox/routing-dsl/style-guide.md, docs/src/test/java/docs/http/javadsl/server/directives/StyleGuideExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/StyleGuideExamplesSpec.scala
Add some guidance how we recommend users organise their routing DSL code.
References #2980
=> Routing DSL: style guide

akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/3158-allow-multiple-host-headers.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpResponseParser.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala
=> Core: Allow multiple Host headers in responses

akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Fixes #3159.
Otherwise, the test will fail with assertAllStagesStopped in JDK 11.
In JDK 11 the SSLEngine seems to show a different closing behavior which
leads to the TLS stage being kept open until the idle timeout closes
the connection.
=> core: decrease idle timeout in ClientServerSpec

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MiscDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/MiscDirectives.scala, docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md, docs/src/main/paradox/routing-dsl/directives/misc-directives/extractClientIP.md
Update documentation and migration notes accordingly.
Refs #2924
=> Make X-Real-Ip take precedence over Remote-Address

akka-http-tests/src/test/scala/akka/http/scaladsl/server/EntityStreamingSpec.scala, akka-http/src/main/mima-filters/10.1.x.backwards.excludes/remove-EntityStreaming-method.excludes, akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToResponseMarshallers.scala
=> http: remove deprecated entity streaming marshaller

akka-http-core/src/main/scala/akka/http/impl/settings/ClientConnectionSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala, akka-http-core/src/test/scala/akka/http/scaladsl/settings/ClientConnectionSettingsSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/settings/ServerSettingsSpec.scala
=> Fail early when creating client settings with incomplete parser settings

akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/MultipartUnmarshallersSpec.scala
Will help diagnose failures like #3203
=> tests: Use AkkaSpecWithMaterializer in MultipartUnmarshallerSpec

.travis.yml, akka-http-core/src/test/scala/akka/http/impl/util/AkkaSpecWithMaterializer.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTestTimeout.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToEntityMarshallers.scala, project/Dependencies.scala, project/Doc.scala
And latest genjavadoc to support those.
=> build: update to Scala 2.13.2 / 2.12.11

akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, docs/src/main/paradox/client-side/client-https-support.md, docs/src/test/java/docs/http/javadsl/HttpsExamplesDocTest.java, docs/src/test/scala/docs/http/scaladsl/HttpsExamplesSpec.scala
=> docs: don't claim that SNI is a security feature

akka-http-core/src/main/java/akka/http/javadsl/model/FormData.java, akka-http-core/src/main/scala/akka/http/javadsl/settings/ParserSettings.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala
Add some more deprecation notices or make existing ones more explicit.
=> Deprecations for 10.2.0

.scala-steward.conf
=> build: stay on ScalaTest 3.1.x

docs/src/main/paradox/introduction.md, docs/src/test/java/docs/http/javadsl/ClientSingleRequestExample.java, docs/src/test/java/docs/http/javadsl/HttpServerActorInteractionExample.java, docs/src/test/java/docs/http/javadsl/HttpServerLowLevelExample.java, docs/src/test/java/docs/http/javadsl/HttpServerMinimalExampleTest.java, docs/src/test/java/docs/http/javadsl/HttpServerStreamRandomNumbersTest.java, docs/src/test/java/docs/http/javadsl/JacksonExampleTest.java, docs/src/test/scala/docs/http/scaladsl/HttpClientSingleRequest.scala, docs/src/test/scala/docs/http/scaladsl/HttpServerLowLevel.scala, docs/src/test/scala/docs/http/scaladsl/HttpServerRoutingMinimal.scala, docs/src/test/scala/docs/http/scaladsl/HttpServerStreamingRandomNumbers.scala, docs/src/test/scala/docs/http/scaladsl/HttpServerWithActorInteraction.scala, docs/src/test/scala/docs/http/scaladsl/SprayJsonExample2.scala
More to https://github.com/akka/akka-http/issues/3073
Requires merge of https://github.com/akka/akka-http/pull/3223
Discovered https://github.com/akka/akka-http/issues/3240 and https://github.com/akka/akka-http/issues/3241
=> Docs: use new ActorSystem API

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala
Seems like an incorrect debugging leftover anyway
=> Remove 'adapted' println

akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketIntegrationSpec.scala
=> Add test for failure propagation into websocket flows

akka-http-tests/src/test/scala/akka/http/scaladsl/server/ModeledCustomHeaderSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CacheConditionDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/HeaderDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/HeaderDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/SecurityDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/WebSocketDirectives.scala, docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md, docs/src/test/scala/docs/http/scaladsl/server/directives/HeaderDirectivesExamplesSpec.scala
=> Allow passing a companion object to headerValueByType

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala, akka-http/src/main/boilerplate/akka/http/scaladsl/server/directives/FormFieldDirectivesInstances.scala.template, akka-http/src/main/mima-filters/10.1.x.backwards.excludes/formFields-via-FieldSpec.excludes, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala, docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
=> http: remove magnets usage from formField directives

build.sbt, project/Publish.scala, project/plugins.sbt, scripts/release-train-issue-template.md
=> build: Use publishRsync plugin

akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/PathDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/TimeoutDirectivesExamplesSpec.scala, project/Dependencies.scala
=> build: update to Scala 2.13.3

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CodingDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ExecutionDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FutureDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/RouteDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/RangeDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/RouteDirectives.scala, docs/src/main/paradox/migration-guide/migration-from-spray.md, docs/src/test/scala/docs/http/scaladsl/HttpServerWithActorInteraction.scala, docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/ExecutionDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/FutureDirectivesExamplesSpec.scala
=> http: allow 'complete' directive with status without adapted arguments

project/plugins.sbt
=> build: pull up sbt-assembly dependency to stay compatible with akka master

akka-http-core/src/main/resources/reference.conf, docs/src/main/paradox/client-side/configuration.md, docs/src/main/paradox/client-side/index.md, docs/src/main/paradox/release-notes/10.2.x.md
=> docs: page about client-side configuration + per-host-overrides

akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/RangeDirectives.scala
=> Fix remaining internal adapted arguments warnings

CONTRIBUTING.md, build.sbt, project/Doc.scala, project/Github.scala
* remove unused Paradox settings
* fix snapshot links to Github sources
* remove Scaladoc 2.11 cruft
=> build: cleanup in docs config

build.sbt, docs/src/test/scala/docs/http/scaladsl/server/directives/FutureDirectivesExamplesSpec.scala
=> docs: disallow auto-tupling

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
=> core: make sure to reset all UriParser fields before reusing

akka-http-core/src/main/java/akka/http/javadsl/model/HttpEntity.java, akka-http-core/src/main/java/akka/http/javadsl/model/HttpMessage.java, akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/3361-more-ClassicActorSystemProvider-discard.excludes, akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/3361-more-ClassicActorSystemProvider-toStrict.excludes, akka-http-core/src/main/scala/akka/http/javadsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala, akka-http-core/src/test/java/akka/http/javadsl/model/EntityDiscardingTest.java, akka-http-marshallers-java/akka-http-jackson/src/test/java/akka/http/javadsl/marshallers/jackson/JacksonTest.java, akka-http-tests/src/test/java/akka/http/javadsl/server/UnmarshallerTest.java, akka-http-tests/src/test/java/akka/http/javadsl/unmarshalling/sse/EventStreamUnmarshallingTest.java, akka-http/src/main/scala/akka/http/javadsl/unmarshalling/Unmarshaller.scala, docs/src/test/java/docs/http/javadsl/ClientSingleRequestExample.java, docs/src/test/java/docs/http/javadsl/CustomMediaTypesExampleTest.java, docs/src/test/java/docs/http/javadsl/HttpClientDecodingExampleTest.java, docs/src/test/java/docs/http/javadsl/HttpClientExampleDocTest.java, docs/src/test/java/docs/http/javadsl/HttpServerLowLevelExample.java, docs/src/test/java/docs/http/javadsl/JacksonXmlExampleTest.java, docs/src/test/java/docs/http/javadsl/UnmarshalTest.java, docs/src/test/java/docs/http/javadsl/server/HttpServerExampleDocTest.java, docs/src/test/java/docs/http/javadsl/server/JsonStreamingExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/CustomHttpMethodExamplesTest.java
=> Accept classic provider in more places

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala, akka-http2-support/src/test/scala/akka/http/scaladsl/Http2BindingViaConfigSpec.scala
=> tests: enable more logging in Http2ClientServerSpec

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerProcessingBenchmark.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, build.sbt
Very simplistic so far, but this way at least we have some baseline
=> Http2 benchmarks

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/StreamServerProcessingBenchmark.scala
Also the numbers are now more comparable as the overall number of bytes per run is always the same.
The existing graph for `ServerProcessingBenchmark2` have become quite unreadable because of the number of configs, so this will help a bit hopefully.
=> bench: rename ServerProcessingBenchmark2 and reduce number of configurations

akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
=> core: reverse call propagation for deprecated bind vs. bindImpl methods

akka-http-core/src/main/scala/akka/http/impl/engine/ws/Handshake.scala
This is my most important contribution this month. Please review it with the attention it deserves.
=> core: let's cite all the spec (for WebSocket upgrades)

build.sbt, project/AkkaDependency.scala
=> build: backport AkkaDependency changes from master

docs/src/main/paradox/common/encoding.md, docs/src/main/paradox/configuration.md, docs/src/main/paradox/introduction.md, docs/src/main/paradox/release-notes/10.2.x.md, docs/src/main/paradox/routing-dsl/index.md, docs/src/main/paradox/server-side/index.md, docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/SprayJsonExample.scala, project/AkkaDependency.scala
A first small set of documentation improvements for 10.2
=> docs: overall improvements for 10.2

project/ValidatePullRequest.scala
Currently on top of 4ce9afb which is known to fail with output in that segment.
=> build: quote more parts in PR validation report

akka-http-core/src/main/scala/akka/http/javadsl/ServerBuilder.scala, akka-http-core/src/main/scala/akka/http/scaladsl/ServerBuilder.scala
For completeness and to be able to provide a complete scalafix set in #3407 that doesn't generate illegal code.
=> core: allow customization of materializer with new ServerBuider API

docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md, docs/src/main/paradox/release-notes/10.2.x.md
Gladly not much to add here over 10.2.0-RC2, most work already done.
=> 10.2.0 release notes improvements

akka-http-core/src/main/resources/reference.conf
=> Spelling in reference.conf

build.sbt
=> build: increase paradox parsing timeout

akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileUploadDirectives.scala
=> http: fail storeUploadedFile(s) directive when IO operation fails

akka-http-core/src/main/scala/akka/http/impl/engine/ws/Handshake.scala
Really trivial change removing an unused import
=> Remove unused import in Handshake class

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
Fixes #1495
It seems without this fix responses to HEAD requests will have to discard
the entities manually or the entity subscription timeout will kick in.
This is more of a hack but it might work well enough for now.
=> core: make entities of HEAD requests discard

akka-http-core/src/main/scala/akka/http/impl/engine/ws/FrameOutHandler.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala
Also converted to more idiomatic Deadline.
Fixes #75
=> core: add debug logging when Websocket impl closes connections after timeout

docs/src/main/paradox/routing-dsl/directives/method-directives/head.md
References #2088
Hello, this is my first PR on akka-http project.
I tried to follow the process to make the PR.
Thank you.
=> chore(doc): update head documentation about default behavior

.jvmopts-travis
=> Enable gc logging when generating docs

docs/src/main/paradox/server-side/server-https-support.md, docs/src/test/java/docs/http/javadsl/server/HttpsServerExampleTest.java, docs/src/test/scala/docs/http/scaladsl/server/HttpsServerExampleSpec.scala
=> Document requiring client authentication

build.sbt, docs/src/main/paradox/routing-dsl/testkit.md, docs/src/test/java/docs/http/javadsl/server/testkit/MyAppWithActor.java, docs/src/test/java/docs/http/javadsl/server/testkit/TestKitWithActorTest.java, docs/src/test/scala/docs/http/scaladsl/server/TestKitWithActorSpec.scala
At least documenting the current state of #2036,
(while we might improve the API further in the future)
=> Add examples of testing actor interactions

akka-http-tests/src/test/scala/akka/http/scaladsl/server/EntityStreamingSpec.scala
=> tests: widen EntityStreamingSpec patience

akka-http-tests/src/test/scala/akka/http/scaladsl/server/EntityStreamingSpec.scala
=> [backport] tests: widen EntityStreamingSpec patience

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
For cheaper macro-based debug logging.
=> http2: use LogHelper in demux classes

akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/TestFrameworkInterface.scala, akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/ScalatestRouteTestSpec.scala, akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/Specs2RouteTestSpec.scala
References #3400 
Covering both ScalaTest and Specs2
=> Fall through on AssertionErrors in testkit (#3400)

.scala-steward.conf
=> Correctly exclude akka-actor-testkit-typed

akka-http-core/src/main/resources/reference.conf
=> docs: typo fix: "the onne" --> "the one"

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/client/RequestRendering.scala
=> Remove some minor repetition in HTTP/2 rendering 

docs/src/main/paradox/introduction.md
Adding akka-actor-typed dependency for introduction.md in documentation #3528
=> docs: add akka-actor-typed dependency to introduction.md

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerProcessingBenchmark.scala
The nightly bench run was stuck because of this issue: https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-bench-nightly/219/
=> bench: avoid getting stuck in H2ServerProcessingBenchmark

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
This is only a preview of how it might look like, this is a version that mostly works and passes all tests (but still has some known bugs).
I've got a few FIXMEs, I'd like to work continue on.
Not for review, yet.
=> HTTP/2 unified stream incoming / outgoing stream handling

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ClientConnectionSettings.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala
References #3185 (https://github.com/akka/akka-http/pull/3540#pullrequestreview-511554303)
Built on top of #3522
=> http2: disable Push (send SETTING)

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala
=> http2: fix Scala 2.12 compilation error

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
=> http2: remove explicit parallelism parameter in Http2

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Protocol.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> Respect remote max concurrent streams (reprise)

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Probably conflicts with a number of in-flight PR's, I'm happy to resolve
conflicts here.
=> Helper to expect a parsed frame of a given type

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Soem cleanup after merging #3581 and a few other competing PRs
=> tests: cleanup

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> Use assertAllStagesStopped in Http2ServerSpec and fix two edge case stream leaks

akka-http/src/main/scala/akka/http/scaladsl/server/directives/HeaderDirectives.scala
Related PR: https://github.com/akka/akka-http/pull/3591
Please refer to the above PR description for more details
=> http: optimize header directives by avoiding HttpHeader.unapply

docs/src/main/paradox/client-side/request-level.md, docs/src/main/paradox/implications-of-streaming-http-entity.md
=> Some docs gardening

akka-http-core/src/main/scala/akka/http/scaladsl/model/TransferEncoding.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala
https://tools.ietf.org/html/rfc7230#section-4.3
=> Add modeled 'TE' header

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
Since those may come in asynchronously
=> Continue accepting window updates even when done sending

akka-http-core/src/main/java/akka/http/javadsl/model/TransferEncodings.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/TE.java, akka-http-core/src/main/scala/akka/http/impl/model/parser/CommonRules.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/HeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/SimpleHeaders.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
And add tests. Follow-up to #3616
=> Actually register modeled TE header in header parsing infra

akka-http-core/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> Support custom HTTP methods for HTTP/2 

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> Fix build against akka master

docs/src/main/paradox/release-notes/10.1.x.md
(cherry picked from commit 9df1dd5205b657c5367e53e0030c92c30e6eda1b)
=> backport 10.1.13 release notes to master

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
The previous `handle.getClass` was useless because it returned opaque lambda class names.
=> http2: more useful event info for stream state changes

akka-http-core/src/test/scala/akka/http/impl/engine/ws/ByteStringSinkProbe.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/HPackSpecExamples.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/WindowTracking.scala
Part of #3227 but does not close it.
=> Add some more basic Http2 client tests

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
2 PR's crossed each other it seems
=> Fix compiler errors on master

akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/HttpCookie.scala
=> HttpCookie.copy was calling itself recursively

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
like we already do for server tests
=> http2: check all stages are stopped in client tests

project/build.properties
Reverts akka/akka-http#3649
Since it breaks compilation see https://github.com/sbt/sbt/issues/6197.
=> Revert "build: update sbt from 1.3.13 to 1.4.4"

akka-http-core/src/main/scala/akka/http/scaladsl/model/Uri.scala
=> Add scaladoc for path.?/

LICENSE
=> 2020 -> 2021

.scala-steward.conf
Since that's blocked by https://github.com/sbt/sbt/issues/6197
=> Don't update to sbt 1.4 automatically

akka-http-core/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala
=> Include remote address attribute in HTTP/2 requests

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerProcessingBenchmark.scala, akka-http-core/src/main/mima-filters/10.2.2.backwards.excludes/telemetry-spi.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/TelemetrySpi.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/RequestResponseAssociation.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/TelemetrySpiSpec.scala
=> Telemetry SPI for the HTTP/2 client

akka-http-core/src/main/mima-filters/10.2.2.backwards.excludes/persistent-connection.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/http2/OutgoingConnectionBuilderImpl.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/PersistentConnection.scala, akka-http-core/src/main/scala/akka/http/javadsl/OutgoingConnectionBuilder.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/OutgoingConnectionBuilder.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala, docs/src/main/paradox/compatibility-guidelines.md
On top of #3685 (would perhaps be better to push directly to that PR but separate for now)
=> WIP Reconnecting http2 client PR followup

akka-http-core/src/main/mima-filters/10.2.2.backwards.excludes/h2-client-persistent-connection-max-attempts.backwards.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/http2/OutgoingConnectionBuilderImpl.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/PersistentConnection.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/Http2ClientSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala
=> [h2 client] persistent connection max attempts

scripts/release-train-issue-template.md
References https://github.com/akka/akka-grpc/pull/1263
=> Adds step to push changes to GH

docs/src/main/paradox/release-notes/10.1.x.md, docs/src/main/paradox/security.md, docs/src/main/paradox/security/2021-02-24-incorrect-handling-of-Transfer-Encoding-header.md, docs/src/main/paradox/security/2021.md
=> Release note for 10.1.14

project/MiMa.scala
=> build: post 10.1.14 changes

project/Dependencies.scala, project/plugins.sbt
Also update silencer to compatible version.
=> build: update to Scala 2.13.5, 2.12.13 and scalafix 0.9.26

akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, project/build.properties
Also fix an implicit issue which non-deterministically turned up now and then probably because sometimes implicit resolution depends on definition order (which in turn can depend on the order that
sbt or the file system enumerate files, separate compilation etc.)
=> Update to sbt 1.4.7

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
=> [backport] core: don't send '100 Continue' if 'Content-Length' header is 0, doesn't exist or data got send early

.travis.yml, build.sbt, project/Formatting.scala, project/Publish.scala, project/plugins.sbt, scripts/release-train-issue-template.md
That seems to work for snapshots as well.
=> build: publish to sonatype directly

docs/src/main/paradox/contributing.md
See #3792
Page is outdated: https://doc.akka.io/docs/akka-http/current/contributing.html
=> Remove bintray leftovers / Fix snapshot version badge

akka-http-core/src/main/scala/akka/http/scaladsl/model/Trailer.scala
Follow-up on #3820 (https://github.com/akka/akka-http/pull/3820#discussion_r642502122)
=> Append new trailing headers at the end

akka-http-core/src/main/scala/akka/http/impl/engine/http2/framing/FrameRenderer.scala
A quick rewrite of the FrameRenderer to use preallocated arrays of exactly the right size. Split out of #3822.
=> http2: avoid extra allocations in frame renderer

akka-http-core/src/main/scala/akka/http/impl/engine/server/ServerTerminator.scala, akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
=> Preserve original response headers during server termination #3818

.travis.yml
=> Clarify we're publishing to sonatype, not bintray

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/Marshaller.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=>  http2: provide missing handling logic in CollectingIncomingData state + tests

NOTICE.txt, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/Decoder.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/DynamicTable.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/Encoder.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/HeaderField.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/HeaderListener.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/HpackUtil.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/Huffman.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/HuffmanDecoder.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/HuffmanEncoder.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/StaticTable.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/package-info.java, akka-http-core/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderDecompression.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameHpackSupport.scala, license/LICENSE.hpack.txt, project/Dependencies.scala
Imported from latest version at https://github.com/twitter/hpack/commit/713612a439aa8f9b22cf4840054f9e7b3a787c02
This is in preparation of some important optimization wrt header parsing.
=> http2: import shaded twitter hpack library (APL2)

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
=> http2: convert stream handling map to LongMap

akka-http-core/src/main/mima-filters/10.2.4.backwards.excludes/3741-http2-persistent-connection-backoff.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/http2/OutgoingConnectionBuilderImpl.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/PersistentConnection.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/Http2ClientSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala
References #3741
Pretty much copied the backoff logic from the NewConnectionPool as is.
=> http2: back off on client persistent connection failure

akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/RenderSupport.scala
Growing these buffers dynamically turned up during profiling a while ago.
=> core: increase some default buffer sizes

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala
I saw a failure at `probe.expectNoMessage(500.millis)` which was expected because the logic would use the maximum bracket `400ms - 800ms` if the maximum is set to `max-connection-backoff = 800ms`. So, I adapted the brackets and numbers slightly.
=> tests: harden Http2PersistentClientSpec

akka-http-core/src/main/mima-filters/10.2.5.backwards.excludes/3893-fix-http2-multiplexer-loop.excludes, akka-http-core/src/main/scala-2.13-/akka/http/ccompat/package.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> http2: prevent enqueuing OutStreams multiple times

docs/src/main/paradox/client-side/client-transport.md, docs/src/main/paradox/client-side/connection-level.md, docs/src/main/paradox/client-side/host-level.md, docs/src/main/paradox/client-side/pool-overflow.md, docs/src/main/paradox/client-side/websocket-support.md, docs/src/main/paradox/common/caching.md, docs/src/main/paradox/common/http-model.md, docs/src/main/paradox/common/sse-support.md, docs/src/main/paradox/compatibility-guidelines.md, docs/src/main/paradox/implications-of-streaming-http-entity.md, docs/src/main/paradox/introduction.md, docs/src/main/paradox/release-notes/10.0.x.md, docs/src/main/paradox/release-notes/10.2.x.md, docs/src/main/paradox/routing-dsl/directives/method-directives/overrideMethodWithParameter.md, docs/src/main/paradox/troubleshooting/unsupported-http-method-pri.md
No particular issue is relevant, just a documentation review.
Thanks for all your work on this toolkit!
=> docs: various documentation fixes

.github/workflows/validate-and-test.yml
The check will only run after being merged.
=> build: add fossa checks

.github/workflows/publish.yml, .github/workflows/validate-and-test.yml
YAML arrays seem to need commas (or just s single element in this case)
=> build: actually enable our GHA workflows for main branch

docs/src/test/java/docs/http/javadsl/server/directives/FutureDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/FutureDirectivesExamplesSpec.scala
This single test already failed so many builds...
=> docs: comment out flaky test

build.sbt, project/Publish.scala, project/plugins.sbt, scripts/release-train-issue-template.md
* Use publishRsync plugin
* Move publihsRsyncHost setting to 'docs'
but keep ThisBuild so it also applies to the root project
(cherry picked from commit f3fe3481a7bdc2645f9cbc969e629565df5e0583)
=> [10.1 backport] build: Use publishRsync plugin (#3305)

docs/src/main/paradox/release-notes/10.1.x.md, docs/src/main/paradox/security/2021-CVE-2021-42697-stack-overflow-parsing-user-agent.md, docs/src/main/paradox/security/2021.md, scripts/create-release-issue.sh, scripts/release-train-issue-template.md
=> 10.1.15 release notes

project/build.properties
Will move to 1.6.1 as well but haven't checked how well that works for now.
=> build: update to sbt 1.5.8

.scala-steward.conf
https://github.com/akka/akka-http/pull/3995#issuecomment-1009951997
https://github.com/akka/akka-http/pull/3996#issuecomment-1009953070
=> build: restrict scala-steward updates

.github/workflows/publish-test-reports.yml
This is using another action to also report tests, let's see how those look.
=> build: try other action for test reporting

docs/src/test/java/docs/http/javadsl/server/directives/FutureDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/FutureDirectivesExamplesSpec.scala
These have been pestering us for a long while without any resolution. So
let's comment them for now.
Fixes #3888
=> docs: finally disable flaky completeWithBreaker tests

akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/sse/ServerSentEventParserSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/sse/ServerSentEventParser.scala
=> http: interpret SSE heartbeats as events

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientServerSpec.scala
=> http2: silence noisy error when HTTP/2 connection is closed with idle-timeout

akka-http-core/src/main/scala/akka/http/scaladsl/model/sse/ServerSentEvent.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/sse/EventStreamUnmarshallingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/sse/ServerSentEventParserSpec.scala, akka-http/src/main/mima-filters/10.2.8.backwards.excludes/4043-ServerSentEventParser.excludes, akka-http/src/main/resources/reference.conf, akka-http/src/main/scala/akka/http/impl/settings/ServerSentEventSettingsImpl.scala, akka-http/src/main/scala/akka/http/javadsl/settings/ServerSentEventSettings.scala, akka-http/src/main/scala/akka/http/scaladsl/settings/ServerSentEventSettings.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/sse/EventStreamParser.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/sse/EventStreamUnmarshalling.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/sse/ServerSentEventParser.scala
=> http: hide empty SSE events behind flag

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala
=>  http2: unregister connection from MasterTermination when done

.github/workflows/nightly.yml
New configs are JDK 17 and Akka master
=> build: add nightly job to matrix of configurations

project/AkkaDependency.scala
Snapshot repository has changed to Sonatype snapshots.
=> build: fix determineLatestSnapshot for akka

akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
Fixes #4065
While unlikely, there was no guarantee that the first request was not yet finished
when the second request arrived at the pool and the connection was accepted.
=> core: fix race condition in NewConnectionPoolSpec

akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
Refs #4058
GracefulTerminationHandling has several race conditions that play out
differently in Akka 2.6. Most likely the reason is that write coalescing makes
it more likely that the error sent out when the termination timeout triggers
is able to overtake the sent out response.
=> core: make GracefulTerminationSpec less strict

project/MiMa.scala
Should turn up on Maven Central soon
=> build: add 10.2.9 to Mima

docs/src/test/scala/docs/http/scaladsl/Http2ClientApp.scala, docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala
Can be fixed properly when moving to 2.6
=> build: compile against right akka version in nightlies

project/AkkaDependency.scala
Nightlies stopped building against the true last snapshot last week... (and there seems to be a small regression since then)
=> build: properly sort snapshots so we will find last one after "+9"

akka-http-caching/src/test/scala/akka/http/scaladsl/server/directives/CachingDirectivesSpec.scala
Failed multiple times in nightlies.
=> test: harden CachingDirectivesSpec

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/SecurityDirectivesSpec.scala, akka-http/src/main/mima-filters/10.2.9.backwards.excludes/4146-Credentials-add-new-method-provide-verify.excludes, akka-http/src/main/scala/akka/http/scaladsl/server/directives/SecurityDirectives.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/SecurityDirectivesExamplesSpec.scala
References #1796
* Create provideVerify method
* Update tests in SecurityDirectivesExamplesSpec.scala
=> Allow custom verifier in Credentials.Provided

docs/src/main/paradox/release-notes/10.2.x.md
=> doc: Release notes for 10.2.10

CONTRIBUTING.md, LICENSE.txt, NOTICE.txt, README.md, build.sbt
https://www.lightbend.com/blog/why-we-are-changing-the-license-for-akka
=> Change license

.github/workflows/nightly.yml
=> build: Don't run nightly tests against Akka 2.6

project/Common.scala, project/Dependencies.scala, project/build.properties
=> Scala 2.12.17 & 2.13.10

.github/workflows/fossa.yml, .github/workflows/nightly.yml, .github/workflows/publish-test-reports.yml, .github/workflows/publish.yml, .github/workflows/validate-and-test.yml
* Move JDK name into the matrix names.
* Quoting
* More exact version for publishing, align with akka/akka
* Missing renames
References #4189
=> ci: select JDKs consistently

.github/workflows/nightly.yml, .github/workflows/validate-and-test.yml
=> Set max heap for JDK 8 in PR validation

akka-http-core/src/main/scala/akka/http/ParsingErrorHandler.scala
=> chore: Undo dummy commit

akka-http-caching/src/test/scala/akka/http/caching/ExpiringLfuCacheSpec.scala
=> fix: Race condition in ExpiringLfuCacheSpec 

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MethodDirectivesSpec.scala
=> fix: MethodDirectivesSpec tight timeout

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/PreviewServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, akka-http-core/src/test/resources/http2-preview-fallback.conf, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/settings/ServerSettingsSpec.scala, akka-http2-support/src/test/java/akka/http/javadsl/Http2JavaServerTest.java, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2SpecIntegrationSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/TelemetrySpiSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/WithPriorKnowledgeSpec.scala, akka-http2-support/src/test/scala/akka/http/scaladsl/Http2ServerTest.scala, docs/src/main/paradox/server-side/http2.md, docs/src/main/paradox/technologies.md, docs/src/main/paradox/troubleshooting/unsupported-http-method-pri.md
=> chore: Un-preview the HTTP/2 server support 

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala
=> fix: http2-enable flag was not picking up the old one

.github/workflows/publish.yml
=> build: Don't touch files before publishing docs

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2HighlevelServerSpec.scala
=> fix: Recover handler errors, turn into HTTP 500 response 

.github/workflows/publish.yml
=> fix: Balance them curlies in CI config

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala
References #4244, #4225, #4104
=> chore: Ignore test case tear down race condition warning

akka-http-core/src/main/mima-filters/10.5.2.backwards.excludes/ssl-config-drop.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala, akka-http-core/src/main/scala/akka/http/javadsl/ConnectionContext.scala, akka-http-core/src/main/scala/akka/http/scaladsl/ConnectionContext.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/test/scala/akka/http/javadsl/ConnectHttpSpec.scala
Noticed in nightlies failing after we dropped SSLConfig from Akka
=> chore: Dropping more internal related to the removed SSLConfig

project/build.properties
Includes security fix for coursier/ivy
=> bump: sbt 1.9.4

.github/workflows/nightly.yml, .github/workflows/publish-test-reports.yml, .github/workflows/validate-and-test.yml, build.sbt, docs/src/main/paradox/migration-guide/migration-guide-10.6.x.md, project/Dependencies.scala
See https://github.com/akka/akka/pull/32125
=> chore: Drop Scala 2.12

.github/workflows/nightly.yml, .github/workflows/publish-test-reports.yml, .github/workflows/validate-and-test.yml, build.sbt, docs/src/main/paradox/migration-guide/migration-guide-10.6.x.md, project/Common.scala, project/Doc.scala, project/project-info.conf
See https://github.com/akka/akka/pull/32127
=> chore: Drop JDK 8

docs/release-train-issue-template.md, project/Publish.scala
=> build: temporary snapshot repo

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/framing/RSTFrameLimit.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/Http2ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Backport of #4324 from main
References #4323
=> backport: Rate limit protection against rapid resets (#4324)

akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/PersistentConnection.scala, akka-http2-tests/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala
References #3892 
Superseedes #4299
=> fix: Emit a failed response for the triggering request on connection failure

docs/release-train-issue-template.md
Refs https://github.com/lightbend/akka-meta/issues/393#issuecomment-1788563212
=> chore: Include quickstart bumping in release template

.github/workflows/nightly.yml, .github/workflows/publish-test-reports.yml, .github/workflows/publish.yml, RELEASING.md, docs/src/main/paradox/contributing.md, project/AkkaDependency.scala, project/Publish.scala
* and publish docs with new ssh key
=> build: Publish snapshots

akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
The important thing is the runtime.
=> chore: Don't version check the test modules, 

CODE_OF_CONDUCT.md, README.md
References
- https://github.com/akka/akka/pull/32295
=> chore: point to current versions in the Readme

.github/workflows/nightly.yml
Type inference problems with JDK 21_35
=> build: Nightly test on a later patch of JDK 21

.github/workflows/native-image-tests.yml
Adding a mostly empty job so I can iterate on tests in actual PR #4349
=> build: Native image test placeholder

LICENSE.txt
References https://github.com/akka/akka-http/issues/4354
=> chore: Update license change date

docs/src/main/paradox/introduction.md
=> docs: fix div tag in introduction.md

project/MiMa.scala
=> build: post 10.6.1 mima plugin config

project/Doc.scala
=> bump: genjavadoc 0.19

.fossa.yml, .github/workflows/algolia-doc-site-scrape.yml, .github/workflows/fossa.yml, .github/workflows/native-image-tests.yml, .github/workflows/nightly.yml, .github/workflows/publish.yml, .github/workflows/validate-and-test.yml, CODE_OF_CONDUCT.md, README.md, docs/release-train-issue-template.md, project/plugins.sbt, project/project-info.conf
References https://github.com/lightbend/akka-meta/issues/428
=> chore: repo gardening

LICENSE.txt
References https://github.com/akka/akka-http/issues/4378
=> chore: License change date for 10.6.2

.github/workflows/publish-docs.yml
As we have it in other Akka repos.
=> build: Split out docs publish workflow to allow post-release docs publish

.github/workflows/check-samples.yml
=> build: Fix sample check workflow

.algolia-search-index-config.json, CONTRIBUTING.md, README.md, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterface.scala, akka-http-core/src/main/scala/akka/http/javadsl/model/ws/UpgradeToWebSocket.scala, akka-http-core/src/main/scala/akka/http/javadsl/model/ws/WebSocketUpgrade.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/ws/WebSocketUpgrade.scala, build.sbt, docs/release-train-issue-template.md, docs/src/main/paradox/client-side/client-transport.md, docs/src/main/paradox/routing-dsl/directives/route-directives/handle.md, project/AkkaDependency.scala, samples/akka-http-quickstart-scala/src/main/resources/logback.xml
Updating URLs for the upcoming release train.
References
- https://github.com/akka/akka/pull/32518
=> docs: revice URL structure (libraries)

project/MiMa.scala
Post release item for https://github.com/akka/akka-http/issues/4438.
=> build: align mima for 10.7.0 release

.scala-steward.conf, project/plugins.sbt
Without this the project does not load locally for me (how does it pass CI checks?)
=> bump: sbt-scalafix that works with Scala 2.13.15

.scala-steward.conf, project/Dependencies.scala
See https://github.com/akka/akka/pull/32705
=> bump: Jackson 2.18.3

LICENSE.txt, native-image-tests/build.sbt, samples/akka-http-quickstart-java/pom.xml, samples/akka-http-quickstart-scala/build.sbt
References https://github.com/akka/akka-http/issues/4486
=> chore: License change date and sample bumps for 10.7.1

project/MiMa.scala
References https://github.com/akka/akka-http/issues/4486
=> build: 10.7.1 in MiMa conf

akka-http-tests/src/test/scala/akka/http/impl/settings/CorsSettingsSpec.scala, akka-http/src/main/scala/akka/http/impl/settings/CorsSettingsImpl.scala
=> chore: Case insensitive header name match in CORS

.github/workflows/check-samples.yml
Fixes https://github.com/akka/akka-http/actions/runs/15875736569/job/44762761391#step:9:22
=> chore: add mvn creds to quickstart-java

project/MiMa.scala
References https://github.com/akka/akka-http/issues/4506
=> build: Add 10.7.2 to MiMa

project/AkkaDependency.scala
Failing in https://github.com/akka/akka-http/actions/runs/18116725520/job/51553497399#step:6:45
=> build: fix nightly snapshot repo config
