akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpRequestRendererFactory.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/WSServerAutobahnTest.scala, akka-http-core/src/test/scala/akka/http/scaladsl/TestServer.scala, akka-http-core/src/test/scala/akka/http/scaladsl/settings/SettingsEqualitySpec.scala, akka-http-core/src/test/scala/akka/testkit/AkkaSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/ConnectionTestApp.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/TcpLeakApp.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToRequestMarshallers.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/BasicDirectives.scala, docs/src/test/java/docs/http/javadsl/server/directives/SecurityDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/WebSocketClientExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/BlockingInHttpExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/HttpsServerExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/WebSocketExampleSpec.scala
As part of getting familiar with akka-http I went through a part of compiler warnings and fixed them.
Mostly they were related to deprecation, there were few related to dead code.
I have only touched the warnings that are straightforward to fix because I didn't want to break anything
I'm not sure about the warnings related to `parboiled2` - should they be fixed here, or in the https://github.com/sirthias/parboiled2 repository ?
There was no issue related to this PR
=> fixed a part of compiler warnings

akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/TestRouteResult.scala
While not sure if it is a desired behavior, I'd like to propose such a change :innocent: .
=> Both assertHeaderExists functions now behave in the same way.

docs/src/main/paradox/java/http/routing-dsl/directives/marshalling-directives/entity.md, docs/src/test/java/docs/http/javadsl/server/directives/MarshallingDirectivesExamplesTest.java
Refs #218 entity directive
From entity.md, I removed mentions to spray-json and JsValue, but is that ok? I was assuming currently supported marshalling methods in Java is only via Jackson, as in [marshalling.html](http://doc.akka.io/docs/akka/2.4/java/http/routing-dsl/marshalling.html), but let me know if that is wrong.
=> Add entity directive example

akka-http-tests/src/test/resources/dirWithLink/linked-dir, akka-http-tests/src/test/resources/sübdir/sample späce.PDF, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala
@2beaucoup here's a new fix without all your extra changes. AFAICS these should apply also to former versions for which we might have to issue a fix release.
WDYT about containing the changes inside of the new `safeDirectoryChildPath` (old `fileSystemPath`)?
Fixes #346.
=> Fix directory traversal in Windows in getFromDirectory / listDirectoryContents

build.sbt, docs/src/main/paradox/java/http/client-side/client-https-support.md, docs/src/main/paradox/java/http/common/de-coding.md, docs/src/main/paradox/java/http/common/json-support.md, docs/src/main/paradox/java/http/common/marshalling.md, docs/src/main/paradox/java/http/common/unmarshalling.md, docs/src/main/paradox/java/http/http-model.md, docs/src/main/paradox/java/http/routing-dsl/directives/future-directives/onCompleteWithBreaker.md, docs/src/main/paradox/java/http/routing-dsl/rejections.md, docs/src/main/paradox/java/http/routing-dsl/routes.md, docs/src/main/paradox/java/http/server-side/low-level-server-side-api.md, docs/src/main/paradox/java/http/server-side/websocket-support.md, docs/src/main/paradox/scala/http/client-side/client-https-support.md, docs/src/main/paradox/scala/http/client-side/index.md, docs/src/main/paradox/scala/http/common/de-coding.md, docs/src/main/paradox/scala/http/common/http-model.md, docs/src/main/paradox/scala/http/common/json-support.md, docs/src/main/paradox/scala/http/common/marshalling.md, docs/src/main/paradox/scala/http/common/unmarshalling.md, docs/src/main/paradox/scala/http/common/xml-support.md, docs/src/main/paradox/scala/http/handling-blocking-operations-in-akka-http-routes.md, docs/src/main/paradox/scala/http/low-level-server-side-api.md, docs/src/main/paradox/scala/http/migration-guide-2.4.x-experimental.md, docs/src/main/paradox/scala/http/routing-dsl/directives/coding-directives/requestEncodedWith.md, docs/src/main/paradox/scala/http/routing-dsl/directives/custom-directives.md, docs/src/main/paradox/scala/http/routing-dsl/directives/future-directives/onCompleteWithBreaker.md, docs/src/main/paradox/scala/http/routing-dsl/exception-handling.md, docs/src/main/paradox/scala/http/routing-dsl/rejections.md, docs/src/main/paradox/scala/http/routing-dsl/testkit.md, docs/src/main/paradox/scala/http/routing-dsl/websocket-support.md
This is a preliminary PR to knock another two points off of #318 
It depends on lightbend/paradox#27 being available in a new Paradox release.
=> Update external links to Akka docs and GitHub source code

akka-http-core/src/main/scala/akka/http/impl/settings/RoutingSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/RoutingSettings.scala, akka-http-core/src/test/resources/reference.conf, akka-http-tests/src/test/scala/akka/http/scaladsl/server/BasicRouteSpecs.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ExecutionDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FutureDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/RouteDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/SecurityDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/RouteDirectivesExamplesSpec.scala
Reused already existing property type. Set to full logging in tests as event filters asserts on that.
=> Error logging verbosity is not configurable for routing and used to determine log content of ErrorHandler (#16).

docs/src/main/paradox/scala/http/migration-from-spray.md
First argument of MediaType.applicationWithFixedCharset is only the subType, not the full MediaType name.
=> Fix typo in the spray migration guide

docs/src/main/paradox/java/http/routing-dsl/index.md, docs/src/main/paradox/scala/http/routing-dsl/index.md
Found some typos in the java and scala version of [High-level Server-Side API](http://doc.akka.io/docs/akka/2.4/scala/http/routing-dsl/index.html) and fixed them.
=> =doc fix typos in High-level Server-Side API

akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/MarshallingTestUtils.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/MarshallingSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToResponseMarshallers.scala
RFC 7231 3.4.1 states:
```
A user agent cannot rely on proactive negotiation preferences being
consistently honored, since the origin server might not implement
proactive negotiation for the requested resource or might decide that
sending a response that doesn't conform to the user agent's
preferences is better than sending a 406 (Not Acceptable) response.
```
So, especially for status code responses which usually won't contain any
actual "resource" at all, it makes more sense to return the status code
and a `text/plain` response with the status codes default message instead
of requiring the client to accept `text/plain` just to support receiving
status information.
Fixes #366.
/cc @leachbj
/cc @gosubpl (since you changed the code the last time)
=> =htp #366 disable content-type negotiation for responses marshalled from status codes

akka-http-core/src/test/scala/akka/http/scaladsl/util/FastFutureSpec.scala
Increase timeout a bit.
Resolves https://github.com/akka/akka-http/issues/392
=> fix too tight timeout (because jenkins) #392

akka-http-core/src/main/java/akka/http/javadsl/model/MediaTypes.java, akka-http-core/src/main/java/akka/http/javadsl/model/Multipart.java, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/BodyPartRenderer.scala, akka-http-core/src/main/scala/akka/http/impl/util/StageLogging.scala, akka-http-core/src/main/scala/akka/http/javadsl/model/MediaType.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/MultipartSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/MarshallingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/MultipartUnmarshallersSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/MultipartMarshallers.scala, docs/src/test/java/docs/http/javadsl/server/directives/FileUploadDirectivesExamplesTest.java
Here's an update to @derekwyatt's #339. We somewhat break bin compat for the MediaType constants but try to keep it for `Multipart.toEntity`.
=> Update to #339

build.sbt, project/Common.scala
Fixes #408
`inThisBuild` sets project scope to the current build, but settings set in the `/build.sbt` are added to the root project only.
Instead moved common settings to an AutoPlugin that is applied to every project.
=> Move common settings to an autoplugin 

build.sbt, project/Publish.scala, project/ValidatePullRequest.scala
Remove the crossVersion setting since SBT will automatically set it to
`CrossVersion.binary` when `crossPaths` is `true` which is the default.
As for the cause, defining it inside `inThisPlugin` creates a conflict
with SBT's default which is automatically added to each subproject.
Fixes the following error reported for `show crossVersion`:
akka-http-root > show crossVersion
[error] Ambiguous keys: {.}/*:crossVersion, *:crossVersion
[error] show crossVersion
[error]                  ^
---
With this I get the following:
```
akka-http-root > show crossVersion
[info] akka-http-testkit/*:crossVersion
[info] 	Binary
[info] akka-http-core/*:crossVersion
[info] 	Binary
[info] akka-http-jackson/*:crossVersion
[info] 	Binary
[info] akka-http-marshallers-java/*:crossVersion
[info] 	Binary
[info] …
```
=> Fix SBT's ambiguous keys error for crossVersion

CONTRIBUTING.md
Issue #429
* Replace Akka project name with akka-http project name
* Update github URLS to right project
* Removed not present branches
* Removed Contrib module as it doesn't exist in akka-http
* Updated tags to more meaningful ones in akka-http
=> Replace Akka with Akka-http when it refers to the project name #429

akka-http-core/src/main/java/akka/http/javadsl/model/HttpEntity.java, akka-http-core/src/main/java/akka/http/javadsl/model/HttpMessage.java, akka-http-core/src/main/scala/akka/http/javadsl/Http.scala, akka-http-core/src/main/scala/akka/http/javadsl/ServerBinding.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FramedEntityStreamingDirectives.scala, akka-parsing/build.sbt, build.sbt, project/Doc.scala, project/Publish.scala
Adapts the Unidoc auto plugins from akka/akka to work in akka/akka-http with minimal changes.
=> Reenable sbt-unidoc settings

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpAttributes.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerTestSetupBase.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Additionally, I've "borrowed" @jrudolph tests.
=> Bind and BindAndHandle handles remote address in the same way now (#344). Refactoring to decrease code duplication.

akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/rendering/RequestRendererSpec.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/MarshallingTestUtils.scala
With a small cleanup to make future timeouts more explicit in `LowLevelOutgoingConnectionSpec`.
=> Fix test timeouts

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/DebuggingDirectivesSpec.scala, build.sbt, docs/src/main/paradox/scala/http/common/json-support.md, docs/src/test/scala/docs/http/scaladsl/SprayJsonPrettyMarshalSpec.scala, project/Dependencies.scala
Fixes two tests to work with Scala 2.12:
- SprayJsonPrettyMarshalSpec defined a trait inside a test scope, which
resulted in a ClassFormatError:
[info] docs.http.scaladsl.SprayJsonPrettyMarshalSpec **\* ABORTED ***
[info]   java.lang.ClassFormatError: Duplicate field name&signature in class file docs/http/scaladsl/SprayJsonPrettyMarshalSpec$MyJsonService$1
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
- The fix for https://issues.scala-lang.org/browse/SI-9019 causes
DebuggingDirectivesSpec to fail by printing `ByteString.ByteString1C`
instead of `ByteString` in Scala 2.11.
=> Cross compile to Scala 2.12.0-RC2 (#437)

docs/src/main/paradox/java/http/routing-dsl/exception-handling.md, docs/src/main/paradox/java/http/routing-dsl/rejections.md, docs/src/main/paradox/java/http/routing-dsl/routes.md, docs/src/main/paradox/java/http/routing-dsl/testkit.md, docs/src/main/paradox/scala/http/routing-dsl/routes.md, docs/src/main/paradox/scala/http/routing-dsl/testkit.md, docs/src/test/java/docs/http/javadsl/ExceptionHandlerExample.java, docs/src/test/java/docs/http/javadsl/RouteSealExample.java, docs/src/test/scala/docs/http/scaladsl/RouteSealExampleSpec.scala
The following pages already have route sealing descriptions which I copied from.
[testkit](http://doc.akka.io/docs/akka/2.4.11/scala/http/routing-dsl/testkit.html#sealing-routes)
[rejection-handler](http://doc.akka.io/docs/akka/2.4.11/scala/http/routing-dsl/rejections.html#the-rejectionhandler)
[exception-handler](http://doc.akka.io/docs/akka/2.4.11/scala/http/routing-dsl/exception-handling.html#exception-handling-scala)
The Java documentation looks still under construction, so when we do rework, route-sealing sections should be extended?
[Java testkit (no mention to sealing)](http://doc.akka.io/docs/akka/2.4.11/java/http/routing-dsl/testkit.html#sealing-routes)
[Java rejection-handler](http://doc.akka.io/docs/akka/2.4.11/java/http/routing-dsl/rejections.html#the-rejectionhandler)
[Java …
=> Add route sealing description to routes.md

akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/HttpCredentials.scala
Removing the sealed, as it breaks scaladoc.
Java extends this class.
Model is special, we'll write up that people should not be extending it randomly in any case.
=> =htc remove too restrictive sealed (java extends it)

docs/src/main/paradox/scala/http/migration-guide/migration-from-spray.md
Add some overview documentation of the changes and, in particular, point
to further documentation about entity streaming.
=> =doc #280,#397 extend migration guide

akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerBug21008Spec.scala
Also renames the test to reflect the original bug number.
Ref: akka/akka#21008
=> Fix #19: Bump leeway timeout to 1s in HttpServerBug21008Spec

docs/src/main/paradox/scala/http/routing-dsl/path-matchers.md
Issue: #476
Fix extra empty lines on operator titles.
Fix table rendering (extra line was missing)
Fix unary_! title, by removing the code snippet syntax (as it should be a title)
=> Path matchers docu fix

akka-http-core/src/test/scala/akka/http/impl/util/One2OneBidiFlowSpec.scala
It seems the test was meant to full the buffer and emit additional 8 elements. If we stall flow it should read  `0` vs `24` from counter and compare `24+8` to `0+8`.
=> BidiFlow backpressure test case checks if buffer has been filled up now (#423).

akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolConductor.scala
Minor improvements to error logging output in PoolConductor bringing it in-line with other GraphStages
=> =htc align logging in PoolConductor to other GraphStages (#482)

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/javadsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Actually providing better guarantees turned out to be difficult, so
being clear about the limit being an approximate one seems to be the
best solution for now.
See also the discussions in https://github.com/akka/akka-http/pull/371.
Fixes #368.
@2m WDYT?
=> =htc #368 document the guarantees of `max-connections`

project/Doc.scala
Set -Xdoclint:none to fix genjavadoc:doc.
Based on akka/akka@098ef546d70b67a6e7b08c1e1223e5902b68ce2f but only add
the setting when `akka.genjavadoc.enabled=true`.
---
With this I get
```
> sbt -Dakka.genjavadoc.enabled=true genjavadoc:doc | grep 'Genjavadoc Java API documentation successful'
[info] Genjavadoc Java API documentation successful.
[info] Genjavadoc Java API documentation successful.
[info] Genjavadoc Java API documentation successful.
[info] Genjavadoc Java API documentation successful.
[info] Genjavadoc Java API documentation successful.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Genjavadoc Java API …
```
=> Disable Javadoc errors for missing references (#498)

project/ParadoxSignatureDirective.scala
@jrudolph, a change we discussed today @ gitter.
=> Paradox reads fromFile with explicit encoding now (UTF-8). Fixes quirks under Windows.

docs/src/main/paradox/java/http/index.md, docs/src/main/paradox/java/http/introduction.md, docs/src/main/paradox/scala/http/introduction.md, docs/src/test/java/docs/http/javadsl/ClientSingleRequestExample.java, docs/src/test/java/docs/http/javadsl/HttpServerActorInteractionExample.java, docs/src/test/java/docs/http/javadsl/HttpServerLowLevelExample.java, docs/src/test/java/docs/http/javadsl/HttpServerMinimalExampleTest.java, docs/src/test/java/docs/http/javadsl/HttpServerStreamRandomNumbersTest.java, docs/src/test/java/docs/http/javadsl/JacksonExampleTest.java, docs/src/test/java/docs/http/javadsl/SprayJsonExampleTest.java
Issue: #454
Add Java snippets for:
- Minimal Server (#minimal-routing-example)
- Spray JSON example (#second-spray-json-example)
- Streaming Random Numbers (#stream-random-numbers)
Missing Java snippets for:
- Actor Interaction (#actor-interaction)
- Low Level Server Example (#actor-interaction)
- Single Client Request (#single-request-example)
=> Add Intro documentation for Java API (#454)

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/AlpnSwitch.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameParser.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/WrappedSslContextSPI.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
This will still contain a serious hack to transport the chosen ALPN protocol to the switch stage because the switch is done based on the engine (which we would never actually see) and the streaming TLS API only gives access to the SSLSession which doesn't seem to offer any backreferences to the engine...
/cc @ktoso
=> ALPN switch between Http/1 vs Http/2

docs/src/main/paradox/java/http/routing-dsl/directives/misc-directives/extractClientIP.md, docs/src/main/paradox/java/http/routing-dsl/directives/misc-directives/requestEntityEmpty.md, docs/src/main/paradox/java/http/routing-dsl/directives/misc-directives/requestEntityPresent.md, docs/src/main/paradox/java/http/routing-dsl/directives/misc-directives/selectPreferredLanguage.md, docs/src/main/paradox/java/http/routing-dsl/directives/misc-directives/validate.md, docs/src/test/java/docs/http/javadsl/server/directives/MiscDirectivesExamplesTest.java
Issue: #218
Added Java Examples for `extractClientIP`, `requestEntityPresent`, `requestEntityEmpty`, `selectPreferredLanguage` and `validate`.
`rejectEmptyResponse` will come in separate PR.
=> Misc directives java examples

docs/src/main/paradox/java/http/common/index.md, docs/src/main/paradox/java/http/index.md, docs/src/main/paradox/scala/http/common/index.md, docs/src/main/paradox/scala/http/index.md, docs/src/main/paradox/scala/http/routing-dsl/directives/websocket-directives/handleWebSocketMessages.md, docs/src/main/paradox/scala/http/routing-dsl/directives/websocket-directives/handleWebSocketMessagesForProtocol.md, docs/src/main/paradox/scala/http/routing-dsl/index.md, docs/src/main/paradox/scala/http/websocket-support.md
Issue: #465
Make Http Model entry a first level topic
Make server side Websocket Support a first level topic
Additionally, fixed the Java docs, Http Model was supposed to be first level topic but it wasn't shown as it also belogned to `commons/index.md`
=> Scala docs reorg

akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala
=> =htc #364 add test that backpressure will be fixed on akka 2.4.14

README.md, project/Publish.scala
Because this is the package name we got from bintray which is linked to JCenter and can not rename it.
=> Update bintray package

docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala
Improves the examples by removing imports from the top of the file and explicitly importing inline within examples.
I'm happy to go through other parts of the documentation, just want to make sure I'm on the right track first!
cc @ktoso, per https://github.com/akka/akka-http/pull/487#issuecomment-258929762.
=> Improve http client documentation

project/plugins.sbt
the newest version supports Scala 2.12 properly and is capable of
detecting a variety of compatibility issues older versions missed
=> upgrade to latest MiMa (0.1.12)

CONTRIBUTING.md, akka-http-core/src/main/java/akka/http/javadsl/model/HttpEntity.java, akka-http-core/src/main/java/akka/http/javadsl/model/HttpMethod.java, akka-http-core/src/main/java/akka/http/javadsl/model/HttpMethods.java, akka-http-core/src/main/java/akka/http/javadsl/model/RemoteAddress.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/EntityTagRange.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/HttpEncodingRange.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/HttpOriginRange.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/LanguageRange.java, akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/HttpChallenge.scala, docs/src/main/paradox/java/http/migration-guide/index.md, docs/src/main/paradox/java/http/migration-guide/migration-guide-2.4.x-10.0.x.md, docs/src/main/paradox/scala/http/migration-guide/index.md, docs/src/main/paradox/scala/http/migration-guide/migration-guide-2.4.x-10.0.x.md
Refs #597 
* java/http/migration-guide/index.md
* scala/http/migration-guide/index.md
are important to fix paradox generation failure.
As 10.0.0 already out, when do we work on these FIXMEs and TODOs? To be fixed in 11.0? 
If we fix them immediately, I added some of them (e.g. HttpMethods.java) before, so I can easily fix those in separate PRs.
=> Update Akka Http version from 3.0 to 10.0 in misc places (Fixes #597)

docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala
The actor interaction example in the Introduction page of the Scala docs doesn't actually compile or even run. 
Firstly, the Auction actor itself is not defined. A companion object was written, but was mistakenly put outside of the test's scope. I defined a simple Auction actor that, upon receiving a `Bid`, prints a message to stdout. If it receives any other message, it prints "Invalid message".
Secondly, `Props` is used incorrectly - it's assuming there is a companion object - and some imports are missing. I fixed both of these issues as well.
=> `actor-interaction` example should now run

akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala, akka-http-core/src/main/scala/akka/http/impl/util/One2OneBidiFlow.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala, akka-http-core/src/test/scala/akka/http/impl/util/One2OneBidiFlowSpec.scala
We will now send an `UnexpectedConnectionClosureException` which more
closely explains the problem at hand.
Also, the error is reported with `failStage` instead of throwing which
prevents the noisy logging.
Fixes #616.
=> =htc #616 replace OutputTruncationException for the http client use case

docs/src/main/paradox/java/http/routing-dsl/directives/index.md, docs/src/test/java/docs/http/javadsl/server/DirectiveExamplesTest.java
Issue: #594
Add section explaining the different alternatives to compose routes using the Java DSL.
* Example using `orElse`
* Example combining directives in own method
* Example using `route`
* Example using `roture` with several alternatives
=> docs #594 Add section about Composing Directives Java

docs/src/main/paradox/java/http/client-side/client-https-support.md, docs/src/main/paradox/scala/http/client-side/client-https-support.md
resolves https://github.com/akka/akka-http/issues/645
=> remove outdated https client warning in docs #645

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpMessageSpec.scala
When the server receives a request it will try to reconstruct the
effective request URI as defined in HTTP/1.1 [1]. Requests using
HTTP/1.0 will use the same code path but since the `Host` header is not
required in HTTP/1.0 Akka HTTP requires that a default `Host` header
value is configured in `akka.http.server.default-host-header`. In
addition to the documentation in `reference.conf` make this more clear
by also hinting to the setting in the error log as discussed in #596.
[1]: https://tools.ietf.org/html/rfc7230#section-5.5
=> Improve the server-side log message when default-host-header is not set

docs/src/main/paradox/scala/http/routing-dsl/directives/basic-directives/extract.md, docs/src/main/paradox/scala/http/routing-dsl/directives/basic-directives/extractLog.md, docs/src/main/paradox/scala/http/routing-dsl/directives/basic-directives/mapRequest.md, docs/src/main/paradox/scala/http/routing-dsl/directives/basic-directives/mapResponse.md, docs/src/main/paradox/scala/http/routing-dsl/directives/basic-directives/mapRouteResult.md, docs/src/main/paradox/scala/http/routing-dsl/directives/basic-directives/provide.md, docs/src/main/paradox/scala/http/routing-dsl/directives/basic-directives/withLog.md, docs/src/main/paradox/scala/http/routing-dsl/directives/security-directives/authorize.md, docs/src/main/paradox/scala/http/routing-dsl/directives/security-directives/authorizeAsync.md, docs/src/main/paradox/scala/http/routing-dsl/directives/security-directives/extractCredentials.md, docs/src/test/scala/docs/http/scaladsl/server/directives/BasicDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/SecurityDirectivesExamplesSpec.scala
Issue: #636
Paradox doesn't seem to support snippets whose id starts with a number.
Change id format for offending ones.
=> Docs. Change snippet id to not start with a number

akka-http-tests/src/test/scala/akka/http/scaladsl/server/RejectionSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/TestServer.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala, docs/src/main/paradox/scala/http/routing-dsl/rejections.md, docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala
Improves ease of customising rejection triggered http responses, and only those so it's more precise than the solution proposed in http://stackoverflow.com/questions/34620297/how-to-generically-wrap-a-rejection-with-akka-http 
Resolves https://github.com/akka/akka-http/issues/673
Please review @jrudolph
=> +htp #673 allow mapping rejection handled responses

akka-http-core/src/main/java/akka/http/javadsl/model/Multiparts.java, akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala, akka-http-core/src/test/scala/akka/http/javadsl/model/MultipartsSpec.scala
java doesn't allow to cast:
```
akka.http.scaladsl.model.Multipart.FormData.BodyPart bp = (akka.http.scaladsl.model.Multipart.FormData.BodyPart)Multiparts.createFormDataBodyPartStrict("", HttpEntities.create(""));
```
java says it's ambigous, so it's impossible to call `akka.http.scaladsl.model.Multipart.FormData.apply(Source.single(bp));`
=> Add a way to transform a Source<BodyPart, Object> to a FormData object in Java

project/Doc.scala
Fix #684 by using -skip-packages to ignore the package from generated
Scaladoc.
=> =doc Remove akka.pattern package from Scaladoc (#684)

RELEASING.md, project/MiMa.scala
Otherwise, we would only check subprojects against versions for which a
`mima-filters/<version>.*` file would have already been created.
=> =pro manually maintain list of previous versions in MiMa.scala

docs/src/main/paradox/scala/http/introduction.md
The scala version wasn't explicitly stated in the file `tutorial.md` which might surprised reader(s)
=> Make explicit the scala lib release to readers

akka-http-marshallers-scala/akka-http-spray-json/src/main/mima-filters/10.0.1.backwards.excludes, akka-http-marshallers-scala/akka-http-spray-json/src/main/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonByteStringParserInput.scala, akka-http-marshallers-scala/akka-http-spray-json/src/main/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupport.scala, akka-http-marshallers-scala/akka-http-spray-json/src/test/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupportSpec.scala, akka-http/src/main/mima-filters/10.0.1.backwards.excludes, akka-http/src/main/scala/akka/http/javadsl/unmarshalling/Unmarshaller.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/Unmarshaller.scala, project/Dependencies.scala
Changes:
* upgrade to spray-json 1.3.3 (which has working 4-byte UTF-8 character decoding for all Scala versions)
* use new IndexedBytesParserInput to avoid copied code from spray-json
* refactor unmarshallers to base all on a single implementation
* fix tests to actually test more kinds of UTF-8 characters
Fixes #691.
=> Fix spray-json unmarshalling

akka-http/src/main/scala/akka/http/javadsl/unmarshalling/Unmarshaller.scala
Issue: #604
Return types should belong to Java DSL only.
Add extra method `entityToMultipartFormData` to unmarshall multipart form data objects.
=> Fix Java Unmarshaller to return only Java DSL classes

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/PathDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/PathMatcher.scala
Fixes #394 by ensuring order of the provided mappings instead of leaving it up to the undefined order provided by the map implementation.
It might be a bit overkill to include all of the test cases created by @gosubpl but I included them for completeness and to test with `ListMap`.
=> Match path maps in order of longest matching key prefix (#394)

akka-http-tests/src/test/java/akka/http/javadsl/server/directives/ComposingDirectivesTest.java, akka-http/src/main/scala/akka/http/javadsl/common/PartialApplication.scala, akka-http/src/main/scala/akka/http/javadsl/server/Directives.scala, docs/src/main/paradox/java/http/routing-dsl/directives/index.md, docs/src/test/java/docs/http/javadsl/ComposeDirectivesExampleTest.java, docs/src/test/java/docs/http/javadsl/server/DirectiveExamplesTest.java
Issue: #620
Add composing capabilities for the Java DSL.
* `anyOf` is the equivalent of Scala's `|`
* `allOf` is the equivalent of Scala's `&`
=> Add Composing directives java (#620)

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameParser.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Compliance.scala
Introduces self dependency checks for `HEADER` and `PRORITY` frames, making `5.3` pass. Also adds missing size check for `PRIORITY` frame
=> improve h2spec compliance - fixes 5.3 (#245)

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameParser.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameRenderer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderDecompression.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FramingSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Small one propagating the priority info from frames.
Initially, I thought we might just render this as an additional PriorityFrame. I think, however, that it might make sense to model it accurately, so that priority information is complete from the start.
=> =ht2 parse and render priority information of HEADERS frames

docs/src/main/paradox/scala/http/routing-dsl/directives/custom-directives.md
As seen can be seen in the code sample directly above the modified sentence sentence, the methods name is `tapply` rather than `happly`.
Location in live documentation: http://doc.akka.io/docs/akka-http/current/scala/http/routing-dsl/directives/custom-directives.html#directives-from-scratch
=> Fix typo of the `tapply` method from `Directive`

docs/src/main/paradox/_template/page.st
- Removes unused HTML from the generated output by using ST4 comments.
- Add standard Akka doc footer info with copyright, license and date
for last update. <img width="1044" alt="screen shot 2017-01-13 at 10 32 30 pm" src="https://cloud.githubusercontent.com/assets/8417/21952055/47b1910a-d9e0-11e6-97e8-995735185b2b.png">
- Fix undentation comment.
- Ensure that the search box spans the whole left panel by overriding
Algolia's default CSS styles. <br /><img width="247" alt="screen shot 2017-01-13 at 10 32 40 pm" src="https://cloud.githubusercontent.com/assets/8417/21952054/43d4fdce-d9e0-11e6-84e8-efbcabc09f3e.png">
=> =doc Improve the Paradox page template

akka-http-core/src/main/scala/akka/http/impl/engine/ws/MessageToFrameRenderer.scala, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala
Previously, a single empty frame was created to start a WS message. Now,
a streamed message will only be begun when the first data comes in.
=> =htc #748 optimize frame creation for streamed WS messages

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameLogger.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Compliance.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Protocol.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/FrameRenderer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameRendering.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderDecompression.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/framing/Http2FramingSpec.scala
Minimal changes to get the settings handling rolling, handle incoming SETTINGS_HEADER_TABLE_SIZE. Not handling outgoing, since we don't send them anyway.
The Rendering stage I'd like to keep, at least for now, since the Data rendering there will be nice to impl there. I'm not so very keen on making it a statefulMapConcat for now, we can later if indeed looks good?
Resolves https://github.com/akka/akka-http/issues/776
=> +ht2 #776 handle incoming SETTINGS_HEADER_TABLE_SIZE

akka-http-core/src/main/scala/akka/http/scaladsl/model/Uri.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala
Applied @jrudolph's comment in #784
=> Fixes #784 exclude leading double slash from Uri.Authority.toString

akka-http-tests/src/test/java/akka/http/javadsl/server/MinimalHttpApp.java, akka-http-tests/src/test/java/akka/http/javadsl/server/SneakHttpApp.java, akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/HttpAppSpec.scala, akka-http/src/main/java/akka/http/javadsl/server/HttpApp.java, akka-http/src/main/scala/akka/http/scaladsl/server/HttpApp.scala, docs/src/main/paradox/java/http/routing-dsl/HttpApp.md, docs/src/main/paradox/java/http/routing-dsl/index.md, docs/src/main/paradox/scala/http/routing-dsl/HttpApp.md, docs/src/main/paradox/scala/http/routing-dsl/index.md, docs/src/test/java/docs/http/javadsl/server/HttpAppExampleTest.java, docs/src/test/scala/docs/http/scaladsl/HttpAppExampleSpec.scala
Issue: #156
Add a bootstrap trait that does all the boilerplate for you. Just write as much as you need, not more.
I converted some of the examples under the docs project to Objects extending `HttpApp` to see how the trait works and how much code it saves.
Feedback and additional hooks proposal are highly welcomed!
=> Provide HttpApp API for Scala and Java

build.sbt, project/ValidatePullRequest.scala
Run the paradox task to validate that PRs do not introduce doc
regressions. Since doc generation is not timing sensitive it is fine to
run this outside of the Jenkins cluster and this avoids to further
complicate the PR validation code.
-----
Based on https://github.com/akka/akka-http/pull/798#issuecomment-273898023
/cc @jlprat @ktoso
=> Fix PR validation to build the documentation

akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/HttpAppSpec.scala
Issue: #827 
Replace deprecated (and soon to be removed) `isTerminated` in `HttpAppSpec` with `whenTerminated`
=> Use whenTerminated instead of deprecated isTerminated #827

akka-http-tests/src/test/java/akka/http/javadsl/server/directives/ExecutionDirectivesTest.java, akka-http/src/main/scala/akka/http/javadsl/server/RejectionHandler.scala, docs/src/main/paradox/java/http/routing-dsl/rejections.md, docs/src/main/paradox/scala/http/routing-dsl/source-streaming-support.md, docs/src/test/java/docs/http/javadsl/server/RejectionHandlerExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala
Issue: #593
* Extend `RejectionHandler` to have `mapRejectionResponse`
* Add tests for it
* Documenation for Rejections adapted to Java APIs
* Fix code example for Scala docs
=> Provide Rejection Documentation #593

akka-http-core/src/main/scala/akka/http/javadsl/ConnectHttp.scala, akka-http-core/src/test/scala/akka/http/javadsl/ConnectHttpSpec.scala
This fixes #660 by bringing feature parity with the Scala API and also reworks `ConnectHttp` to improve how connection data is extracted.
Tested manually in the Scala REPL using the Java HttpApp:
```
> sbt akka-http/console
[info] Starting scala interpreter...
[info]
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_102).
Type in expressions for evaluation. Or try :help.
scala> :paste
// Entering paste mode (ctrl-D to finish)
import com.typesafe.config.ConfigFactory
import akka.http.javadsl.server.HttpApp
import akka.http.javadsl.settings.ServerSettings
object Server extends HttpApp {
protected override def route = complete("hi")
def run() = startServer("localhost", 0, ServerSettings.create(ConfigFactory.load()))
}
Server.run
// Exiting paste mode, now interpreting. …
```
=> Allow Java bind API to specify port zero (#660)

docs/src/main/paradox/java/http/index.md, docs/src/main/paradox/java/http/introduction.md
Issue: ##863
Information under `index.html` for Java documentation is a partial duplication of `introduction.html`.
Remove duplicated text.
Add missing dependency under `introduction.html`
=> Remove duplicated info from index. Add akka-http-jackson mdoule in intro

akka-http-core/src/main/mima-filters/10.0.3.backwards.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, docs/src/main/paradox/java/http/common/timeouts.md, docs/src/main/paradox/scala/http/common/timeouts.md
Under circumstances that I could not reproduce so far,
the AbsorbCancellation stage introduced in #459 may keep the graph running
if data was already buffered but never read. The reason is that the stage
so far requires completion to reach the stage after cancellation was
absorbed which might be blocked by incoming elements that were never
pulled.
The solution is two-fold. After cancellation:
1) pull in and ignore all incoming elements to eventually fetch completion
2) complete the stage after a configurable time
In the HTTP use case, we delay the cancellation by no more than the time specified
in the new linger-timeout setting.
=> =htc #851 fix leaking AbsorbCancellation

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpResponseParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/SpecializedHeaderValueParsers.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ContentLengthHeaderParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala
* Add tests verifying `\n` alongside `\r\n` in all modified parsers
* Duplicate specs to test either with `\r\n` and with `\n` (force to test in both cases for future developments)
=> As mentioned in #106, parsers should also accept LF end of line as good as CRLF.

akka-http-core/src/main/mima-filters/10.0.2.backwards.excludes, akka-http-core/src/main/mima-filters/10.0.3.backwards.excludes, akka-http-marshallers-scala/akka-http-spray-json/src/main/mima-filters/10.0.3.backwards.excludes, akka-http/src/main/mima-filters/10.0.3.backwards.excludes, project/MiMa.scala
Issue: #870
* Update MiMa to track 10.0.2 and 10.0.3
* Add exclusion files for akka-http-core, akka-http and akka-http-spray-json
=> Update MiMa to track 10.0.2 and 10.0.3 and update exclusions #870

akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Scaling the serverTimeout and resulting timeout made the test less stable and
caused at least one failure on AppVeyor with timefactor=1.5.
=> Remove .dilated from client-server connect close with idle timeout test

akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/HttpAppSpec.scala, akka-http/src/main/java/akka/http/javadsl/server/HttpApp.java, akka-http/src/main/scala/akka/http/scaladsl/server/HttpApp.scala, docs/src/main/paradox/java/http/routing-dsl/HttpApp.md, docs/src/main/paradox/scala/http/routing-dsl/HttpApp.md, docs/src/test/java/docs/http/javadsl/server/HttpAppExampleTest.java, docs/src/test/scala/docs/http/scaladsl/HttpAppExampleSpec.scala
Issue: #873 and #875
Provide start server with only host and port
Update docu
Make `HttpApp` for Scala API extend `Directives` (like Java one does)
=> Improve HttpApp usability #873 #875

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/PriorityTree.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/StreamPrioritizer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/util/AsciiTreeLayout.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/PriorityTreeSpec.scala
A first preview of the priority work:
* a first version of the priority tree to implement the rules from the spec (it works and is somewhat simple but is probably rather slow)
* a rewrite of the multiplexer with a proper state machine that sends control frames first and now has a single entry point for actually prioritizing substreams
=> Http2 multiplexer rewrite and plugable prioritizers

CONTRIBUTING.md
Issue: #899 
Link to github issue tracker instead to akka docs page in CONTRIBUTING
=> Fix link to issue tracker in CONTRIBUTING #899

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/PathDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/PathDirectives.scala
Fixes #878.
I'm not sure if it's the right way to do it - if you have any suggestions on how to make it better, please tell ;)
=> Avoid redirect loops when `redirectToNoTrailingSlashIfPresent` is used

akka-http-core/src/main/java/akka/http/javadsl/model/HttpEntities.java, akka-http-core/src/main/java/akka/http/javadsl/model/HttpEntity.java, akka-http-core/src/main/java/akka/http/javadsl/model/HttpMessage.java, akka-http-core/src/main/java/akka/http/javadsl/model/HttpMethod.java, akka-http-core/src/main/java/akka/http/javadsl/model/HttpMethods.java, akka-http-core/src/main/java/akka/http/javadsl/model/RemoteAddress.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/EntityTagRange.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/HttpEncodingRange.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/HttpOriginRange.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/LanguageRange.java, akka-http-core/src/main/scala/akka/http/impl/model/JavaInitialization.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala, akka-http/src/main/scala/akka/http/javadsl/server/RoutingJavaMapping.scala, project/Doc.scala
Update FIXMEs referring to Akka 3.x and Akka HTTP 10.x to refer to Akka
HTTP 11.x.
---
I suggest we also create a 11.x milestone ticket to ensure we remember to remove and rename related methods.
=> Update versions in FIXMEs and TODOs

akka-http-core/src/main/mima-filters/10.0.4.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterfaceActor.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ConnectionPoolSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala, akka-http-core/src/main/scala/akka/http/javadsl/ClientTransport.scala, akka-http-core/src/main/scala/akka/http/javadsl/Http.scala, akka-http-core/src/main/scala/akka/http/javadsl/OutgoingConnection.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ConnectionPoolSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/ClientTransport.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ConnectionPoolSettings.scala
For now, this is basically a refactoring of how the client-side graph is put together.
I had this already lying around for a while half-finished. Thought I could just finish it.
Java APIs are still missing.
Refs #916.
=> +htc #916 add pluggable Transport API to switch out client-side transport layer

akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala
Changes the type of `Content-Range` from `ResponseHeader` to `RequestResponseHeader`
=> Allow Content-Range to be used as a request header #932

akka-http/src/main/scala/akka/http/javadsl/server/directives/FramedEntityStreamingDirectives.scala, akka-parsing/src/main/scala/akka/parboiled2/DynamicRuleDispatch.scala, akka-parsing/src/main/scala/akka/parboiled2/Parser.scala, akka-parsing/src/main/scala/akka/parboiled2/support/OpTreeContext.scala, docs/src/test/scala/docs/http/scaladsl/HttpAppExampleSpec.scala
Mostly taking care of easy cases like deprecated methods that have known
alternatives.
The most noticeable change is the use of
```ctx.internal.enclosingOwner``` in the parboiled2 parser macro
I had be happy to dig deeper if some changes require more refactoring that first thought.
=> Remove a few compilation warnings #856

akka-http-core/src/main/mima-filters/10.0.4.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala
Before, the timeout kept referencing the stage which kept the whole
GraphInterpreter and indirectly the ActorGraphInterpreter referenced. The memory
was only freed after the timeout had triggered.
Fixes #945.
=> =htc #945 in StreamUtils.delayCancellation cancel timeout if stage was stopped otherwise

akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/Unmarshal.scala, docs/src/test/scala/docs/http/scaladsl/UnmarshalSpec.scala
Attempt to fix issue #78
As per the corresponding Gitter discussion, this PR will make ```Unmarshall#to``` use the execution context provided by the Materializer if none is provided implicitly.
=> Change `Unmarshal#to` to use a default context #78

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/BasicDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/BasicDirectives.scala
Use toStrictEntity so the request is updated to provide the strict
entity for inner routes ensuring that the request data is only read
once.
=> =htp #961 Make extractStrictEntity provide strict entity for inner routes

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpResponseParser.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala
Proposal for issue #981 that will allow to parse a non-standard
Http Response which does not contain a status message.
Example: 'HTTP/1.1 400' instead of 'HTTP/1.1 400 Bad Request'
=> Make Response parser more relaxed on reason message #981

akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaRange.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/ContentNegotiationSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/ContentNegotation.scala
https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1 describes how to interpret the Accept header during content negotiation.
Notably, it specifies "The media type quality factor associated with a given type is determined by finding the media range with the highest precedence which matches that type", and then gives some examples.
'matching' is implemented in akka-http in `MediaRange::matches`, but for `MediaRange.One` fails to take into account parameters.
'precedence' is implemented in akka-http when determining the sorting of `acceptedMediaRanges` in `MediaTypeNegotiator`, but for non-wildcard media types sorts by the qValue instead of by the number of parameters.
=> Use media type parameters in content negotiation (#963)

build.sbt
Used as default for the sbt prompt, IntelliJ project name, perhaps other things
=> Name root project 'akka-http-root'

akka-http/src/main/scala/akka/http/scaladsl/server/HttpApp.scala
Issue: #1034
Do not throw if promise is already completed when called by the JVM shutdown hook
=> Do not throw if promise is completed #1034

akka-http-tests/src/test/scala/akka/http/scaladsl/TestUtils.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala
* because they use finalize that is not gc friendly
* they were only used in tests, but good to stay away from them
anyway
Refs #1037
=> Replace FileInputStream and FileOutputStream, #1037

akka-http-core/src/main/mima-filters/10.0.5.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/RenderSupport.scala, akka-http-core/src/main/scala/akka/http/impl/util/Rendering.scala
Small scale buffer copies are faster than fine-grained chained ByteStrings.
=> =htc use ByteArrayRendering for response rendering

docs/src/test/scala/docs/http/scaladsl/server/directives/ParameterDirectivesExamplesSpec.scala
renames in `Repeated, deserialized parameter` example
city -> distance
cities -> distances
=> Copy-paste/naming error fixed

akka-http-tests/src/test/java/akka/http/javadsl/server/directives/ParameterDirectivesTest.java, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ParameterDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/ParameterDirectives.scala
This changes the behaviour so that rather than throwing an exception leading to an Internal Server Error, instead we reject with a `MalformedRequestContentRejection`. This is used instead of `MalformedQueryParameterRejection` as the parse failure doesn't give us information about the query parameter that led to the parse failure.
I hope the tests are sufficient, but I'm more than happy to add more if desired.
=> Handle failure while parsing the URI in parameter extraction #1043

akka-http/src/main/java/akka/http/javadsl/server/directives/ContentTypeResolver.java, akka-http/src/main/mima-filters/10.0.5.backwards.excludes, akka-http/src/main/scala/akka/http/javadsl/server/RoutingJavaMapping.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/FileAndResourceDirectives.scala
Resolves https://github.com/akka/akka-http/issues/360 .
The JavaMapping class assumes that all Java interfaces have
factory methods that only instantiate their Scala subclasses
from the scala DSL. That's not the case for ContentTypeResolver,
which is only a Java interface and a Scala trait. It's intended
to be implemented as a lambda / function.
However, when doing that from Java, the Scala trait is not
instantiated, upsetting the JavaMapping magic.
This commit changes ContentTypeResolver to no longer use the
JavaMapping conversion, but rather convert explicitly. By making
it a Java 8 functional interface, it can now be directly
implemented as a lambda. Binary compatibility is hopefully
unaffected, since the default method isn't slapped on until
actual Java implementations (which couldn't …
=> [WIP] #360 Allow Java-implemented ContentTypeResolver

akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteDirectives.scala
Issue: 641
`complete` directives take `ResponseEntity` as a parameter instead of `RequestEntity`
I think in next steps `Marshaller[T, RequestEntity]` should be replaced by `Marshaller[T, ResponseEntity]`. But it requires #642 first.
=> Complete directives take `ResponseEntity` as a parameter instead of `RequestEntity`

akka-http-core/src/main/java/akka/http/javadsl/model/RemoteAddress.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/EntityTagRange.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/HttpEncodingRange.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/HttpOriginRange.java, akka-http-core/src/main/scala/akka/http/scaladsl/model/RemoteAddress.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/EntityTag.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/HttpEncoding.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/HttpOrigin.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/LanguageRange.scala, akka-http-core/src/test/scala/akka/http/javadsl/JavaInitializationSpec.scala
The workaround added in 34bd3d9f1b50ac133896b9e73b47d9408a2bd033 to
ensure static fields in Java model classes inherited from Scala models
are initialized properly put the runtime patching on the enclosing Scala
object, however, it also changed the Java classes to redirect static
fields to the new API, which meant that the initialization hook was
never called.
To fix this problem move the initialization to the Scala object
referenced from the Java static field.
---
Note, it is possible to further clean up use of `JavaInitialization` and for example remove it from `HttpEntity.Empty` since it is defined as a `val` instead of `object`.
=> =htc #936 Fix NPE when access static Java constant fields

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/BufferedOutletSupport.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/model/http2/Http2Exception.scala
It's now in its own file and handle StreamFrameEvents depending on the state of a stream.
Refs #1064.
=> Refactor Http2 incoming-side stream state machine

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/RouteDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/Marshaller.scala
When using `Marshalling.oneOf`, in some situations each marshaller is actually executed before picking the most suitable result.
While indeed we can't avoid allocating a `Marshalling` for each `Marshaller` (that would need a wider overhaul as described in #243), the actual marshalling can still be lazy at that point (https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/marshalling/Marshaller.scala#L168).
It seems `Marshaller.compose` is forcing the early evaluation. This PR appears to confirm that, though it isn't obvious we can work that through without performing the ugly hacks in here.
=> [WIP] #1017 make marshaller composition more lazy

docs/src/main/paradox/java/http/routing-dsl/testkit.md, docs/src/main/paradox/java/http/server-side-https-support.md, docs/src/test/java/docs/http/javadsl/server/HighLevelServerBindFailureExample.java, docs/src/test/java/docs/http/javadsl/server/HighLevelServerExample.java
Issue: #1041
Remove mentions to old Spray HttpApp from docs.
Keep them for migration notes
=> Remove references to old HttpApp from docs #1041

akka-http-core/src/main/scala/akka/http/impl/model/parser/AcceptHeader.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/IllegalHeadersIntegrationSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RequestContext.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RequestContextImpl.scala
Resolves in 2 parts https://github.com/akka/akka-http/issues/1072
One is to avoid infinite retrying by refining what a real wildcard actually is.
Two is to ignore weird media types in the form of `*/wat`
=> Fix weird MediaType parsing (Don't panic its only a weird media range)

docs/src/main/paradox/java/http/common/http-model.md, docs/src/main/paradox/scala/http/common/http-model.md
Fixes #1099
uri-model.md already has the same sections. ("Obtaining the Raw Request URI" is not right next to "The URI model", but in the middle of the page)
http://doc.akka.io/docs/akka-http/10.0.6/java/http/common/uri-model.html
http://doc.akka.io/docs/akka-http/10.0.6/scala/http/common/uri-model.html
=> Remove duplicated doc sections

project/OSGi.scala
Addresses issue #1097 so that the Import-Package for `akka` packages are generated from the current dependent version up to, but not including, the next major version.
For example, `[2.4.17, 3.0.0)`
=> Modify OSGi header range of akka imports to upper limit of next major version (fix #1097)

akka-http-tests/src/test/java/akka/http/javadsl/server/MinimalHttpApp.java, akka-http-tests/src/test/scala/akka/http/scaladsl/server/HttpAppSpec.scala, akka-http/src/main/java/akka/http/javadsl/server/HttpApp.java, akka-http/src/main/mima-filters/10.0.6.backwards.excludes, akka-http/src/main/scala/akka/http/scaladsl/server/HttpApp.scala, docs/src/main/paradox/java/http/migration-guide/index.md, docs/src/main/paradox/java/http/migration-guide/migration-within-10.0.x-Api-May-Change.md, docs/src/main/paradox/java/http/routing-dsl/HttpApp.md, docs/src/main/paradox/scala/http/migration-guide/index.md, docs/src/main/paradox/scala/http/migration-guide/migration-within-10.0.x-Api-May-Change.md, docs/src/main/paradox/scala/http/routing-dsl/HttpApp.md, docs/src/test/java/docs/http/javadsl/server/HttpAppExampleTest.java, docs/src/test/scala/docs/http/scaladsl/HttpAppExampleSpec.scala
Issue: #953
Provide routes method in HttpApp
Deprecate route mothod in HttpApp
Use the new method in tests and docs
Update docs
HttpApp still uses the route method internally to ease the update
=> Provide routes method in HttpApp #953

build.sbt
The regression was introduced in ffd69f87ac1a18a393fff28be285ef7989cd2c32.
=> Fix akka-docs extref to expand the akka version sbt setting

akka-http-core/src/main/scala/akka/http/impl/model/parser/CommonRules.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
RFC 1123 Section 5.2.14 defines the grammar for dates as:
date = 1*2DIGIT month 2*4DIGIT
=> =htc #1110 Parse RFC 1123 dates with single digit day and double digit year

docs/src/main/paradox/scala/http/routing-dsl/testkit.md, docs/src/test/scala/docs/http/scaladsl/server/FullSpecs2TestKitExampleSpec.scala
Makes it easier to see the two supported test frameworks. Adjust the
specs2 imports and formatting to make it similar to the ScalaTest
version.
Extracted from #1125
---
=> =doc Show scalatest and specs2 testkit examples using tabs

akka-http-core/src/main/mima-filters/10.0.6.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpAttributes.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/impl/util/StreamUtilsSpec.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/AlpnSwitch.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Quick impl of https://github.com/akka/akka-http/issues/1088
We forgot to propagate headers to the ALPN "switched to" server graph.
This is not cleaned up, impled quickly before leaving home today, if you have suggestions where to "pass around" the headers let me know, I marked some TODOs. The Parsing is a method now, now a GraphStage so it has to get it passed in (it can't just reach for the attributes), I don't mind this style I guess, but wonder if there would be a cleaner way
Resolves https://github.com/akka/akka-http/issues/1088
=> +h2 #1088 include RemoteAddress in ALPN switched to server

project/Dependencies.scala
When akka-http was migrated from the akka repo the original
project/Dependencies.scala file was copied more or less verbatim. Remove
dependencies that are not used by the akka-http components to reduce
clutter.
=> =pro Remove unused dependencies copied from Akka import

docs/src/main/paradox/java/http/introduction.md, docs/src/main/paradox/java/http/migration-guide/index.md, docs/src/main/paradox/java/http/migration-guide/migration-guide-10.0.x.md, docs/src/main/paradox/scala/http/introduction.md, docs/src/main/paradox/scala/http/migration-guide/index.md, docs/src/main/paradox/scala/http/migration-guide/migration-guide-10.0.x.md, docs/src/main/paradox/scala/http/routing-dsl/directives/custom-directives.md
Change `AkkaHttp` to `HttpApp` in the migration guide. I also took the liberty to rename the file to better match the others, the title remains the same.
=> Fix 10.0.x migration guide

docs/src/main/paradox/java/http/introduction.md, docs/src/main/paradox/release-notes.md, docs/src/main/paradox/scala/http/introduction.md
Point to the new g8 seed templates as a way to bootstrap a new Akka HTTP
sbt project.
As discussed in #1150.
---
Motivated by https://github.com/akka/akka-http/pull/1150#issuecomment-303685068
/cc @ktoso @jlprat
=> Mention Giter8 templates in the introduction

docs/src/main/paradox/java/http/client-side/client-https-support.md, docs/src/main/paradox/java/http/common/de-coding.md, docs/src/main/paradox/java/http/common/http-model.md, docs/src/main/paradox/java/http/common/marshalling.md, docs/src/main/paradox/java/http/common/unmarshalling.md, docs/src/main/paradox/java/http/routing-dsl/rejections.md, docs/src/main/paradox/java/http/server-side/low-level-server-side-api.md, docs/src/main/paradox/scala/http/client-side/client-https-support.md, docs/src/main/paradox/scala/http/common/de-coding.md, docs/src/main/paradox/scala/http/common/http-model.md, docs/src/main/paradox/scala/http/common/json-support.md, docs/src/main/paradox/scala/http/common/marshalling.md, docs/src/main/paradox/scala/http/common/unmarshalling.md, docs/src/main/paradox/scala/http/common/xml-support.md, docs/src/main/paradox/scala/http/low-level-server-side-api.md, docs/src/main/paradox/scala/http/routing-dsl/directives/coding-directives/decodeRequest.md, docs/src/main/paradox/scala/http/routing-dsl/directives/coding-directives/requestEncodedWith.md, docs/src/main/paradox/scala/http/routing-dsl/directives/custom-directives.md, docs/src/main/paradox/scala/http/routing-dsl/exception-handling.md, docs/src/main/paradox/scala/http/routing-dsl/rejections.md, docs/src/test/scala/docs/http/scaladsl/server/directives/CodingDirectivesExamplesSpec.scala
Also fixes a broken snippet: http://doc.akka.io/docs/akka-http/10.0.7/scala/http/routing-dsl/directives/coding-directives/decodeRequest.html#decoderequest
=> Link to javadoc and scaladoc instead of files on GitHub

akka-http-core/src/main/mima-filters/10.0.7.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/model/parser/ContentTypeHeader.scala, akka-http-core/src/main/scala/akka/http/javadsl/model/ContentType.scala, akka-http-core/src/main/scala/akka/http/javadsl/model/MediaType.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/ContentType.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala, akka-http-core/src/test/scala/io/akka/integrationtest/http/HttpModelIntegrationSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/MultipartUnmarshallersSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/UnmarshallingSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/Marshal.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToResponseMarshallers.scala, docs/src/main/paradox/release-notes.md
The text/xml content-type (and possibly others) is best used with a
charset parameter, and akka inforces this on the type level. That's
great practice, but _incoming_ requests can certainly have a
Content-Type header of "text/xml" without a charset. Akka currently
just blindly adds "UTF-8", which is incorrect and a potential problem.
This commit adds a specific type to the ContentType hierarchy to represent
"a media type that should have had a charset but didn't".
=> Fix #1134: Create representation of Content-Type with missing charset

docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala
The code listing shown in Customizing Rejection Handling can't be
compiled as is, because the implicit def is defined outside any class or
object. Move it into the MyApp object so it compiles stand-alone.
=> Fix #1172: Move rejection handler into the example App object

akka-http2-support/build.sbt, project/Version.scala
The upgrade to sbt 0.13.15 allows us to drop use of `.taskValue` for
generators.
=> Drop use of .taskValue from sbt generators

akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
I agree with Johannes that the only code path to this failure is when the
parboiled dispatcher would throw `RuleNotFoundException`, but don't see how
this could be nondeterministic. To further narrow this down I added a test that
fails specifically in that case, should be interesting to see if that one also
fails (and whether they fail together).
Refs #443
=> Add extra test to narrow down failure #443

akka-http-core/src/main/mima-filters/10.0.7.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/settings/ClientConnectionSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ConnectionPoolSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/ClientTransport.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ClientConnectionSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/ClientTransport.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ClientConnectionSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/ByteStringSinkProbe.scala
This was inspired by part of @ktoso's fix in #1014 but goes a bit further to simplify the transport API.
A transport is now a static constant function value that gets passed
all parameters at connection time.
That fixes #1012 where client connection settings were both kept redundantly
inside the transport and inside the settings.
It's now also possible to specify the localAddress inside the settings. Methods
in the Http entrypoint that allow specifying the localAddress explicitly will
override whatever was given in the settings. In the future we'd like to
get rid of all those parameters to simplify entrypoint signatures in Http.
There is a basic disadvantage of passing `ClientConnectionSettings` to the `connectTo` method which is that whatever settings future `ClientTransport` come up …
=> Revamp SPI / API of ClientTransport infrastructure to fix #1012 and to simplify API

akka-http-core/src/main/mima-filters/10.0.7.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/model/parser/CharacterClasses.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala, akka-http-core/src/test/java/akka/http/javadsl/model/UriTest.java, akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala, akka-http-tests/src/test/java/akka/http/javadsl/server/directives/ParameterDirectivesTest.java, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ParameterDirectivesSpec.scala, docs/src/main/paradox/java/http/common/uri-model.md
* Create new character class for query value chars and use this in relaxed mode
* Update relevant tests and examples to reflect this change
Fixes #1120
=> Allow '=' in query param values in relaxed mode (Fix #1120)

akka-http-tests/src/test/java/akka/http/javadsl/server/MinimalHttpApp.java, akka-http-tests/src/test/scala/akka/http/javadsl/server/HttpAppSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/HttpAppSpec.scala
Issues: #1121 #1061
Refactor test to avoid race condition between serving a request and shutting down the server itself.
Now, server is shutdown independently from serving a request.
=> =httst Improve test reliability for HttpApp #1121 #1061

akka-http-core/src/main/mima-filters/10.0.7.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/client/HttpsProxyGraphStage.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/BodyPartParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocketClientBlueprint.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala
Attempted fix to issue #1166. 
Changed HttpHeaderParser such that by default illegal header value handling depends on the configured IllegalResponseHeaderValueProcessingMode.
A couple of problems:
First, I'm not sure how I should handle an unexpected value [here](https://github.com/disblader/akka-http/blob/websocket-illegal-headers/akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala#L452). Is there an exception that implementors generally use for these kinds of situations?
Secondly, I'm pretty bad with scalatest and I ended up in [this situation](https://github.com/disblader/akka-http/blob/websocket-illegal-headers/akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala#L194-L201) where I have identical tests with different …
=> Websocket illegal headers #1166 

akka-http-core/src/main/scala/akka/http/scaladsl/model/ContentType.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/UnmarshallingSpec.scala
This scenario was overlooked in #1141, because jm.ContentType isn't a
sealed trait (and can't be, because it is implemented in the scala DSL).
Fixes #1222.
=> #1222 Correctly handle ContentType.withMissingCharset in ContentTypeRange

akka-http/src/main/scala/akka/http/javadsl/server/directives/MiscDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/MiscDirectives.scala, docs/src/main/paradox/java/http/routing-dsl/directives/misc-directives/withoutSizeLimit.md, docs/src/main/paradox/scala/http/routing-dsl/directives/misc-directives/withoutSizeLimit.md
Issue: #814
Add Warning and note on Scala/Java Doc so people see the risks of using withoutSizeLimit
=> =docs add discouragement to use withoutSizeLimit in docs #814

akka-http-core/src/main/java/akka/http/javadsl/model/StatusCodes.java, akka-http-core/src/main/scala/akka/http/scaladsl/model/StatusCode.scala
Added support for status code 418 according to https://tools.ietf.org/html/rfc2324
=> Add HTTP status code 418

akka-http-core/src/main/scala/akka/http/scaladsl/model/ContentType.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/UnmarshallingSpec.scala
Follow up for #1223 to actually test the behavior that the unmarshaller will match a `WithMissingCharset` content-type and assume UTF-8.
/cc @jypma
=> =htt #1222 improve test case to test fixed behavior

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpResponseParser.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala
Fixed #1251 and updated tests to use non-default status code
=> HttpResponseParser - add parsing for status codes without reason (#1251)

docs/src/test/scala/docs/http/scaladsl/RouteSealExampleSpec.scala
Which in turn would hang the entire test suite
=> The scaladsl route seal example was leaking an actor system

docs/src/main/paradox/scala/http/client-side/client-transport.md
The HTTPS proxy client implementation that uses HTTP CONNECT could in
theory also be used for proxy'ing to HTTP endpoints, but we haven't
found an implementation that in fact allows this yet.
Refs #1228
=> Document HTTP CONNECT could support HTTP endpoints

RELEASING.md
I thought it might be a good idea to communicate the intention to release a new version on the Gitter Akka Dev Channel, so nobody is merging unexpected Pull Requests.
=> Add release step to communicate merge halt before releasing

akka-http-core/src/main/java/akka/http/javadsl/model/headers/CacheDirectives.java, akka-http-core/src/main/scala/akka/http/impl/model/parser/CacheControlHeader.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/CacheDirective.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
Hi,
after reading [this](https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/ ) a while ago I thought that the `immutable` Cache-Control value might be a good addition and so I created this PR.
Let me know what you think.
Best,
Matthias
See also
- https://bitsup.blogspot.de/2016/05/cache-control-immutable.html
- https://tools.ietf.org/wg/httpbis/draft-ietf-httpbis-immutable/
=> adds Cache-Control 'immutable' value

akka-http-core/src/main/scala/akka/http/scaladsl/model/Uri.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala
While I couldn't find any saying in RFC3986, I think this is better than using the reverse order.
See playframework/playframework#7567
=> Preserve the order of repeated parameters when retrieving query string as a multimap

docs/src/main/paradox/scala/http/release-notes.md
Small mistake, added new feature description in wrong version
=> =doc release-notes move proxy auth to right version

akka-http-core/src/main/scala/akka/http/impl/engine/client/HttpsProxyGraphStage.scala
This was my mistake while amending polishing up the Auth support in the stage.
Double \r\n is ofc needed at end of http message.
Resolves https://github.com/akka/akka-http/issues/1319
=> =htc #1319 fix missing \r\n (to get double) in HttpProxy stage CONNECT

docs/src/main/paradox/java/http/client-side, docs/src/main/paradox/java/http/client-side/client-https-support.md, docs/src/main/paradox/java/http/client-side/client-transport.md, docs/src/main/paradox/java/http/client-side/connection-level.md, docs/src/main/paradox/java/http/client-side/host-level.md, docs/src/main/paradox/java/http/client-side/index.md, docs/src/main/paradox/java/http/client-side/pool-overflow.md, docs/src/main/paradox/java/http/client-side/request-level.md, docs/src/main/paradox/java/http/client-side/websocket-support.md
After @jlprat 's hard work to unify the client-side docs let's reduce the link clutter.
References #1290
=> =doc #1290 Link client-side docs at the directory level

akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolGateway.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterfaceActor.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala
Previously, a shutdown request didn't check if there are outstanding
requests so that outstanding responses were just lost.
This is still missing tests, but I haven't been able to reproduce it reliably. The reason is that there's only a short time frame where you can hit the race, i.e. while the scheduled `gateway.shutdown` is dispatched through `PoolMasterActor` to `PoolInterfaceActor` a new request must come in.
=> =htc #1245 fix pool idle-timeout race condition

docs/src/test/scala/docs/http/scaladsl/server/directives/FileAndResourceDirectivesExamplesSpec.scala
with '/', it is not working at lastest version (2.11 / 10.0.9)
=> remove '/' from getFromResourceDirectory example

akka-http-core/src/main/mima-filters/10.0.9.backwards.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/Http2ServerSettings.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/ByteStringSinkProbe.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/IncomingFlowController.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/scaladsl/Http2ServerTest.scala
The tests pass but the code is not yet in its final shape. A few constants need to be converted to configuration values. There's currently only a simplistics strategy of sending out WINDOW_UPDATE frames. It is configured with maximum values for connection-level and stream-level windows. When outstanding + buffered data falls below half the maximum configured number it sends out a WINDOW_UPDATE frame to the peer.
I think there are a few hard flow-control problems that cannot be easily solved (but putting it in strategies should help experimenting with other ones):
* If `max-stream-level-window * num_connections > max-connection-level-window`, there can be head-of-line blocking between streams. Since this is only for uploads, it doesn't seem to be a serious concern for now, the client can …
=> Http2 inbound flow control

akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala, akka-http-core/src/test/scala/akka/http/impl/util/CollectionStage.scala
The idea is to provide a stage / API that allows to find out the result
of running elements through a flow. The race condition previously was that
finding out whether the flow was completed could only be observed by waiting
for some amount of time.
This adds a new test utility stage that injects an event into the mailbox
of the ActorGraphInterpeter (via AsyncCallback) which is hoped to be only
processed after all internal events have been processed. This seems to work
reliably as long as the complete flow is fused and synchronous and the whole
processing needs less events than the event queue processes in one go.
Fixes #864
=> =htc #864 fix race condition in ResponseRendererSpec

akka-http-core/src/main/mima-filters/10.0.0.backwards.excludes, project/MiMa.scala, project/build.properties, project/plugins.sbt
*This PR uses a not yet released feature (https://github.com/typesafehub/migration-manager/pull/174) from sbt MiMa plugin where it is able to load mima filters from files like in akka-http.*
*EDIT: it now uses a new version of MiMa 0.1.15 and can be merged.*
Sbt MiMa now knows how to load issue filters from file. Also there is now support for wildcards in FQCN in filter definitions, so no custom filters needed anymore.
=> Move MiMa issue loading from file to sbt mima plugin

akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/Uri.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala
Fixes #1274 and a number of issues in https://tools.ietf.org/html/rfc7540#section-8.1.2. The most important other fix for users is support for `cookie` header compression. The other changes are mostly around stricter validation of pseudo-header fields.
I've finished this PR up to a level where I'm reasonably happy, but I would appreciate a preliminary review. I've also got some questions (marked `// QUESTION` in the source) that I'd be interested in your thoughts on.
I added a new test, `RequestParsingSpec`, that mirrors RFC7540 closely so we can see which where we're spec compliant and where we're not. We may not want to be completely spec compliant—e.g. we may want to accept some non-compliant paths—but I think it's useful to see where we deviate from the spec anyway so we can at least …
=> Improve HTTP/2 request parsing

docs/src/main/paradox/scala/http/common/uri-model.md
I think this corrects some typos, but please correct me if there is actually a type `URI` rather than `Uri`.
=> Change URI to Uri

docs/src/main/paradox/scala/http/handling-blocking-operations-in-akka-http-routes.md
This section has moved to the "Dispatchers" page in the latest version of the Akka documentation.
=> Fix the "Blocking needs careful management" link

akka-http-core/src/main/mima-filters/10.0.10.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/HeaderParser.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpHeader.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
Before every attempt to parse an unknown (i.e. not modeled) header would
end up in throwing and catching an exception. This does not really make
sense as parboiled already provides for delivering these signals without
an exception.
Refs playframework/playframework#7822
=> =htc replace usage of `RuleNotFoundException` by introducing explicit result ADT

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MiscDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala
Fix for https://github.com/akka/akka-http/issues/1341
Actual behavior:
`withSizeLimit` in combination with `formFieldMap` directive responds with NotFound status code when a size of FormData exceeds the limit.
Expected behavior:
The combination of these directives should respond with BadRequest in a case of too large FormData, as it is implemented for too large Entity.
In order to fix this, handling of `EntityStreamSizeException` was added to  `FormFieldDirectives`.
=> Reject request if form data exceeds limit defined in withSizeLimit directive

akka-http-core/src/main/java/akka/http/javadsl/model/headers/XForwardedHost.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/XForwardedProto.java, akka-http-core/src/main/scala/akka/http/impl/model/parser/HeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/SimpleHeaders.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala
Refs: #1377
This PR adds support for the _de facto_ standard headers:
- `X-Forwarded-Host`
- `X-Forwarded-Proto`
=> +htc Add X-Forwarded-Proto and X-Forwarded-Host #1377

docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/CaseClassExtractionExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/DirectiveExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala
With paradox code lines from snippets are being hidden by adding anything that starts with `#` to the line (see [here](https://github.com/lightbend/paradox/issues/157)). This fixes the issue where these non-informative lines where being included in code snippets like [here](https://doc.akka.io/docs/akka-http/10.0.10/scala/http/routing-dsl/case-class-extraction.html).
=> Hide non-informative lines from snippets

project/Dependencies.scala
- jackson 2.8.8 -> 2.9.1
- akka 2.5.4 -> 2.5.6
- cross Scala 2.12.2 -> 2.12.3
- scala test 3.0.3 -> 3.0.4
- specs2 3.8.6 -> 3.9.5
=> Dependency updates

akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/RouteTest.scala
=> Issue #1271 - Provide Dilated Timeouts for Java Testkit.

CODE_OF_CONDUCT.md, CONTRIBUTING.md
We've introduced it in Akka, to be on par with other Lightbend projects which have them already some time ago. Adding it here since Akka HTTP abides to the same guidelines.
The full rationale is:
In order to strengthen the welcoming nature of our community.
Please note that this addition is not in direct reaction to any specific incident; we've been blessed with a very nice and polite community, and have in the past handled a few situations without having to call out a rule set like this - thank you everyone :-) However, we do think stating it explicitly will make more people confident and comfortable in participating in our community - similarly as Scala and Play have done in their communities. It will also show up in the github community tab https://github.com/akka/akka/community and …
=> Include Akka's CoC

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpAttributes.scala, akka-http-core/src/main/scala/akka/http/javadsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/ClientCancellationSpec.scala, akka-http-core/src/test/scala/akka/http/javadsl/HttpExtensionApiSpec.scala
It seems we had lots of these left over I guess from the early days where creating substreams required materializers to be passed. It seems no one cleaned that up so far. The changes were somewhat big to keep binary compatibility at least for a while. In Scala, it's binary and source compatible (if the materializer was passed implicitly). Java users need to remove the materializer argument.
Going forward, if we deprecate the old methods now and release another 10.0.x in October, we might think about cleaning those methods up for 10.1.0.
=> In top-level API don't require materializer where it's just ignored afterwards

akka-http-core/src/main/java/akka/http/javadsl/model/HttpEntity.java, akka-http-core/src/main/java/akka/http/javadsl/model/HttpMessage.java, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
Fixes #1430 
Adds a small paragraph to `HttpEntity.discardBytes` and `HttpMessage.discardEntityBytes` that clarifies the different behaviour for `Strict` entities.
Tried to follow the tone and wording in other Scaladocs in the same files for consistency.
=> Clarify discarding for strict entities #1430

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/HeaderParser.scala, akka-parsing/src/main/scala/akka/parboiled2/DynamicRuleDispatch.scala
Another small improvement as a follow up to #1424.
Previously, every header parsing attempt had to go through the
`DynamicRuleDispatch`, a binary search to find the parsing rule for an
HTTP header name.
However, the `HttpHeaderParser` already has a parsing tree that with a node
for every header name.
This change divides header parsing into two steps: looking up the rule
and invoking the parser. Looking up the rule now only needs to be once
per node in the `HttpHeaderParser` and afterwards it can just run
without going through the dispatch.
=> =htc lookup predefined header parsers as early as possible

docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala
- Moved the code inside the MyApp object, it compiles fine with Paradox due to encapsulating object, but looks broken in the docs.
=> Moved exception handler code in example

docs/src/main/paradox/scala/http/compatibility-guidelines.md
Adding  the "com.typesafe.akka" %% "akka-http-testkit" in test scope in your project, automatically add the akka-stream-testkit transitional dependency, but the version 2.4
To avoid, it is necessary to add the right version for this library.
=> Note about same issue using the testkit libraries.

akka-http/src/main/scala/akka/http/scaladsl/common/StrictForm.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala
We now don't allow customizing what and how a form is interpreted any more (which no one should have customized so far anyway).
On the other hand, implicit resolution is now simpler and less error-prone and probably also faster for most `formField` usages.
Old implicit definitions are kept for now for binary compatibility.
=> Simplify formField implicits a bit #541

docs/src/main/paradox/java/http/server-side, docs/src/main/paradox/java/http/server-side/http2.md, docs/src/main/paradox/java/http/server-side/low-level-api.md, docs/src/main/paradox/java/http/server-side/server-https-support.md, docs/src/main/paradox/java/http/server-side/websocket-support.md
Since all server-side documents are now shared between Java and Scala we can link the Java version at the directory level.
=> =doc Link Java server-side docs at the directory level

akka-http2-support/build.sbt, build.sbt, project/Dependencies.scala, project/Doc.scala, project/MultiNode.scala, project/ParadoxSignatureDirective.scala, project/ValidatePullRequest.scala, project/VersionGenerator.scala, project/Whitesource.scala, project/build.properties, project/plugins.sbt
Fixes #1434.
Includes the unidoc update changes from #925 which was reverted in #940 since it broke the  integrated build with akka/akka.
`sbt-jol` is removed based on https://github.com/akka/akka-http/issues/1434#issuecomment-331334611
=> Update build to use sbt 1.0

docs/src/main/paradox/java/http/server-side, docs/src/main/paradox/java/http/server-side/index.md
When #1371 was merged it broke the directory level symlink of the
server-side docs. Restore the symlink so the java doc group works
correctly.
CC @ktoso
=> Fix server-side doc link

akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/CacheDirective.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/HttpCookie.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/LinkValue.scala
* Updated comments in CacheDirective to be scaladocs
* Updated comments in HttpCookie to be scaladocs
* Updated comments in LinkValue to be scaladocs
=> Change comments in CacheDirective to scaladoc #1514

docs/src/test/java/docs/http/javadsl/server/directives/CachingDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/CachingDirectivesExamplesSpec.scala
The create cache tests demonstrate that if we set a small max capacity
(say 50 entries) and make more than that amount of unique requests and
finally redo the initial request then a new cache entry should be
generated. That is the entry of the initial request has been evicted and
regenerated.
The problem is that the LFU-cache implementation does not guarantee when
eviction happens. It might happen at next write time or as we clearly
see in #1541 at some later convenience. As a workaround bump the number
of requests to be much higher.
=> =doc Fix #1541: Bump number of unique requests to 500

project/Dependencies.scala
Caffeine has a dependency on com.google.code.findbugs:jsr305:3.0.2 which
is marked provided. Without explicitly adding this the build fails for
Scala 2.12.4.
---
Refs #1542
=> =cache Fix #1542: Add dependency on JSR305 JAR

docs/src/main/paradox/java/http/routing-dsl/index.md, docs/src/main/paradox/java/http/routing-dsl/overview.md, docs/src/main/paradox/scala/http/common/index.md, docs/src/main/paradox/scala/http/implications-of-streaming-http-entity.md, docs/src/main/paradox/scala/http/introduction.md, docs/src/main/paradox/scala/http/routing-dsl/routes.md, docs/src/main/paradox/scala/http/server-side/index.md
Revert most of 6f0634068c8cb91968bf0214aaf2a900498df0fa so links
inside consolidated documentation pages are language agnostic.
=> =doc Change server side links to not be Scala specific

akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala
Refs #1560
It appears in a previous JRE version(?) `jar.getInputStream` would
fail for directories, while now an explicit check is needed.
We could even argue opening the input stream is no longer needed
at all, why did we not simply check `isDirectory` before?
=> Explicitly check if a resource is a dir

akka-parsing/src/main/scala/akka/parboiled2/DynamicRuleDispatch.scala
Updated version of #1202 after #1428. Might not be as relevant anymore? But
replacing the macro-binary-search with a HashMap still makes the code a bit
simpler.
=> Use hashmap instead of binary tree of parsers

docs/src/test/java/docs/http/javadsl/server/directives/CachingDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/CachingDirectivesExamplesSpec.scala
Eviction is probabilistic in caffeine's LFU cache, so simple deterministic
tests are likely to fail now and then.
Fixes #1563.
=> =doc #1563 remove eviction tests from caching example specs

akka-http/src/main/scala/akka/http/javadsl/marshalling/Marshaller.scala
...to improve the Java DSL for two Marshallers (see #1551)
=> added Marshaller.oneOf(m1, m2) to JavaDSL (#1551)

akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/Uri.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala
Follow up to #1559.
The third commit just reenables code formatting for UriParser.scala. Can be ignored for reviewing.
Fixes #1558.
=> Percent decode userinfo while parsing URIs (#1558)

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/test/scala/akka/http/scaladsl/settings/ConnectionPoolSettingsSpec.scala
This way the defaults from akka.http.client automatically apply.
Fixes #1492.
=> =htc #1492 remove duplicate settings from akka.http.host-connection-pool.client

akka-http/src/main/mima-filters/10.0.10.backwards.excludes, akka-http/src/main/scala/akka/http/scaladsl/coding/Deflate.scala, akka-http/src/main/scala/akka/http/scaladsl/coding/Gzip.scala, docs/src/main/paradox/scala/http/release-notes.md
The idea is to replace the handlers in `DecompressorParsingLogic` with simple parameters of the `Inflate` step.
=> =htc simplify decompressor/deflate infrastructure

akka-http-core/src/main/scala/akka/http/scaladsl/util/FastFuture.scala
Also this PR fixes one TODO with creating exception with suppressed stack trace:
if (pred(r)) future
else throw new NoSuchElementException("Future.filter predicate is not satisfied") // FIXME: avoid stack trace generation
NOTE: I am not sure how to properly name this exception.
=> Add NoSuchElementException without stack trace being filled in

akka-http-core/src/main/mima-filters/10.0.10.backwards.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolFlow.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterfaceActor.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ConnectionPoolSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ConnectionPoolSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ConnectionPoolSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
At this point all old tests are passing (though the new pool is not yet enabled yet. The new pool has the same interface as the old one. It can be swapped in by replacing
```scala
val poolFlow = PoolFlow(connectionFlow, settings, log).named("PoolFlow")
```
with 
```scala
val poolFlow = HostConnectionPool(connectionFlow, settings, log).named("PoolFlow")
```
in PoolInterfaceActor, here:
https://github.com/akka/akka-http/blob/50a9d327b96302d38aca4178f22e9bcd75931def/akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterfaceActor.scala#L98-L102
The idea is to make it configurable for a bit of time to let it mature.
I haven't implemented the new and interesting features like better timeout, reporting, etc yet.
I don't consider this PR ready yet. I'd like to fill in a few more new …
=> #1312 Rewrite of PoolFlow / PoolSlot / PoolConductor as single GraphStage

docs/src/main/paradox/scala/http/release-notes.md
Also update links to older announcements to go directly to the blog post
instead of via a redirect.
=> Fix link to the 10.0.11 announcement

akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
Couldn't reproduce the exact issue but NPE in this line
serverConnections.ref ! connection
is most likely to be caused by an initialization issue.
Fixes #1592.
=> =htc #1592 fix NPE during text execution leading to spurious test failures

akka-http-core/src/main/scala/akka/http/scaladsl/model/Uri.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala
* Add percent encoding length check at Uri.decode. Bcause
StringIndexOutOfBoundsException raises when Uri.Path call by illegal
format(ex. %AA%, %AA%1).
* Add test case
=> Adding percent encoding length check for Path.Uri #1553

docs/src/main/paradox/scala/http/release-notes.md
HTTPS link instead of plain HTTP one.
=> =doc Link to https for announcement link in release notes

docs/src/main/paradox/scala/http/routing-dsl/testkit.md
The original requirement is from https://github.com/akka/akka-http-quickstart-scala.g8/issues/13.
I think it could be useful for external sites to link this table of inspectors directly. Thanks! :)
=> Add markdown heading.

docs/src/main/paradox/scala/http/routing-dsl/path-matchers.md
A very minor thing. While reading the doc I found this, I think it's a typo.
=> Fix typo in path

akka-http-core/src/main/scala/akka/http/javadsl/ConnectionContext.scala
It seems something prevented merging the "Java API" docs with the deprecation
docs leading to compilation errors during javadoc generation.
=> =htc #1614 fix genjavadoc generation

akka-http-core/src/main/java/akka/http/javadsl/model/headers/RetryAfter.java, akka-http-core/src/main/scala/akka/http/impl/model/parser/HeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/SimpleHeaders.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/RetryAfterParameter.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala
* Add the class and companion to the headers
* Create the corresponding java class
* Add case in the HeaderParser and SimpleHeaders
* Create test cases
Note: the current commit won't pass the HttpHeaderSpec, for reasons still
under investigation.
=> Http header retry-after #1554

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/DontLeakActorsOnFailingConnectionSpecs.scala
Still does not succeed reliably, but a starting point for further work
=> Run DontLeakActorsOnFailingConnectionSpecs against new client pool + fix unexpected connection signal reception

docs/src/main/paradox/scala/http/routing-dsl/index.md, docs/src/main/paradox/scala/http/routing-dsl/path-matchers.md, project/plugins.sbt
Refs #1290
Needs a paradox with https://github.com/lightbend/paradox/pull/170 to remove scala-specific elements from
the indexes
=> Consolidate routing-dsl index

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
* no unbounded response buffers, in a code comment I previously speculated whether buffering would be ok or not. I figured, probably unbounded buffering is not so cool so I removed it. Now the outgoing result is buffered in the slot until it is fetched
* some additional failure handlers
=> A few pool improvements

docs/src/main/paradox/java/http/contributing.md, docs/src/main/paradox/java/http/extensions.md, docs/src/main/paradox/java/http/reference.md, docs/src/main/paradox/java/http/technologies.md, docs/src/main/paradox/java/http/tipsandtricks.md, docs/src/main/paradox/java/http/usage.md, docs/src/main/paradox/scala/http/client-side/index.md, docs/src/main/paradox/scala/http/common/index.md, docs/src/main/paradox/scala/http/common/timeouts.md, docs/src/main/paradox/scala/http/contributing.md, docs/src/main/paradox/scala/http/extensions.md, docs/src/main/paradox/scala/http/index.md, docs/src/main/paradox/scala/http/introduction.md, docs/src/main/paradox/scala/http/reference.md, docs/src/main/paradox/scala/http/release-notes/index.md, docs/src/main/paradox/scala/http/routing-dsl/index.md, docs/src/main/paradox/scala/http/routing-dsl/overview.md, docs/src/main/paradox/scala/http/routing-dsl/routes.md, docs/src/main/paradox/scala/http/security.md, docs/src/main/paradox/scala/http/server-side/index.md, docs/src/main/paradox/scala/http/server-side/low-level-api.md, docs/src/main/paradox/scala/http/server-side/server-https-support.md, docs/src/main/paradox/scala/http/server-side/websocket-support.md, docs/src/main/paradox/scala/http/technologies.md, docs/src/main/paradox/scala/http/tipsandtricks.md, docs/src/main/paradox/scala/http/usage.md
Refs #436 
The idea is to start restructuring the top-level TOC to give the most important topics the best spots. The "chapter numbers" are mostly a cosmetic feature that feels to give the docs an ordered appearance (and hopefully prevents adding more entries lightly). I also added some other smaller "features".
=> #463 Restructuring of documentation TOC

docs/src/test/java/docs/http/javadsl/server/directives/FutureDirectivesExamplesTest.java
Perhaps gives a more useful error message for #1063, which I haven't been able
to reproduce locally
=> Check the entity body first

akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolFlow.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
Likely the bug happened in the Idle state. That's the one state that
didn't explicitly close the connection when the signal came. On the
other hand, the assumption may have been that on reception of a
`onConnectionCompleted` / `onConnectionFailed` signal, a connection was
already thought to be 'closed'.
This will also make the code simpler because SlotContext.closeConnection()
doesn't need to be exposed to the state handlers.
In some way it also shows the redundancy of the whole state handling code
structure as the code doesn't do much more than showing what expected signals
are in which states. The only side-effects left for the states are pushing
requests and results. But even those are never delayed so there's little logic
left in SlotStates.
Refs #1724, #1653, #1721.
=> Fix connection closing issue #1724

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
Refs: #1730
To make it binary compatible, a new overloaded method is added that accepts the Scala Protocol and produces a Scala HttpResponse
Adds explicit return type for `withHeaders`
=> +htc add overloaded method to fix return type #1730

akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ParameterDirectivesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/CustomDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/ParameterDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/RangeDirectivesExamplesSpec.scala
I've replaced almost all of the triple equals assertions with shouldEqual from the code base. Some of the test cases stopped passing after that change so I've fixed them. 
The last triple equals assertion is located in `akka.http.impl.engine.ws.Utf8CodingSpecs` test class. But fixing that probably will take more time because the failure cause was not clear to me. 
Should I create a new issue for Utf8CodingSpecs as a bug or continue it in #1136?
Refs: #1136
=> Replaces triple equals assertions with shouldEqual (#1136)

akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala
Refs #1142 but doesn't really fix it:
* The ScalaTest match style didn't really make sense
* dilating the interval didn't really make sense
* A bit more generous timeout
=> MessageSpec fixes

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
Fixed #1726 (and probably other issues/failures due to "Slot execution failed: Cannot [onResponseDispatchable] when in state [...]".
=> #1726 New pool: solve double dispatch after errors while waiting for dispatch

akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
These are basically new tests for the old implementation. Let's disable
those and focus on improving reliability of the new one.
=> =htc disable LegacyPoolImplementation in HostConnectionPoolSpec

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala
HTTP status code 431 is more specific and described in [RFC 6585](https://tools.ietf.org/html/rfc6585#section-5).
Related to https://github.com/playframework/playframework/pull/8162#discussion_r161883824.
=> Use HTTP 431 when header exceeds value or name max length

akka-http-core/src/main/scala/akka/http/impl/model/parser/CommonActions.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/HeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ParserSettingsImpl.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala
Previously, defining customMediaType in ParserSettings broke parsing of
predefined media types or custom ad-hoc media-types with charsets. This had
two reasons:
* when custom media types were defined, we never parsed into our own
predefined ones any more
* areCustomMediaTypesDefined was defined the wrong way round: just checking
that the value was changed from the magic one doesn't mean there might
still be none defined
Fixes #1786.
=> =htc #1786 fix customMediaTypes behavior

docs/src/main/paradox/routing-dsl/path-matchers.md
Page has dangling `@@@`. Remove top text stating that this only makes sense for Scala DSL.
=> =doc Fix path matcher doc page

akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala, docs/src/test/java/docs/http/javadsl/RespondWithHeaderHandlerExampleTest.java
Thanks @nodefactory-bk for the reproducer.
Fixes #380.
=>  =htc #380 TLS should close connection when instructed by stream completion

docs/src/main/paradox/client-side/request-level.md, docs/src/test/java/docs/http/javadsl/HttpClientExampleDocTest.java, docs/src/test/java/docs/http/javadsl/HttpServerActorInteractionExample.java
This pr for #992:
- updates the code example for actor interaction in Java
- updates the code example for single request in actor in Java and extracts to snippet
=> Adapt Actor Examples to Akka 2.5 #992

docs/src/main/paradox/routing-dsl/case-class-extraction.md
This [does not work](https://github.com/lightbend/paradox/issues/185)
In this case this made Scala-specific content pop up at https://doc.akka.io/docs/akka-http/current/routing-dsl/case-class-extraction.html?language=java
=> Fix nesting WrapDirective's in docs

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/SecurityDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/SecurityDirectives.scala
Implements https://github.com/akka/akka-http/issues/1769
If `Authorization` header is missing check `access_token` URI query parameter instead.
=> Support OAuth2 access token in URI query component as defined in RFC6750

akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala
Fix #1763.
This commit should fix the example of #1763. I am still investigating other `apply` constructors, so I labeled it as WIP. This issue somehow related to https://github.com/akka/akka/issues/19650.
=> [WIP] Fix Uri.apply didn't normalize port (#1763)

docs/src/main/paradox/handling-blocking-operations-in-akka-http-routes.md
* if you have blocking tasks it's likely that they are also
rather long running tasks (several millis) and therefore it
makes most sense to have a low throughput setting for better
fairness
=> wrong advice of throughput setting for blocking dispatcher

.travis.yml, akka-http-core/src/main/mima-filters/10.0.11.backwards.excludes, akka-http/src/main/mima-filters/10.0.11.backwards.excludes, project/Dependencies.scala
I think it's time to switch the default. I started changing the nightlies to use explicit versions when building.
=> =pro build with Scala 2.12 by default

akka-http2-support/src/test/scala/akka/http/h2spec/H2SpecIntegrationSpec.scala
That's only confusing for people looking at the nightly builds. When someone wants to improve HTTP/2 edge cases you can still run H2Spec for pointers about what could be fixed.
=> =ht2 don't fail any tests on jenkins for now to make tests blue

docs/src/main/paradox/common/caching.md, project/ParadoxSupport.scala
Fixes the scaladoc part of #1895. It would be even nicer to try and autodetect
whether we should link to the object, and produce a compile-time error when
linking to a class does not have a companion object or vice-versa, but it seems
this is not supported by fast-classpath-scanner at this point
=> Allow linking to case objects with `@unidoc`

akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolConductor.scala, akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/RouteTest.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/MarshallingTestUtils.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala, akka-http-tests/src/test/java/akka/http/javadsl/server/MarshallerTest.java, akka-http/src/main/mima-filters/10.0.11.backwards.excludes, akka-http/src/main/scala/akka/http/javadsl/server/Route.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteAdapter.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToResponseMarshallers.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileUploadDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/ParameterDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/sse/LineParser.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/PriorityTree.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderDecompression.scala, docs/src/test/java/docs/http/javadsl/RouteSealExample.java, docs/src/test/java/docs/http/javadsl/server/directives/SecurityDirectivesExamplesTest.java
Removes unused private methods
Converts unnecessary `var` to `val`
Adds new overloads without unnecessary implicts
Removes unnecessary default values for parameters
Removes unnecessary `implicit val`s
Migrates deprecated methods to new ones
=> Fix several warnings across the project

akka-http-core/src/main/scala/akka/http/impl/engine/ws/Randoms.scala, akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocketClientBlueprint.scala, akka-http-core/src/main/scala/akka/http/impl/model/JavaQuery.scala, akka-http-core/src/main/scala/akka/http/impl/model/JavaUri.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/Base64Parsing.scala, akka-http-core/src/main/scala/akka/http/impl/util/ByteStringParserInput.scala, akka-http-core/src/main/scala/akka/http/impl/util/JavaAccessors.scala, akka-http-core/src/main/scala/akka/http/impl/util/StageLoggingWithOverride.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/AlpnSwitch.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameLogger.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Compliance.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/IncomingFlowController.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/PriorityTree.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/StreamPrioritizer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/FrameRenderer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameRendering.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/ByteStringInputStream.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderDecompression.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/framing/Http2FramingSpec.scala, build.sbt
I went through the current [API docs](https://doc.akka.io/api/akka-http/10.1.0-RC2/akka/http/javadsl/index.html) which should exclude private stuff and so found a few more classes that should be marked as internal.
=> Mark a lot more internal classes as such

project/Dependencies.scala
This will allow running the nightlies for 2.13. Let's see if that helps for anything or if it just produces spurious failures.
=> =pro also allow building for 2.13.0-M3

.travis.yml, RELEASING.md
This will ignore whatever Scala versions are defined in our sbt build.
Problem with the existing version was that it tried building with 2.13.0-M3 and also tried to run multiple deployment builds because of the added scala version (see #1922).
=> =pro Publish for 2.12.x and 2.11.x in parallel with travis

akka-http-core/src/main/java/akka/http/impl/util/Util.java, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/ParserOutput.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala
These are changes which are a good idea anyways:
* added explicit return types
* don't use `run(_host = xyz)` syntax where it is an assignment and not a named parameter usage
Refs #1916
=> Fix a few 2.13.0-M3 compilation issues

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala
These headers are now always parsed, even when modeled header parsing is disabled. These headers are needed by Akka HTTP in order to populate `Request` objects and to support WebSockets. Both of these features are needed by Play's HTTP backend.
I'd like to have this patch available to Play 2.6 which uses Akka HTTP 10.0.x. Would it be possible to backport this to the the Akka HTTP 10.0.x branch? I've got a PR for Play that I'll submit once this is ready and once there's a new Akka HTTP release available to use.
=> Always parse Content-Encoding and WebSocket headers

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala
Backport of ` Always parse Content-Encoding and WebSocket headers` #1937
=> Always parse Content-Encoding and WebSocket headers (#1937)

docs/src/main/paradox/client-side/request-level.md
I couldn't work out why this was rendering as
"Sink]@java[response.discardEntityBytes(Materializer)`]" in
https://doc.akka.io/docs/akka-http/current/client-side/request-level.html
This fixes it and I think it reads slightly better.
=> Fix paradox error for discard entity bytes

akka-http/src/main/scala/akka/http/javadsl/server/Route.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteAdapter.scala, akka-http/src/main/scala/akka/http/scaladsl/server/Route.scala
Refs: #1898
Initial attempt to remove not needed implicits
MiMa is not happy about the removal of the defaults
If deafaults stay, Scalac complaints about having multiple overloaded alternatives of method seal define default arguments.
=> Remove not needed implicits from Route.seal #1898

akka-http-core/src/main/scala/akka/http/impl/engine/client/OutgoingConnectionBlueprint.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/ResponseParsingMergeSpec.scala
getNextData handler completes the stage immediately if dataIn is closed,
preventing emmitting elements and trigerring already registered completeStage
event in onUpstreamFinish handler.
Fix #1899
=> Emit entity truncation errors before completing graph stage

akka-http-core/src/main/java/akka/http/impl/util/Util.java, akka-http-core/src/main/java/akka/http/javadsl/model/Uri.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/LinkParams.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/LinkValue.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/Location.java, akka-http-core/src/main/java/akka/http/javadsl/model/headers/Referer.java, akka-http-core/src/main/mima-filters/10.1.0.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/model/JavaUri.scala
Adds `javadsl.model.Uri.asScala()`
Adds `static javadsl.model.Uri.create(scaladsl.model.Uri)`
Removes the internal conversion method from `akka.http.impl.util.Util`.
Fixes #1949
=> Support conversion between scaladsl.Uri and javadsl.Uri

build.sbt, docs/src/main/paradox/compatibility-guidelines.md, docs/src/main/paradox/introduction.md
This reverts commit dc708850193244eb3c67f34d77bc4401c2fa36a3.
We accidentally backported the change to the build file which made akka-stream not depended on automatically; This is fine and documented in 10.1, however such change should not exist on 10.0.
This PR reverts this commit
=> Revert "!pro make akka-actor / akka-stream a provided dependency (#1582)"

akka-http-core/src/main/mima-filters/10.1.0.backwards.excludes, akka-http-core/src/main/mima-filters/10.1.1.backwards.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/ws/FrameHandler.scala, akka-http-core/src/main/scala/akka/http/impl/engine/ws/Protocol.scala, akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocket.scala, akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocketClientBlueprint.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ClientConnectionSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/impl/settings/WebSocketSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ClientConnectionSettings.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/WebSocketSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ClientConnectionSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/WebSocketSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/ByteStringSinkProbe.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketServerSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/WithMaterializerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/TestServer.scala, docs/src/main/paradox/client-side/websocket-support.md, docs/src/main/paradox/server-side/websocket-support.md, docs/src/test/java/docs/http/javadsl/server/WebSocketCoreExample.java, docs/src/test/scala/docs/http/scaladsl/server/WebSocketExampleSpec.scala
Initial progress on https://github.com/akka/akka-http/issues/102
This is now ready for review; it does the basic automatic, ping keepalive, but also I allowed for the pong keep alive. We do not allow customising the data payload; I can add this if needed but it's likely good enough without payload for the basic use cases
=> Transparent websocket ping/pong

akka-http-tests/src/test/scala/akka/http/scaladsl/server/EntityStreamingSpec.scala, docs/src/main/paradox/common/json-support.md, docs/src/main/paradox/routing-dsl/source-streaming-support.md, docs/src/test/java/docs/http/javadsl/server/JsonStreamingExamplesTest.java
It was pointed out on akka-user that we didn't document the client-side for consuming streaming JSON responses nicely; I added those docs.
`Re: [akka-user][deprecated] Akka Http and consuming a response of "application/stream+json" type`
=> =doc document client-side for streaming JSON

CONTRIBUTING.md, docs/src/main/paradox/contributing.md
Since Scalariform is already maintained by scala-ide, I changed to the new repository.
=> Change the link of Scalariform

akka-http-core/src/main/scala/akka/http/impl/model/parser/CommonActions.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/HeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ParserSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
When a custom media type is matched we now add parameters. In particular this now means that users can support the `charset` parameter in custom media types.
This change will be used downstream in Play's Akka HTTP backend. Play will be able to override the `application/json` media type to support an explicit `charset` parameter instead of having an implicit, fixed `charset` of UTF-8. Allowing an explicit `charset` parameter will fix several Play bugs related to interop with other HTTP agents.
See:
- https://github.com/playframework/playframework/issues/8239
- https://github.com/playframework/play-ws/issues/150
=> Support parameters for custom media types

akka-http-tests/src/test/scala/akka/http/scaladsl/server/DiscardEntityDefaultRejectionHandlerSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/WithoutSizeLimitSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala
Refs: #38
Default RejectionHandler is rejecting now the request entity by default.
Not knowing a better way to check if the `Source` has been discarded, it's counting elements emitted in test
=> =htp Discard Entity in Default RejectionHandler #38

akka-http-tests/src/test/java/akka/http/javadsl/server/MarshallerTest.java, akka-http/src/main/scala/akka/http/javadsl/marshalling/Marshaller.scala, docs/src/main/paradox/common/marshalling.md
Fixes #1247 by adding a `Marshaller<Optional<A>, RequestEntity>` that is usable from Java.
=> Add Java DSL optionMarshaller #1247

docs/src/main/paradox/implications-of-streaming-http-entity.md
Redundant part about running the underlying `dataBytes` Source
=> Duplication of description

docs/src/main/paradox/release-notes/10.1.x.md, docs/src/main/paradox/routing-dsl/rejections.md
Document that default `RejectionHandler` is not discarding the entity.
Also added release notes for version 10.1.1 that were missing (oops!)
=> [+doc] Document entity discarding in default rejection handler

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala, akka-http2-support/src/test/scala/akka/http/h2spec/H2SpecIntegrationSpec.scala
We don't actually pick such large header table sizes, but now don't
crash when we're allowed one anymore either. Fixes the h2spec TCK
tests for section 6.5.
=> Allow h2 SETTINGS with large max header table size

akka-http-core/src/main/java/akka/http/javadsl/model/Multiparts.java, akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala, akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/WSProbe.scala, akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/WSTestRequestBuilding.scala
=> Backport: Fix type parameters in Java API to work with latest Akka #1965

docs/src/main/paradox/server-side/low-level-api.md
The doc page has a wrong name - `akka.http.server.pipelining-limit` is correct.
https://github.com/akka/akka-http/blob/12e7c98b7f003ed0bfe3ed9ddf51dc2e360a6c00/akka-http-core/src/main/resources/reference.conf#L98
=> doc Correct pipelining-limit flag name

akka-http-core/src/main/scala/akka/http/impl/util/package.scala
When using `Route.seal` on a route, I get the following exception
```
[error] Exception in thread "main" java.lang.ExceptionInInitializerError
[error] 	at sbux.ucp.canary.Main$.main(Main.scala:42)
[error] 	at sbux.ucp.canary.Main.main(Main.scala)
[error] Caused by: java.lang.IllegalStateException
[error] 	at akka.http.impl.util.package$.actorSystem(package.scala:34)
[error] 	at akka.http.scaladsl.settings.SettingsCompanion.default(SettingsCompanion.scala:20)
[error] 	at akka.http.scaladsl.settings.SettingsCompanion.default$(SettingsCompanion.scala:20)
[error] 	at akka.http.scaladsl.settings.RoutingSettings$.default(RoutingSettings.scala:42)
[error] 	... 2 more
```
This isn't great, because it doesn't tell me what object was picked up as an actorRef factory.  Adding in the object in the …
=> More descriptive error message for actorSystem

docs/src/main/paradox/routing-dsl/path-matchers.md
typo, add missing closing bracket
=> typo, add missing closing bracket

docs/src/main/paradox/introduction.md
Right after second example of _Introduction_ page, a curl command is provided to let the reader create an order. But provided JSON document does not comply with domain model: the order is specified as an item, while it should be a list of items.
=> Correct syntax of curl command for creating an order

docs/src/main/paradox/routing-dsl/source-streaming-support.md, docs/src/test/java/docs/http/javadsl/server/JsonStreamingExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/JsonStreamingExamplesSpec.scala
I didn't open an issue for this, as this is small improvement to the documentation, but let me know if I should .
The rendered page is here: https://richard-akka-http-doc.firebaseapp.com/routing-dsl/source-streaming-support.html
At the beginning of the "JSON streaming" section, there is a mention to `Measurement`,
but that is actually not used until much later in the "Consuming JSON streaming" section.
=> doc - move the "measurement" stuff to the section where it is explained in detail

CONTRIBUTING.md, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/client/HttpsProxyGraphStage.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/SettingsCompanion.scala, akka-http-core/src/test/scala/akka/http/scaladsl/TightRequestTimeoutSpec.scala, akka-http-tests/src/multi-jvm/scala/akka/http/AkkaHttpServerLatencyMultiNodeSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/CustomMediaTypesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/CustomStatusCodesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CacheConditionDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/IllegalHeadersIntegrationSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/sse/ServerSentEventParserSpec.scala, akka-http/src/main/scala/akka/http/javadsl/common/EntityStreamingSupport.scala, akka-http/src/main/scala/akka/http/javadsl/marshalling/Marshaller.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/Marshaller.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/MultipartMarshallers.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-parsing/src/main/java/akka/parboiled2/util/Base64.java, docs/src/main/paradox/common/http-model.md, docs/src/main/paradox/contributing.md, docs/src/main/paradox/routing-dsl/directives/marshalling-directives/handleWith.md, docs/src/main/paradox/routing-dsl/path-matchers.md, docs/src/test/java/docs/http/javadsl/server/DirectiveExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/DebuggingDirectivesExamplesTest.java, project/ValidatePullRequest.scala
As with https://github.com/akka/akka/pull/25448, I've fixed typos detected by https://github.com/client9/misspell 
```
$ misspell .
akka-http/src/main/scala/akka/http/javadsl/marshalling/Marshaller.scala:101:53: "actualy" is a misspelling of "actually"
akka-http/src/main/scala/akka/http/javadsl/marshalling/Marshaller.scala:114:43: "actualy" is a misspelling of "actually"
akka-http/src/main/scala/akka/http/javadsl/marshalling/Marshaller.scala:127:43: "actualy" is a misspelling of "actually"
akka-http/src/main/scala/akka/http/javadsl/marshalling/Marshaller.scala:140:43: "actualy" is a misspelling of "actually"
akka-http/src/main/scala/akka/http/javadsl/marshalling/Marshaller.scala:153:43: "actualy" is a misspelling of "actually"
akka-http/src/main/scala/akka/http/javadsl/common/EntityStreami …
```
=> Fix several minor typos detected by github.com/client9/misspell

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/pool/SlotStateSpec.scala
Fixes bug in SlotState for akka/akka-http#2138
Accepting `onRequestEntityCompleted` when in `WaitingForEndOfResponseEntity`. Staying in the same state, marking request as ended (`waitingForEndOfRequestEntity = false`)
=> Fixes bug in SlotState for akka/akka-http#2138

akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/CustomMediaTypesSpec.scala
If MediaType instances are used with a hashset or hashmap,
equivalent (equal) objects should go into the same buckets. Since
MediaType's equals() method correctly is case insensitive, do should its
hashCode.
Fixes #2144.
=> Ignore case for MediaType.hashCode

akka-http-core/src/main/mima-filters/10.1.3.backwards.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/javadsl/settings/Http2ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/UseHttp2.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
Refs #2145 
The idea is to change the default for the `bindAndHandleAsync` `parallelism` parameter to `0`, which means "take the value from the configuration".
We then take different values for HTTP/1 and HTTP/2:
* for HTTP/1 take `pipelining-limit` because that's even stronger than parallelism
* for HTTP/2 take a new setting `http2.max-concurrent-streams`
=> Introduce HTTP/2 max-concurrent-streams settings

docs/src/main/paradox/_template/projectSpecificFooter.st, docs/src/main/paradox/assets/js/warnOldDocs.js, project/plugins.sbt
Refs: #2135
Adds a warning banner in the style of Akka when the user is browsing outdated or old versions in same series.
**NOTE**
**This PR will not make it appear on old versions unless the template and the `warnOldDocs.js` file are added manually to the old documentation files on the webserver.**
=> +doc Add warning banner when browsing old versions #2135

akka-http-core/src/main/mima-filters/10.1.3.backwards.excludes, akka-http-core/src/main/scala/akka/http/javadsl/ConnectHttp.scala, akka-http-core/src/main/scala/akka/http/javadsl/ConnectionContext.scala, akka-http-core/src/main/scala/akka/http/scaladsl/ConnectionContext.scala, akka-http-core/src/test/scala/akka/http/javadsl/ConnectHttpSpec.scala
The only information passed from javadsl to the scaladsl in Http
was the context which for Http connections was always the default one
meaning that setting http2 always had no effect.
This seed the easiest way not to break the user facing API
=> Preserve http2 option when going from javadsl to scaladsl

akka-http-core/src/main/scala/akka/http/impl/model/parser/SimpleHeaders.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/StrictTransportSecurityDirective.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/headers/HeaderSpec.scala
Fixes issue [#2122](https://github.com/akka/akka-http/issues/2122) so that HSTS header support is conform spec. Specifically:
- Trailing semicolons are allowed.
- Order of directives is not important.
- 'max-age' directive must occur exactly once.
- 'includeSubDomains' directive may not occur more than once.
=> Implement HSTS header support conform spec #2122

akka-http-core/src/main/java/akka/http/javadsl/model/MediaTypes.java, akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala
added `application/merge-patch+json` media type to akka-http-core
Refs #2189
=> added application/merge-patch+json

docs/src/main/paradox/migration-guide/migration-guide-10.0.x.md, docs/src/main/paradox/release-notes/10.0.x.md
Because people will more likely see them on the `current` page.
=> Publish 10.0.14 release notes also on master

akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, project/Dependencies.scala, project/VersionGenerator.scala
Fixes #1538 
See issue for discussion if it should really be done.
=> Require Akka 2.5.10 and use the new version checker utility

RELEASING.md, project/MiMa.scala
In these cases like looking from 10.1.x to 10.0.x, when branching, we
defined a set of mima filters between 10.1 and 10.0. However, from Mima's
perspective a new 10.0.x version will reintroduce the incompatibilities.
For that reason, we collect all old filters (i.e. filters for released versions of
forked branches) and only keep an entry for the latest version of the forked
branch.
In our case, all filters for 10.0.x are collected and then registered as a
single entry for 10.0.13 (mima already reuses newer filters for older versions
so that this covers all older versions).
An alternative approach would be to collect mima filters for forked branches
when doing the branch in a single file like `10.0.x.backwards.excludes`.
=> =pro Fix Mima rules for forked release branches

akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Refs #1886.
I suspect the failure was just a timing issue, where the idempotent GET request
is automatically retried 6 times, but that didn't happen within the 3 seconds
that `EventFilter` waits for this. Sidestepped by using a non-idempotent POST
request so it won't retry at all.
=> HTTPS request to HTTP endpoint logging test

akka-http-caching/src/main/scala/akka/http/caching/LfuCache.scala, akka-http-caching/src/test/scala/akka/http/caching/ExpiringLfuCacheSpec.scala, docs/src/main/paradox/common/caching.md
If you don't want to use tti you need to write some ugly `time-to-idle = 5 minutes - 1 seconds` to the config. So I fixed the requirement.
(Maybe if tti is not finite we should use ttl for both values. That would make easier setup in some use-cases. But that can be misleading too, so I did the minimal effort "fix" only.)
(Or maybe we should play with boolalgebra and change the whole thing to:
`!(timeToLive.isFinite && timeToIdle.isFinite && timeToLive < timeToIdle)` bcs the following implementation only set the desired finite values...)
=> fix LfuCache ttl can be equal to tti

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileUploadDirectives.scala
=> =htp Fix cancellation and head-of-line blocking in fileUpload directive

docs/src/main/paradox/routing-dsl/index.md
Currently, this section is nested inside "Handling HTTP Server failures in the High-Level API".
=> Fix header for the file upload section in Routing documentation

akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/coding/CoderSpec.scala
This fixes an issue where the limitByteChunksStage function used by the NoCoding encoder was losing data if larger than the maximum chunk size. The tests have also been fixed to cover this scenario.
I don't know if this is an issue that affects people using the akka-http in the wild, but is quite subtle. I came across the issue trying to test out chunked StreamRefs in akka-cluster in a WIP PR https://github.com/akka/akka/pull/25643. That PR copies the broken code from akka-http verbatim, so is likely to be also broken.
=> Fix limiting of chunk size in the NoCoding encoder

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> Handle stream cancellation while outgoing data is buffered 

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ParameterDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/PredefinedFromStringUnmarshallers.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/ParameterDirectivesExamplesSpec.scala
Hello,
This PR solves the issue when `CsvSeq[T]` unmarshaller would ignore last empty string value (the one after trailing comma), i.e. would not pass it to underlying unmarshaller. This is agains csv semantic, so I think it is fair to assume that this is bug.
```scala
val values = Await.result(CsvSeq[String].apply(",value1,value2,"), Duration.Inf)
// Current behaviour
assert(values == Seq("", "value1", "value2"))
// Expected behaviour
// assert(values == Seq("", "value1", "value2", ""))
```
This is my very first PR, so I am scared and sorry if I did something wrong, but the fix seems straightforward enough to try submitting it
=> Fix CsvSeq unmarshaller to include trailing empty string values in the result Seq[T]

akka-http-core/src/main/java/akka/http/javadsl/model/StatusCodes.java, akka-http-core/src/main/scala/akka/http/scaladsl/model/StatusCode.scala
I think this should be safe to just replace as `Unordered Collection` was only ever present in WebDAV drafts and should have no implementations, but of course it is a breaking change.
See https://tools.ietf.org/html/rfc8470 for details on `Too Early`.
=> Replace existing HTTP Status Code 425 with TOO_EARLY

akka-http-tests/src/test/java/akka/http/javadsl/server/directives/MiscDirectivesTest.java, akka-http-tests/src/test/scala/akka/http/scaladsl/server/SizeLimitSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MiscDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala, docs/src/test/java/docs/http/javadsl/server/directives/MiscDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/MiscDirectivesExamplesSpec.scala
#2279 Modify RejectionHandler to complete request which encounter EntityStreamSizeException with RequestEntityTooLarge status code instead of BadRequest
=> #2279 Fix status code in case of EntityStreamSizeException

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/---bug-report.md, .github/ISSUE_TEMPLATE/---feature-request.md, .github/ISSUE_TEMPLATE/---question.md
I directly copied the ones for Akka (thanks @raboof!) and removed the hint to other repos,
as we never get issues or feature requests for the wrong repo in Akka HTTP.
=> Add issue templates

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMethod.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpMethodsSpec.scala
=> Overriden `getForKeyCaseInsensitive` in `HttpMethods` #2303

akka-http-core/src/main/mima-filters/10.1.5.backwards.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ConnectionPoolSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ConnectionPoolSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ConnectionPoolSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/DontLeakActorsOnFailingConnectionSpecs.scala, docs/src/main/paradox/client-side/host-level.md
Fixes #1391.
It works but I might want to tweak the implementation a bit. The settings file describes the feature quite well.
TODO:
=> =htc #1391 client pool: exponential backoff after failed connection attempts

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/AllowMaterializationOnlyOnce.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/common/StrictForm.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala
Fixes the 'simple case' ('A') of #73
To avoid consuming the entity for each field. Of course slurping in the
entire entity is not very elegant, but this is what both the form-data and
the multipart marshallers already do further down the line.
=> toStrict the entity when parsing multiple form fields

docs/src/main/paradox/routing-dsl/exception-handling.md, docs/src/test/java/docs/http/javadsl/ExceptionHandlerExample.java, docs/src/test/java/docs/http/javadsl/ExceptionHandlerInSealExample.java, docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala
Add Route.seal example to Exception Handling docs
Removes extra `implicit` in example where it wasn't needed
Removes `throws IOException` declaration where it wasn't needed
=> =doc Add Route.seal example to Exception Handling docs #266

akka-http/src/main/scala/akka/http/scaladsl/server/Directive.scala, docs/src/main/paradox/routing-dsl/directives/custom-directives.md, docs/src/test/scala/docs/http/scaladsl/server/directives/CustomDirectivesExamplesSpec.scala
This commit adds two new methods on `Directives`:
- Directive#ttransform the tupled variant of Future#transform that
allows mapping and filtering at the same time
- Directive1#transform the equivalent of Future#transform for
Directive1, the specialized version of Directive#ttransform
As an example, instead of writing:
```
parameter("x".as[Int]).filter(x => x >= 0, someRejection).map(x => Positive(x))
```
we can now write this in one go using Directive1#transform:
```
parameter("x".as[Int]).transform({ case x if x >= 0 => Positive(x) }, someRejection)
```
- composing `PartialFunction`s is really awkward, had to hack around it in `Directive1#transform` because there we have to nest two of them
- I would prefer a curried version of `transform` that takes the partial function as the second …
=> Add Directive#tcollect and Directive1#collect

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
Refs #1484 (fixes the easy one of the two exceptions reported there).
=> =htc Fix broken multi-byte UTF-8 decoding if UTF-8 sequence is cut in the middle

.travis.yml
As Travis doesn't seem to check out the branch but a certain hash instead.
=> =pro when detecting master branch also check TRAVIS_BRANCH

akka-http2-support/src/test/scala/akka/http/h2spec/H2SpecIntegrationSpec.scala
The akka-http-nightly build is run from a path that contains the names of all the axis. The JVM axis is now "AdoptOpenJDK 8", i.e. containing a space. The h2spec needs to run an executable with full path that then includes a space which currently doesn't work.
Not sure if quoting works with the ProcessBuilder but let's try.
=> =ht2 harden h2spec execution against spaces in the executable path

project/MultiNode.scala
Java's `propertyNames` uses a wildcard type, so that Scala doesn't know statically
that only Strings are inside.
=> =pro fix warning in build

akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, build.sbt
This is how the warning log looks like if you mess up:
```
[WARN] [12/20/2018 10:19:07.966] [run-main-0] [ManifestInfo(akka://helloAkkaHttpServer)] Detected possible incompatible versions on the classpath. Please note that a given Akka HTTP version MUST be the same across all modules of Akka HTTP that you are using, e.g. if you use [10.1.6+7-3560e987] all other modules that are released together MUST be of the same version. Make sure you're using a compatible set of libraries. Possibly conflicting versions [10.1.3, 10.1.6+7-3560e987] in libraries [akka-http-spray-json:10.1.3, akka-parsing:10.1.6+7-3560e987, akka-http-xml:10.1.6+7-3560e987, akka-http:10.1.6+7-3560e987, akka-http-core:10.1.6+7-3560e987]
```
Refs #2335
=> Check that all akka-http modules have the same version, #2335

akka-http2-support/src/test/scala/akka/http/h2spec/H2SpecIntegrationSpec.scala
Number of tests run dropped quite a lot in the nightlies (~ 4000 to ~3000) since I enabled AdoptOpenJDK. Turns out for quite stupid reasons ;)
(Almost all of 1000 tests are maked as skipped but anyway...)
=> =ht2 fix H2SpecIntegrationSpec xml test report generation

akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
=> [10.0-backport] TLS closing issue fixes

akka-http/src/main/scala/akka/http/scaladsl/server/Rejection.scala
The toString implementation inherited by java.lang.Throwable only prints
the class name followed by the result of the getMessage method (which,
by default, returns null). As a consequence, the rejection carried by a
RejectionError instance is not shown.
We pass the given rejection to the RuntimeException constructor so that
it is shown as the exception message.
=> Set a more descriptive message to the RejectionError exception

.travis.yml, notes/release-train-issue-template.md, project/Publish.scala
To consume snapshots, the following resolver is to be used:
```scala
resolvers += Resolver.bintrayRepo("akka", "snapshots")
```
Fixes #1254
Supersedes #1744
=> Publish snapshots of every master commit

docs/src/main/paradox/routing-dsl/testkit.md
To run the example in this page I also needed the `akka-stream-testkit` dependency.
I believe it would make sense to have it in this page.
=> Add akka-stream-testkit

docs/src/test/scala/docs/http/scaladsl/server/directives/DebuggingDirectivesExamplesSpec.scala
I guess there was a rename and the comment got left behind?
=> replace logRequestResponse with logRequestResult

akka-http-tests/src/test/java/akka/http/javadsl/server/directives/RouteDirectivesTest.java, akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala
Hi there!
To fix this bug I've followed the route suggested in the comments. A unit test was also patched.
=> Oversized requests should return 413 and not 500 #358

akka-http-core/src/main/java/akka/http/javadsl/model/ContentTypes.java, akka-http-core/src/main/java/akka/http/javadsl/model/FormData.java, akka-http-core/src/main/java/akka/http/javadsl/model/MediaTypes.java, akka-http-core/src/main/mima-filters/10.1.7.backwards.excludes, akka-http-core/src/main/scala/akka/http/scaladsl/model/ContentType.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/FormData.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/MediaType.scala, akka-http-tests/src/test/java/akka/http/javadsl/server/values/FormFieldsTest.java, akka-http-tests/src/test/scala/akka/http/scaladsl/FormDataSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/MarshallingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToEntityMarshallers.scala
Closes #91
Currently `charset=UTF-8` is added to `Content-Type: application/x-www-form-urlencoded` by default. This mime-type, however, takes no charset parameter as IANA describes [its specification](https://www.iana.org/assignments/media-types/application/x-www-form-urlencoded). ~As [W3 application-x-www-form-urlencoded encoding algorithm](https://www.w3.org/TR/html5/sec-forms.html#application-x-www-form-urlencoded-encoding-algorithm) describes, `charset` is not expected.~ Thus we don't append `charset=UTF-8` in `Content-Type: application/x-www-form-urlencoded` FormData.
=> Disable to append charset=UTF-8 by default in `Content-Type: application/x-www-form-urlencoded` FormData

akka-http-core/src/main/scala-2.13+/akka/http/ccompat/imm/package.scala, project/Doc.scala
That's because it's broken in 2.13.0-M5 with `-Ymacro-annotations` enabled.
See #2416.
Fixes #2416.
=> =pro disable scaladoc generation for 2.13.0-M5 for now, #2416

docs/src/main/paradox/server-side/server-https-support.md
Ssl-config still doesn't support server-side TLS/SSL configuration, so don't pretend it does.
Refs #55.
=> =doc Remove mention of ssl-config in server docs

docs/src/test/scala/docs/http/scaladsl/SprayJsonExampleSpec.scala
This code snippet is referenced in the introduction documentation of akka-http:
https://doc.akka.io/docs/akka-http/current/introduction.html
It was a frustrating experience (again) with examples from the doc. I had to spend some time to find out why the code snippet didn't compile. Mentioning this required dependency for this snippet would save me and others time.
=> make code example in introduction doc self-contained

akka-http-core/src/test/scala/akka/http/HashCodeCollider.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/util/BenchUtils.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala
This should be statistically much more reliable and guards against one-time
interruptions.
Fixes #2340, #2386.
=> =htc,htp improve colliding hashCode tests by taking minimum of multiple runs

akka-http-tests/src/test/java/akka/http/javadsl/server/directives/ParameterDirectivesTest.java, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ParameterDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/ParameterDirectives.scala
Removed raw query from error message, because including it can facilitate injection attacks such as cross-site scripting (XSS).
=> Injection vulnerability: raw query in error message.

akka-http-core/src/main/scala/akka/http/impl/engine/rendering/RenderSupport.scala
Going through the HashMap is slow because calculating a hashCode is
slow compared to doing a series of quick reference equals checks.
=> =htc Use static scanning when searching for well-known ContentType for rendering

akka-http-core/src/main/mima-filters/10.1.7.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpResponseParser.scala
* Prevent a round-trip of throwing and catching exceptions after having read a full request (default case)
* Prevent buffering single elements in the output buffer
=> Improve message parsing

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
Refs #2462
Manually tested by running Http2ServerTest, doing a
`curl http://localhost:9001` (speaking HTTP to the HTTPS port)
and inspecting the Jetty ALPN map with a debugger.
=> Clean up ALPN when the stream is stopped

docs/src/main/paradox/common/caching.md, docs/src/test/java/docs/http/javadsl/server/directives/CachingDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/CachingDirectivesExamplesSpec.scala
#1955 Issue
Added missing imports
```java
import java.util.concurrent.TimeUnit;
```
```scala
import scala.concurrent.duration._
```
In caching docs
https://doc.akka.io/docs/akka-http/current/common/caching.html
=> Cache docs: Add missing TimeUnits and duration imports

notes/release-train-issue-template.md
Hi, I believe the step to update the Akka Http version on https://akka.io/docs/ is missing so I just added it.
=> Add step to update the Akka Http version on akka.io/docs

docs/src/main/paradox/common/http-model.md, docs/src/main/paradox/release-notes/10.0.x.md, project/plugins.sbt
Link to companion object for Scala, to class (which has static forwarders)
for Java.
=> Fix links to objects

build.sbt
This fixes our nightly akka-docs build, though oddly I can't reproduce the problem locally
=> Add akka-testkit as provided for akka-http-testkit

project/AkkaDependency.scala
To be able to run the nightly builds also against current akka release-2.5 branch sources.
=> Add support for `-Dakka.build.version=release-2.5` to allow building against akka 2.5 source branch

akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocket.scala
I found a FIXME in code and willing to fix it. This FIXME has reference to https://github.com/akka/akka/issues/16885
https://github.com/akka/akka/issues/16885
now I have 20 failed tests. 19 of them fail with error message that they expect strict message but get source (obviously why). Is it ok to fix those tests?
and one is complaining:
```
"for echoing user handler"
java.lang.AssertionError: assertion failed: expected 11 bytes, but got 11 bytes 
Expected: 
ByteString(11 bytes)
81 09 4D 65 73 73 61 67 65 20 31                 | ..Message 1
But got: 
ByteString(11 bytes)
01 09 4D 65 73 73 61 67 65 20 31                 | ..Message 1
at scala.Predef$.assert(Predef.scala:223)
at akka.http.impl.engine.ws.ByteStringSinkProbe$$anon$1.expectBytes(ByteStringSinkProbe.scala:83)
at …
```
=> use splitAfter in Websocket implementation

akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/UnmarshallingSpec.scala, akka-http/src/main/mima-filters/10.1.8.backwards.excludes, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/PredefinedFromStringUnmarshallers.scala
Add ability to unmarshall Strings to UUIDs in Scala code via predefined implicit `Unmarshaller[String, UUID]`
So we have followings things already:
* [String -> UUID Java Unmarshaller](https://github.com/akka/akka-http/blob/master/akka-http/src/main/java/akka/http/javadsl/unmarshalling/StringUnmarshallers.java#L73)
* [UUID path matcher](https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/PathMatcher.scala#L488)
But we don't have similar thing for Scala Unmarshaller, so one can't do stuff like this (that is actual use case which I needed):
```scala
parameter('id.as[UUID]) { id => ... }
```
While you can do this:
```scala
path(JavaUUID) { id => ... }
```
Seemed like a good thing, so I was surprised that it is not available out of the box for …
=> Add String to UUID unmarshaller to the predefined Scala unmarshallers

akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTestResultComponent.scala, akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/ScalatestRouteTestSpec.scala
One particular starvation case is if a test is run on the ActorSystem dispatcher
which might use a BatchingExecutor. In that case thunks might be scheduled to
be run on the currently running thread but be starved by the unmanaged blocking
in RouteTestResultComponent.awaitResult.
Fixes #2526.
=> htk: manage blocking in RouteTestResult to make starvation less likely

akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
The "Hostname verification failed" warning was emitted by ssl-config when
hostname verification is disabled. In version ssl-config 0.4.0 (which is
transitively pulled in by akka-stream 2.5.22 for Scala 2.13), this warning
isn't shown any more.
=> htc: remove warning expectation in ClientServerSpec

build.sbt
Before:
11:48:49 $ javap -verbose ./akka-http-core/target/scala-2.12/classes/akka/http/javadsl/model/HttpRequest.class | grep major
major version: 55
After:
10:49:25 ! javap -verbose ./akka-http-core/target/scala-2.12/classes/akka/http/javadsl/model/HttpRequest.class | grep major
major version: 52
=> Ensure Java & Scala code is compiled targeting JVM 8

build.sbt
=> Avoid passing -target to javadoc

akka-http-tests/src/multi-jvm/scala/akka/http/AkkaHttpServerLatencyMultiNodeSpec.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/PathDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/PathDirectives.scala, docs/src/main/paradox/routing-dsl/directives/index.md, docs/src/main/paradox/routing-dsl/routes.md, docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/SprayJsonExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/DirectiveExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/FullSpecs2TestKitExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/FullTestKitExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/BasicDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/FileAndResourceDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/FormFieldDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/FutureDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/HostDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/MethodDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/MiscDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/PathDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/RouteDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/SchemeDirectivesExamplesSpec.scala
refs: #2537
Modify samples
Modify docs
Restructure docs text to encourage `concat`
This now has the nice side effect that we can remove the `// format: OFF` directives.
=> Prefer concat in samples #2537

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/BasicDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/BasicDirectives.scala
Now if extractStrictEntity fails with a timeout it will return 408 Request Timeout status instead of 500 Internal Service Error
https://github.com/akka/akka-http/issues/2548
Added TimeoutException handler for toStrict method
=> Return 408 RequestTimeout status when `toStrict` times out #2548

akka-http-core/src/main/scala/akka/http/javadsl/UseHttp2.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/UseHttp2.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/WithPriorKnowledgeSpec.scala, akka-http2-support/src/test/scala/akka/http/scaladsl/Http2BindingViaConfigSpec.scala, akka-http2-support/src/test/scala/akka/http/scaladsl/Http2ServerTest.scala, docs/src/test/java/docs/http/javadsl/Http2Test.java, docs/src/test/scala/docs/http/scaladsl/Http2Spec.scala
Just for discussion, I'm not sure we should do this.
https://github.com/akka/akka-http/pull/2543#discussion_r290340917
I'm hesitant because `Negotiated` is the default, and adding the
`PriorKnowledgeSwitch` might have a performance penalty on top of 'plain'
HTTP/1.
For the same reason I'm not sure we should roll it into `Always`.
References #xxxx
=> Roll together 'prior knowledge' and 'negotiated'

akka-http-core/src/test/java/akka/http/javadsl/model/EntityDiscardingTest.java, akka-http-core/src/test/java/akka/http/javadsl/model/UriTest.java, akka-http-core/src/test/java/akka/http/javadsl/model/sse/ServerSentEventTest.java, akka-http-core/src/test/java/akka/http/javadsl/settings/ClientConnectionSettingsTest.java, akka-http-core/src/test/java/akka/http/javadsl/settings/ConnectionPoolSettingsTest.java, akka-http-core/src/test/java/akka/http/javadsl/settings/ParserSettingsTest.java, akka-http-core/src/test/java/akka/http/javadsl/settings/ServerSettingsTest.java, akka-http-tests/src/test/java/akka/http/javadsl/settings/RoutingSettingsTest.java, akka-http-tests/src/test/java/akka/http/javadsl/unmarshalling/sse/EventStreamUnmarshallingTest.java, docs/src/test/java/docs/http/javadsl/server/HttpAppExampleTest.java, docs/src/test/java/docs/http/javadsl/server/HttpsServerExampleTest.java
Trying the new RC from ScalaTest to see if Java code can see the new `JUnitSuite` class
=> Use ScalaTest 3.0.8 so new JUnitSuite is available from Java

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/HeaderDirectivesSpec.scala, akka-http/src/main/mima-filters/10.1.8.backwards.excludes, akka-http/src/main/scala/akka/http/scaladsl/server/Directive.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/WithPriorKnowledgeSpec.scala, project/Formatting.scala
So far, in #2283 the case for tuples was fixed which also worked for nested `formField` directives in most of the cases but not when the first usage was with a single argument.
Refs #73.
=>  htp: fix case of nested FormField if first formField usage is with single parameter

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
Before they would be closed when the connection closes, which caused
unnecessary memory use for long-lived HTTP/2 connections with many streams
(as is common with gRPC).
Refs #2551
=> Close outgoing HTTP/2 streams earlier

akka-http-core/src/main/mima-filters/10.1.8.backwards.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/javadsl/settings/Http2ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameLogger.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/test/scala/akka/http/h2spec/H2SpecIntegrationSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
+ enable it for some test suites which use WithLogCapturing
=> +ht2 add akka.http.server.http2.log-frames for verbose frame logging for debugging purposes

notes/release-train-issue-template.md
Instructions to keep the minor version docs in sync.
I added links for https://doc.akka.io/docs/akka-http/10.1/ and https://doc.akka.io/docs/akka-http/10.0/ today.
=> Releasing: minor version links & git

akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/UnmarshallingSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/PredefinedFromStringUnmarshallers.scala
Improve the validation in the uuid unmarshaller.
Follows #2505 which introduced the unmarshaller.
Uses a regex that accepts uuid's as defined in [RFC 4122](https://tools.ietf.org/html/rfc4122). A special case is added for the nil uuid. Also avoids a try/catch block.
The validation in `UUID.fromString`-method in java 8 is pretty poor and accepts a lot of invalid uuid strings, java 9 improves on it somewhat but is still far too accepting.
=> Improve validation in uuid unmarshaller

akka-http-core/src/main/resources/reference.conf, docs/src/main/paradox/introduction.md
in the src/main/paradox/introduction.md line 87 
> The high-level, routing API of Akka HTTP provides a DSL to describe HTTP "routes" and how they should be handled. Each route is composed of one or more level of `Directive` s that narrows down to handling one specific type of request.
the Directives wrote wrong.
I'm glad to fix it :)
=> There's a typo in the introduction.md

akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocketClientBlueprint.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/ws/WebSocketRequest.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketClientSpec.scala
Currently passing multiple websockets subprotocols in `Sec-WebSocket-Protocol` header is not supported (see https://github.com/akka/akka-http/issues/2606). This PR makes it possible to do so, passing them separated by comma in `subprotocol: Option[String]` field of the [`WebSocketRequest`](https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/scaladsl/model/ws/WebSocketRequest.scala#L22) model. This corresponds to the `Sec-WebSocket-Protocol` header definition in [RFC 6455](https://tools.ietf.org/html/rfc6455#section-11.3.4)
A better solution would be to change the `WebSocketRequest` model to accept a `subprotocols: Seq[String]` field, but that would break compatibility with current client code. If it, nevertheless, makes sense to do this change, please let …
=> Support multiple subprotocols in Websocket handshake for client side

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/PathDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/PathMatcher.scala
Improve the JavaUUID path matcher
This PR tightens the existing regex and adds the nil uuid, making it accept uuid's as defined in [RFC 4122](https://tools.ietf.org/html/rfc4122). Also avoids a try/catch block.
=> Improve JavaUUID path matcher

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/Multipart.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/DebuggingDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/common/StrictForm.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/SecurityDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/TimeoutDirectives.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/FrameRenderer.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, akka-parsing/src/main/scala/akka/parboiled2/CharPredicate.scala, akka-parsing/src/main/scala/akka/parboiled2/ErrorFormatter.scala
- match may not be exhaustive.
- Unused import.
- Invalid implicitNotFound message.
- Adapting argument list.
- method copyArrayToImmutableIndexedSeq in class LowPriorityImplicits2 is deprecated.
- Adding a number and a String is deprecated.
=> Reduced some scalac warnings.

akka-http-compatibility-tests/src/test/scala/akka/http/scaladsl/server/directives/CompatFormFieldSpec.scala, build.sbt
And add missing dependency on akka-stream to make it compile with Scala 2.11
Refs #2612
=> Ignore FormFieldDirective incompatibility in 2.13

akka-http-core/src/main/scala/akka/http/scaladsl/ConnectionContext.scala
Besides being wrong, this caused issues with genjavadoc 0.11
=> Merge double javadoc

build.sbt
Otherwise, it fails while building nightlies against akka sources.
=> pro: use established style for depending on akka modules for compat tests

akka-http/src/main/scala/akka/http/scaladsl/server/HttpApp.scala, akka-http/src/main/scala/akka/http/scaladsl/server/Route.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RouteResult.scala
ExecutionContextExecutor is a subclass of ExecutionContext.
```scala
handlerFlow(implicit executionContext: ExecutionContextExecutor)
```
can not find `route2HandlerFlow`s `executionContext: ExecutionContext`
e.g
```scala
implicit val strAny: AnyRef = "str"
def foo (implicit str: String = null) = str
foo// null
```
=> When route2HandlerFlow calls handlerFlow, executionContext is always null.

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/PathDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/UnmarshallingSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/PathMatcher.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/PredefinedFromStringUnmarshallers.scala
Widen JavaUUID regex's (again) to allow for old and future variants of uuid's (described in chapter 4.1.1 of [RFC 4122](https://tools.ietf.org/html/rfc4122).
Following-up after #2569 and #2596. Thanks to @plokhotnyuk for pointing this out in https://github.com/spray/spray-json/pull/313.
=> Widen JavaUUID regexp's

akka-http-core/src/main/mima-filters/10.1.9.backwards.excludes/issue-2603-lift-transformDataBytes.excludes, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala
It can work on any kind of entity and will always return a Universal entity.
Refs #2603.
=> core: pull transformDataBytes(newContentLength, transformer) up to HttpEntity

akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-core/src/main/scala/akka/http/impl/util/package.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerTestSetupBase.scala
I.e.
* when materializing the response entity stream fails: return a 500 response
* when streaming itself fails: abort the connection 
Refs #848, #894.
=> Better error handling on server when response entity stream fails

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala
Refs #962
This is basically a generalization of #1337 to handle all unhandled exceptions during unmarshalling as a `MalformedRequestContentRejection`.
=> http: reject with MalformedRequestContentRejection if formFieldSeq cannot unmarshal to form

akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
For some reason 2.11.12 cannot pick up the implicit system provided by the
super class at this position.
=> Fix compilation in 2.11

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/pool/SlotStateSpec.scala
Otherwise, those connections might hang around for a while when a request is ongoing and the client flow isn't expecting or reacting to completion or cancellation.
=> Force connection closure when pool is stopped

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ServerProcessingBenchmark2.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
Currently, it seems streamed response are ~1 order of magnitude slower at least. I guess some of that is somewhat expected as streaming is a memory optimization and not a performance optimization. Might still make sense to optimize if there are any low-hanging fruit. Also the benchmark will be used to look out for regressions.
=> Add benchmark to compare strict vs streamed response types

project/Doc.scala
Add canonical URLs in Scaladoc and use the more accurate links to source code.
=> Scaladoc: link to source and canonical

build.sbt, project/AkkaDependency.scala
The idea is to add another build step in nightlies that exercises those tests, so we'll catch binary incompatibilities (i.e. ones we might otherwise miss because they are fixed by recompiling against akka master) like #2651 early on.
Currently, only akka-http-core tests would be included in those tests but just that would already add a lot of coverage to that case.
=> build: add command line flag that allows running akka-http-core tests against akka master branch

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
Also report underlying reason for response entity failure when materialization times out.
Follow up to #2630.
=> Reduce number of stages needed to implement CaptureMaterializationAndTerminationOp

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CodingDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/coding/Decoder.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/CodingDirectives.scala
That happened since the error wrapping logic was moved to Decoder (in #2185) and
now also used for the client side where error handling logic might use
`dicardEntityBytes` which only then triggered the error logging by trying
to read the stream again which would send a "Substream Source cannot be
materialized more than once" exception through the stream which would then
tried to be "recovered" but rethrowing in `recover` would trigger that noisy
error log.
Using `mapError` instead and moving the error handling logic back, prevents
the extra logging. The error is still propagated through the stream.
=> Prevent extra error log messages when decoded HttpMessage stream fails

project/Doc.scala
=> docs: disable unsupported `-doc-canonical-base-url` for Scala 2.11

docs/src/main/paradox/routing-dsl/testkit.md
The old one (19) results in:
sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.akka#akka-stream-testkit_2.13;2.5.19: not found
References #xxxx
=> fix: akka-stream-testkit version

build.sbt, project/Common.scala
Refs #2673
Tested with javap (`javap -p -c akka-http-core/target/scala-2.12/classes/akka/http/impl/engine/parsing/HttpHeaderParser\$.class | grep clear` should be `Method java/nio/ByteBuffer.clear:()Ljava/nio/Buffer;` and not `Method java/nio/ByteBuffer.clear:()Ljava/nio/ByteBuffer`).
Also tested with cinnamon, also looks good.
=> Always target java 8 bootclasspath

akka-http-marshallers-scala/akka-http-xml/src/main/scala/akka/http/scaladsl/marshallers/xml/ScalaXmlSupport.scala
Should fix the JDK 11 compilation failures in https://jenkins.akka.io:8498/job/akka-http-nightly/608/.
=> xml: import constants from com.sun.org.apache.xerces.internal.impl.Constants

docs/src/main/paradox/routing-dsl/index.md, docs/src/test/scala-2.12+/docs/http/scaladsl/HttpServerWithTypedSpec.scala
Quick fix to fix the build against akka master.
Maybe we should backport some of the toClassic methods to release-2.5 branch since it's causing these kind of problems?
=> Temporary fix for Typed doc sample code

.scala-steward.conf
So that if we enable it it won't send PR's to upgrade Akka
=> Add scala-steward config to exclude akka

build.sbt, project/Dependencies.scala
PR https://github.com/akka/akka-http/pull/2671 bumps the `jackson-databind` version to 2.9.9. However, this version is susceptible to CVE-2019-14439 (original issue: https://github.com/FasterXML/jackson-databind/issues/2389). While the vulnerability might not be directly exploitable from Akka HTTP, it might still pose a problem for projects pulling it in as a transitive dependency.
This PR bumps `jackson-databind` further, to its latest stable version, 2.9.9.3.
FYI, there are three more CVE's of this kind present in all versions of `jackson-databind`, including this one - they will be fixed in the forthcoming 2.10.0 release:
https://github.com/FasterXML/jackson-databind/issues/2410
https://github.com/FasterXML/jackson-databind/issues/2420 …
=> CVE-2019-14439: bump jackson-databind to 2.9.9.3

akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/GenericUnmarshallers.scala
Alternatives could be:
* deprecate the eitherMarshaller (since trying out several unmarshallers in
sequence, might not be what you want in any case)
* auto `toStrict`, that would require to pull out a toStrict timeout out
of thin air
Refs #618
=> http: fail eitherUnmarshaller when entity is not strict

akka-http-marshallers-scala/akka-http-spray-json/src/main/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupport.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/marshallers/xml/ScalaXmlSupportSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/EntityStreamingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MarshallingDirectivesSpec.scala, akka-http/src/main/scala/akka/http/javadsl/server/Rejections.scala, akka-http/src/main/scala/akka/http/javadsl/unmarshalling/Unmarshaller.scala, akka-http/src/main/scala/akka/http/scaladsl/common/StrictForm.scala, akka-http/src/main/scala/akka/http/scaladsl/server/Rejection.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FramedEntityStreamingDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/MarshallingDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/MultipartUnmarshallers.scala, akka-http/src/main/scala/akka/http/scaladsl/unmarshalling/Unmarshaller.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/JsonStreamingExamplesSpec.scala
Rebased/formatted version of https://github.com/akka/akka-http/pull/1713
Refs #1691
=> Add logging unsupported content type

akka-http-core/src/main/scala/akka/http/scaladsl/model/StatusCode.scala, docs/src/main/paradox/release-notes/10.1.x.md
Disallow entity for 205 status code as response with this status code [should contain empty content](https://tools.ietf.org/html/rfc7231#section-6.3.6).
References #2685
- Now you cannot pass HTTP entity to response with 205 status code
Set `allowsEntity` as `false` would be the simplest way of following RFC spec.
=> Disallow entity for 205 status code

akka-http-core/src/main/mima-filters/10.1.9.backwards.excludes/pr-2706-add-http2-setting-outgoing-control-frame-buffer-size.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/javadsl/settings/Http2ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Fixes CVE-2019-9512, CVE-2019-9514, CVE-2019-9515.
=>  http2: backpressure incoming frames when too many outgoing control frames are buffered

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderDecompression.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
I guess no one has noticed so far because it only shows starting from HEADER blocks with more than 2 * frame size.
=> http2: fix receiving HEADERS with more than one CONTINUATION frame

akka-http-core/src/main/mima-filters/10.1.9.backwards.excludes/response-rendering-performance-improvements.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/RenderSupport.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala
Culprits were `Future.failed` and `Source.concat`. This improved speed for streamed responses from ~20x slower to only ~10x slower than strict responses (which is still a lot).
=> Streamed response processing performance improvements

project/ValidatePullRequest.scala
I just turned on the PR validation reports I developed a long time ago (which needed a fix in the jenkins github pr validator plugin which was released only a long time afterwards). To prevent too much clutter this PR collapses the report by default.
=> build: collapse PR validation report for less clutter

build.sbt
Fixes #2747. Might obsolete #2754.
=> build: make sure to lift all akka dependencies to source when test-against-akka-master is used

project/AkkaDependency.scala
Follow up to #2758, obsoletes #2754.
=> build: rename `akka.build.version` env var not to clash with the one in the akka build

akka-http-core/src/test/scala/akka/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala
=> core: fix LowLevelOutgoingConnectionSpec which has subtly different behavior in Akka 2.5 and 2.6

akka-http-tests/src/test/java/akka/http/javadsl/server/JavaRouteTest.java, docs/src/main/paradox/routing-dsl/path-matchers.md
Refs #2749
Also added a test making sure the regex matching is in fact accessible from Java.
=> Doc fix for regex paths from Java 

project/ValidatePullRequest.scala
Fixes the wrong validation report collapsing observed in https://github.com/akka/akka-http/pull/2753#issuecomment-541599194.
=> build: move </details> to the right place in validation report

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpEntitySpec.scala
To support trailing headers in `akka.http.scaladsl.model.HttpEntity.Chunked#transformDataBytes` to improve compatibility with akka-grpc which is setting trailing header (gRPC status) in `akka.http.scaladsl.model.HttpEntity.Chunked`.
When data of such an entity is about to be processed with `akka.http.scaladsl.model.HttpEntity.Chunked#transformDataBytes`  we get `IllegalArgumentException("Chunked.transformDataBytes not allowed for chunks with metadata") `
References #2218 #45 #1869
If the subject of data transormation - `akka.http.scaladsl.model.HttpEntity.chunks` is containing the chunk with trailing headers concatenate it to the chunks which are the result of data transformation with `akka.http.scaladsl.model.HttpEntity.Chunked#transformDataBytes`
I'm instrumenting akka-grpc calls with …
=> core: support chunked trailing headers in transformDataBytes

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/WithPriorKnowledgeSpec.scala
Fixes #2734 and #2782.
Probably TCP frames were coalesced so multiple frames were received in one go
which wasn't expected. The new Http2FrameProbe can deal with that more
gracefully.
=> In WithPriorKnowledgeSpec and H2cUpgradeSpec, use new Http2FrameProbe for analyzing frames

docs/src/main/paradox/release-notes/10.1.x.md
Clarify 10.1.10 has a fix to make it work with Akka 2.6
=> Fix/amend 10.1.10 release notes formatting

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ws/MaskingBench.scala, akka-http-bench-jmh/src/main/scala/akka/http/scaladsl/unmarshalling/sse/LineParserBenchmark.scala, akka-http-core/src/main/scala/akka/http/impl/engine/ws/FrameEventParser.scala
On top of #2780 
It now masks 4 bytes together and also avoids an extra buffer copy at the end by using `ByteString.fromArrayUnsafe`.
(It cannot fix the 2.13 performance problem because ByteString.toArray is still used)
=> Improve WS masking performance

akka-http-core/src/main/java/akka/http/javadsl/model/StatusCodes.java, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/StatusCode.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-tests/src/test/java/akka/http/javadsl/server/directives/MiscDirectivesTest.java, akka-http-tests/src/test/java/akka/http/javadsl/server/directives/RouteDirectivesTest.java, akka-http-tests/src/test/scala/akka/http/scaladsl/server/SizeLimitSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MiscDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala, docs/src/test/java/docs/http/javadsl/server/directives/MiscDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/MiscDirectivesExamplesSpec.scala
For status codes 413, 414 and 416 older names from older RFCs are currently used, I updated them to follow the naming in RFC 7231 and RFC 7233. 
For status code 505 the Scala naming convention was not followed. 
I deprecated the older names.
I decided to leave `OK` (which also doesn't follow the naming convention) as is, because that probably would mean a lot of changes downstream.
=> Update naming for status codes 413, 414, 416 and 505

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala, akka-http-core/src/test/scala/akka/http/javadsl/JavaInitializationSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpEntitySpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/DebuggingDirectivesSpec.scala
Aimed to avoid PII and SPI leakage, partially tackles https://github.com/akka/akka-http/issues/2409
References https://github.com/akka/akka-http/pull/2560
References https://github.com/akka/akka-http/pull/2412
References https://github.com/akka/akka-http/issues/2409#issuecomment-496417344
References https://github.com/akka/akka-http/pull/2412#pullrequestreview-207325113
This PR makes `HttpEntity.Strict#toString` method to print just the entity content type and its contents size. Replacing the previous behaviour which included the whole contents (or their beginning if they were excessively long).
https://github.com/akka/akka-http/pull/2560#pullrequestreview-285451541
> avoid including body data from strict entities (not a good idea anyways)
=> core: hide `HttpEntity.Strict` body data by default

akka-http-tests/src/test/scala/akka/http/scaladsl/server/RejectionSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala
This PR fixes a message which the default rejection handler produces for `UnsupportedRequestContentTypeRejection`. With this PR the message looks something like
```
The request's Content-Type [image/bmp] is not supported. Expected:
image/jpeg or image/png
```
if the corresponding rejection has the `contentType` option defined or
```
The request's Content-Type is not supported. Expected:
image/jpeg or image/png
```
if the `contentType` option is set to `None`.
In case if `UnsupportedRequestContentTypeRejection` doesn't provide supported content type ranges,
the rejection message will look like:
```
The request's Content-Type [image/bmp] is not supported.
```
References #2804
* The default `RejectionHandler`'s error message for `UnsupportedRequestContentTypeRejection` is changed.
=> http: fix default rejection message for unsupported content type (#2804)

project/Publish.scala
Though it still doesn't work for the docs due to
https://github.com/lightbend/paradox/issues/387
=> Allow publishing from a folder with spaces

akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolInterface.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Fixes #2728
* idle timeout messages are now DEBUG level
* when pool slot is idle, use regular stream completion when pool is shutdown
=> core: silence noisy pool idle timeout messages

project/Dependencies.scala, project/MiMa.scala
Fix #2819
The real issue is that nightlies were using `++2.13.0` last night.
=> build: use more resilient checking for Scala 2.13 in Mima

akka-http-core/src/main/scala/akka/http/scaladsl/model/ErrorInfo.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
=> Improve EntityStreamSizeException message

build.sbt
Before we kept it disabled because it messed with sbt-dependency-graph but
that should now be fixed with sbt 1.3.4.
=> build: enable coursier

project/project-info.conf
project-info.jar does not work (https://github.com/lightbend/sbt-paradox-project-info/issues/15),
but linking to `current` is probably better for SEO reasons anyway.
=> Fix project-info links to API docs

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpResponseParser.scala
I spotted this while reviewing some code https://github.com/akka/akka-http/pull/2503/files/fa1e4241b004a2c92d0513a1a9a55ab00b811f0c#diff-934eaac30edce2e74265c0760314da50 
No longer catch exceptions that are fatal to the JVM. 
References  https://github.com/akka/akka-http/pull/2503/files/fa1e4241b004a2c92d0513a1a9a55ab00b811f0c#diff-934eaac30edce2e74265c0760314da50
=> = only catch NonFatal Exceptions

.travis.yml
As Johan noted in https://github.com/akka/akka-grpc/pull/782#issuecomment-572103694 there is some confusion which directory coursier uses. According to https://get-coursier.io/docs/cache.html#compatibility-with-former-versions
`~/.coursier` is the old directory while `~/.cache/coursier` is the new one. When only the old one is found it will continue to use the old one. It seems just adding the entry here before made it use the old one. But let's use the new one to be safe in the future.
=> build: cache modern coursier cache directory in travis

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> http2: fix HeaderCompression updating table size without giving notice to peer

docs/src/main/paradox/routing-dsl/directives/misc-directives/extractClientIP.md
update the document as this can be a common error developers may make.
=> docs: add warning on usage on extractClientIP

build.sbt
It seems coursier isn't able to correctly determine the dependencies when
internal and external dependencies with the same coordinates are mixed in
different configurations.
Since we will drop support for 2.5 on master, let's only add this workaround for the release-10.1 (still need to setup nightlies for that).
Fixes #2909.
=> build: disable coursier when `akka.http.test-against-akka-master` is enabled

docs/src/main/paradox/introduction.md
Update the Auction example for the Introduction documentation to include quotes around the curl request.
* References https://github.com/akka/akka-http/issues/2915
* Added quotes around the url in `curl -X PUT http://localhost:8080/auction?bid=22&user=MartinO` (to `curl -X PUT "http://localhost:8080/auction?bid=22&user=MartinO"`
=> Add quotes to curl request with parameters

akka-http-core/src/main/scala/akka/http/impl/model/parser/CommonActions.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/ContentTypeHeader.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
=> core: identify Content-Type `charset` parameter even if not lower case

akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
=> core: remove some instances of failing `temporaryServerHostnameAndPort` usages in test

akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/TestFrameworkInterface.scala, akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/ScalatestRouteTestSpec.scala, akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/Specs2RouteTestSpec.scala
If we use fail() or an assertion fails inside a route the test won't be
marked as failed. Instead 500 response will be returned. Custom
ExceptionHandler rethrowing TestFailedException fixes this problem.
Refs #2818
=> Handle test exceptions separately from regular exceptions

akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala, akka-http-core/src/main/scala/akka/http/javadsl/Http.scala
An alternative to #2894 for this particular case.
=> core: introduce Inherited.upcast to fix warning in javadsl.Http

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala
To avoid unsafe access of `connectionEstablished`
=> core: nest correctly in NewHostConnectionPool

akka-http-core/src/main/mima-filters/10.1.11.backwards.excludes/2965-introduce-client-stream-cancellation-setting.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/settings/ClientConnectionSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ClientConnectionSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ClientConnectionSettings.scala, akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
Divide and conquer of the (too) big change in #2678.
Finally fixes #2349, the longest-standing recurrent failure.
=> Fix cancellation race conditions on the client-side

akka-http-core/src/main/java/akka/http/javadsl/model/AttributeKey.java, akka-http-core/src/main/java/akka/http/javadsl/model/HttpMessage.java, akka-http-core/src/main/mima-filters/10.1.11.backwards.excludes/1500-attributes.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/util/JavaMapping.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/AttributeKey.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala, akka-http-core/src/test/java/akka/http/javadsl/model/HttpMessageTest.java, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpMessageSpec.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTestResultComponent.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/RejectionSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/BasicDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/MethodDirectives.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, docs/src/main/paradox/common/http-model.md, docs/src/test/java/docs/http/javadsl/ModelDocTest.java, docs/src/test/scala/docs/http/scaladsl/ModelSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/BasicDirectivesExamplesSpec.scala, project/plugins.sbt
In this draft, attributes are identified by AttributeKey instance. Explicitly
naming the keys doesn't seem necessary, as they are 'internal' and never
serialized.
Refs #1500, contrast with #2872
If we decide to go with this approach we should also add directives to extract
attributes by key.
=> Support for request/response message attributes

akka-http-testkit/src/main/scala/akka/http/javadsl/testkit/RouteTest.scala, docs/src/test/java/docs/http/javadsl/server/directives/FileUploadDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/FileUploadDirectivesExamplesSpec.scala
References #2733 (#2930 is a duplicate of it) and #2691
As the code comment says:
`  // test touches disk, so give it some time`
so let's give it a little more time.
=> Reduce flakiness of FileUploadDirectivesExamples (Test and Spec)

docs/src/test/java/docs/http/javadsl/server/directives/FutureDirectivesExamplesTest.java
References #2952 
A pause (GC, noisy neighbor) before:
https://github.com/akka/akka-http/blob/7683d53d97ed6878ac132c6575a714b199db14ba/docs/src/test/java/docs/http/javadsl/server/directives/FutureDirectivesExamplesTest.java#L161
allows the circuit breaker to close again. Increasing the `resetTimeout` should reduce the odds.
=> Increase the resetTimeout to assert the circuit breaker is open

akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala
Fixes #1280
Doesn't add much coverage but confirms that #1280 can now be closed with @raboof's recent fix.
=> core: more examples of strictly invalid chars in URI querie

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
The special condition is that the previous request got an early response and
the connection afterwards broke while waiting for the rest of the request.
Fixes #1439
=> core: don't fail slot after previous connection failed in special condition

akka-http-core/src/main/scala/akka/http/impl/settings/ParserSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ParserSettings.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteAdapter.scala, akka-http/src/main/scala/akka/http/scaladsl/server/Route.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RouteResult.scala, docs/src/main/paradox/migration-guide/index.md, docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
Refs #70
~Before merging should be updated not to take a `Materializer` implicit but instead use either #2886 or https://github.com/akka/akka/pull/28494~
~Before merging we need either a release of Akka 2.5.30 (that contains https://github.com/akka/akka/pull/28545) or #2886~
This is ready to go!
=> Simplify route2HandlerFlow

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
Since by default headers are stored in a list, we would slowly append to the
list. It's questionable whether List is the right datastructure here but
that can be changed separately if needed.
Fixes #3028
=> core: prepend headers in `HttpMessage.addHeader`

akka-http-core/src/test/scala/akka/http/impl/util/WithLogCapturing.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CodingDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MiscDirectivesSpec.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/scaladsl/Http2ServerTest.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/FileUploadDirectivesExamplesSpec.scala
Refs #2957
When grpccurl is used on a Akka gRPC server that does not support server
reflection, we send a 404, and grpcurl sends a RST with error code
PROTOCOL_ERROR.
We definitely didn't handle the RST correctly in that scenario. This PR
fixes handling the RST.
Separate from this PR, we should also investigate why grpcurl is sending
a PROTOCOL_ERROR: this indicates a HTTP/2 protocol-level error, while us
sending a 404 is an application-level error. It might be that grpcurl is
just incorrectly sending a PROTOCOL_ERROR here, or that we're in fact doing
something else wrong that triggers it.
The test is not very nice, but I don't see another way.
=> Accept RST on an already-half-closed HTTP/2 stream

.travis.yml
Otherwise, git in travis will not know about tags sufficiently far in the
past and version numbers will be weird.
Fixes #3043
=> build: configure travis git depth to fix sbt-dynver

akka-http-core/src/main/scala/akka/http/javadsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, project/AkkaDependency.scala
Upgrade to Akka 2.5.31.
So that `ClassicActorSystemProvider` can be used to accept both classic and new actor systems to create the Akka HTTP extensions.
Methods with `akka.actor.ActorSystem` are kept for bin-compatiblity.
=> Akka 2.5.31; accept ClassicActorSystemProvider in extensions

akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala, akka-http-core/src/test/java/akka/http/javadsl/model/UriTest.java, akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala
This still doesn't mean `Uri("") == Uri("?")`, because we'd like to keep
the distinction between "no query" and "empty query" (at least for historical
reasons).
Fixes #2769
=> core: parse empty query `?` to Query.empty

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/HeaderParserBenchmark.scala
See https://github.com/akka/akka-http/commit/41788d857c11a711eb07dff8b0ec1654b20e367e#r38505067
Without re-introducing warning about access
```
[warn] /home/aengelen/dev/akka-http/akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/HeaderParserBenchmark.scala:25:7: variable parser in class HeaderParserBenchmark references private[engine] class HttpHeaderParser.
[warn] Classes which cannot access HttpHeaderParser may be unable to override parser_=.
[warn]   var parser: HttpHeaderParser = _
[warn]       ^
[warn] one warning found
```
=> Fix HeaderParserBenchmark

akka-http-core/src/main/scala/akka/http/impl/model/parser/SimpleHeaders.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, build.sbt, docs/src/main/paradox/client-side/client-https-support.md, docs/src/main/paradox/common/sse-support.md, docs/src/main/paradox/contributing.md, docs/src/main/paradox/handling-blocking-operations-in-akka-http-routes.md, docs/src/main/paradox/migration-guide/migration-from-old-http-javadsl.md, docs/src/main/paradox/routing-dsl/HttpApp.md, docs/src/main/paradox/routing-dsl/directives/cache-condition-directives/conditional.md, docs/src/main/paradox/routing-dsl/directives/form-field-directives/formField.md, docs/src/main/paradox/routing-dsl/directives/form-field-directives/formFieldMap.md, docs/src/main/paradox/routing-dsl/directives/form-field-directives/formFieldMultiMap.md, docs/src/main/paradox/routing-dsl/directives/form-field-directives/formFieldSeq.md, docs/src/main/paradox/routing-dsl/directives/form-field-directives/formFields.md, docs/src/main/paradox/routing-dsl/directives/security-directives/authenticateOrRejectWithChallenge.md, docs/src/main/paradox/routing-dsl/directives/security-directives/index.md, docs/src/main/paradox/routing-dsl/directives/websocket-directives/handleWebSocketMessagesForOptionalProtocol.md, docs/src/main/paradox/routing-dsl/exception-handling.md, docs/src/main/paradox/routing-dsl/overview.md, docs/src/main/paradox/routing-dsl/source-streaming-support.md, docs/src/main/paradox/routing-dsl/testkit.md, docs/src/main/paradox/security/2017-01-23-denial-of-service-via-leak-on-unconsumed-closed-connections.md, docs/src/main/paradox/server-side/http2.md, docs/src/main/paradox/server-side/index.md, docs/src/main/paradox/server-side/low-level-api.md
* Change links to point to the final destination.
* Prefer https where possible.
Most important thing left is rewriting the API doc links to JDK 11 Javadocs which require to add the `java.base` module.
=> Docs: reduce redirects, prefer https

akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/ByteStringSinkProbe.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Otherwise, the response entity stream can leak when the response
rendering stage is completed by a failure instead of by the
associated cancellation.
Currently, it seems failures like this seem to be rare to reach this point
and cancellation usually wins the race (or failures are converted into
completions).
Discovered while working on #3022 and extracted here.
Should be backported to 10.1.x.
=> core: make sure to cancel response entity on failure

akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/ByteStringSinkProbe.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> [backport] core: make sure to cancel response entity on failure (#3046)

project/AkkaDependency.scala, project/VersionGenerator.scala
To allow building against a 2.5 snapshot while running
(the tests) against 2.6. Without this change the
`AkkaVersion.require("akka-http", akka.http.Version.supportedAkkaVersion)`
check would fail at run time because it can't parse the 2.5 snapshot.
=> Specify a non-snapshot minimum expected Akka version

akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/configure-parsing-error-response.backwards.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/ParsingErrorHandler.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
Refs #210
A bit unfortunate that ServerSettings includes the class name and
not the object, but to instantiate the class it'd be good to use
system.dynamicAccess and that is not available when creating the
settings...
=> Allow customizing parsing errors

akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/configure-parsing-error-response.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala
Fixes a compilation error in bench-jmh tests.
WDYT, @raboof. This is not necessarily better than your previous solution as it requires two casts to get there. On the other hand it's nice to be able to keep the signatures in HttpServerBluePrint clean and do things where they are needed.
=> core: move ParsingErrorHandler creation to ControllerStage

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/framing/Http2FramingSpec.scala
References https://github.com/akka/akka-http/pull/2039
I ran into that when bumping Envoy, running in front of my `akka-grpc` service, from 1.13.0 to 1.14.1. 
```
15:40:39.584 [debug] a.i.TcpListener - New connection accepted
15:40:39.602 [debug] a.h.i.e.h.Http2ServerDemux - Changing state from Idle to WaitingForNetworkToSendControlFrames
15:40:39.603 [debug] a.h.i.e.h.Http2ServerDemux - Changing state from WaitingForNetworkToSendControlFrames to Idle
15:40:39.603 [debug] a.h.i.e.h.Http2ServerDemux - Changing state from Idle to WaitingForData
15:40:39.608 [debug] a.a.RepointableActorRef - Aborting tcp connection to /127.0.0.1:35878 because of upstream failure: akka.stream.impl.io.ByteStringParser$ParsingException: Parsing failed in step …
```
=> gracefully discard unsupported h2 SETTINGS

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/framing/Http2FramingSpec.scala
backport of #3053
* gracefully discard unsupported h2 SETTINGS
* remove wildcard import to avoid misuse of loosely-typed isKnownId()
=> backport: gracefully discard unsupported h2 SETTINGS

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ParameterDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/PathDirectivesSpec.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/FormFieldDirectives.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/ParameterDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/common/NameReceptacle.scala, akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/MethodDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/ParameterDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/SecurityDirectives.scala, docs/src/main/paradox/routing-dsl/directives/form-field-directives/formFields.md, docs/src/main/paradox/routing-dsl/directives/index.md, docs/src/main/paradox/routing-dsl/directives/parameter-directives/parameters.md, docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/CaseClassExtractionExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/FormFieldDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/ParameterDirectivesExamplesSpec.scala
As Scala symbols lose their language support in Scala 2.13 users should switch to using regular strings in the parameters and form fields directives.
The `String.*` enhancement conflicts with the `StringOps.*` enhancement from `Predef` (see #3081), so with Strings users must switch to the new `.repeated` enhancer.
* Complement the symbolic methods with regular method names in `NameReceptacle` and `NameUnmarshallerReceptacle`
* The names mimic the names used in the Java DSL
* Remove the use of Scala symbols in the docs.
=> Routing DSL: Names for to symbolic enhancements

docs/src/test/scala/docs/http/scaladsl/server/CaseClassExtractionExamplesSpec.scala
The changes in #3082 did not compile with Scala 2.13. When case class extraction uses `apply` it must use `_` to work.
Incidentally fixes #3000
=> Docs: Make Case class extraction work with 2.13

akka-http-tests/src/test/scala/akka/http/javadsl/DirectivesConsistencySpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/PathMatcher.scala, docs/src/main/paradox/routing-dsl/path-matchers.md
Introduce `slash`, `or`, `and`, `append`, `optional` and `not` for path matching.
References #3082, #3085
I don't think we should promote these, just offer the alternative.
`~` becomes `concat` for routes, here I picked `append` as `concat` is a varargs method to combine multiple routes.
=> Routing DSL: Allow names to match paths

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Protocol.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/model/http2/Http2SettingsHeader.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameProbe.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/framing/Http2FramingSpec.scala
Follow-up of https://github.com/akka/akka-http/pull/3053#discussion_r408714500
The first commit tries to simplify the existence/lookup flow for spec elements, forcing a more graceful handling of unknown frame types & error codes (with a slightly different approach for error codes where I guess it's interesting to capture the code, even if it's not strongly typed).
=> h2 frame parsing: improve handling of unknown values

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/package.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
Backport of #2962
Fix #1484 for 10.1.x
(cherry picked from commit 78ec8a81f9c83e7d1d24ff3a34507ff31ad70d64)
=> [backport] core: fix parsing of partly cached headers with UTF-8 values

project/Common.scala, project/Dependencies.scala
Introduce the scalac silencer to silence warnings for argument adaptation (auto tupleing) as they risk to hide other (for the time being) more relevant warnings.
Depending on the solutions to #2738 we would remove this again.
=> Build: silence warnings for argument adaptation

akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/internal-RenderSupport-changes.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/RenderSupport.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala
Slight performance improvements:
* precompute some often used string combinations
* in `ModeledHeader` avoid `~~` syntax and use direct call instead
=> core: header rendering with less indirection

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpHeader.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala, akka-parsing/src/main/scala/akka/parboiled2/CharPredicate.scala
Slight performance improvement.
That's because Function1 is not specialized for Char so there's boxing involved
(if not elided by the JVM). The solution is provide an explicit
specialized apply method instead.
=> parsing: don't extend from Char => Boolean for CharPredicate

docs/src/main/paradox/routing-dsl/directives/parameter-directives/parameters.md, docs/src/main/paradox/routing-dsl/index.md, docs/src/main/paradox/routing-dsl/overview.md, docs/src/main/paradox/routing-dsl/play-comparison.md, docs/src/main/paradox/routing-dsl/routes.md, docs/src/test/java/docs/http/javadsl/server/testkit/PlayRoutesComparisonTest.java, docs/src/test/scala/docs/http/scaladsl/server/PlayRoutesComparisonSpec.scala
Add a page in the routing docs which shows the examples from the Play docs in Akka HTTP notation with accompanying tests.
References #2980
=> Docs: routing DSL compared with Play routes

build.sbt, docs/src/main/paradox/introduction.md, docs/src/main/paradox/routing-dsl/testkit.md, project/AkkaDependency.scala
Show the Akka version as a parameter in the dependency examples.
=> Docs: show symbolic Akka verson for dependencies

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala, akka-http-core/src/main/scala/akka/http/impl/util/ByteStringParserInput.scala, akka-parsing/src/main/scala/akka/parboiled2/Parser.scala, akka-parsing/src/main/scala/akka/parboiled2/RuleDSLBasics.scala
Seems to be a big performance improvement because the ValueStack in the UriParser can so be reused and doesn't have to be reallocated for each request.
=> Reuse UriParser In HttpRequestParser

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala, docs/src/main/paradox/release-notes/10.1.x.md, docs/src/main/paradox/server-side/http2.md, project/Dependencies.scala
Crash if incompatible versions of JDK and jetty-alpn-agent are detected
10.1 version of #3117:
* make it work on JDK 8 >= 8u252
* fail if incompatible versions are detected
* add a note to release notes
=> [release 10.1] http2: support ALPN natively on JDK >= 8u252

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/scaladsl/Http2ServerTest.scala, build.sbt, docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md, docs/src/main/paradox/release-notes/10.1.x.md, docs/src/main/paradox/server-side/http2.md, project/Dependencies.scala
Refs #3100
Not quite done, we need to decide if we want to 
* drop HTTP2 support for JDK < 8u251 (and jetty-alpn agent)
* still try to use jetty-alpn on JDK >= 8u251 if it's available (seems to be dangerous as jetty-alpn will replace SSL classes for which it is not clear whether they really support those newer JDKs)
Also needs appropriate changes in the documentation.
I tend to say that we should drop jetty-alpn support for 10.2.0 and just require a recent JDK 8 if you want to use HTTP/2. This requirement will transitively propagate to akka-grpc as well so that should be taken into account as well.
=> Support native ALPN in JDK >=8u251

akka-http-core/src/test/scala/akka/http/impl/engine/client/ClientCancellationSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/impl/util/AkkaSpecWithMaterializer.scala, akka-http-core/src/test/scala/akka/http/impl/util/ExampleHttpContexts.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
Currently fails, pushing that here to make sure I remember to fix it enventually.
=> Use SystemMaterializer in AkkaSpecWithMaterializer

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/BodyPartParser.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/MultipartUnmarshallersSpec.scala
10.1 Backport of #3076
Refs #2581
* Improved the heuristic for detecting end of line character(s)
* Added tests for UndefinedEndOfLineConfiguration
Co-authored-by: Johannes Rudolph <johannes.rudolph@gmail.com>
(cherry picked from commit 428877e9143246cf937ad7c944ffb19c676eacc6)
=> [backport] core: fix EOL detection for body part parsing

akka-http-core/src/test/scala/akka/http/impl/engine/client/ClientCancellationSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/impl/util/AkkaSpecWithMaterializer.scala, akka-http-core/src/test/scala/akka/http/impl/util/ExampleHttpContexts.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
Tests in master are broken due to merging outdated #3075.
This reverts commit 15f108c25a6e121c81097a14d78bf4b4556ecea5.
Let's merge this to unblock master again and I'll see what happened.
=> Revert "SystemMaterializer in AkkaSpecWithMaterializer (#3075)"

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala
Even if that method is now in JDK 8u252, JDK 11 doesn't know about that and
fails compilation with `--release 8` because of that.
So, we go back to using this method with reflection. It's only called once
per SSLEngine/connection, so the overhead is negligible.
Will fix the JDK 11 nightlies.
Refs #3135
=> http2: use reflection for accessing `setHandshakeApplicationProtocolSelector`

akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/ClientCancellationSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/impl/util/AkkaSpecWithMaterializer.scala, akka-http-core/src/test/scala/akka/http/impl/util/ExampleHttpContexts.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala
We had to revert this before in #3145 because ClientServerSpecs started to fail in relation
with another change. The fix was to make sure to shut down all
connection pools in the end of tests that used Http().singleRequest.
=> core: use SystemMaterializer in AkkaSpecWithMaterializer

akka-http-core/src/main/scala/akka/http/impl/engine/parsing/BodyPartParser.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/MultipartUnmarshallersSpec.scala
* Improved the heuristic for detecting end of line character(s)
* Added tests for UndefinedEndOfLineConfiguration
References #2581
=> Fix request body line parsing: Issue #2581

docs/src/main/paradox/release-notes/10.1.x.md, scripts/release-train-issue-template.md
Otherwise, the current version of the docs might not contain all release notes
when we release a final from master.
Also added a line to the release train template to do that for previous versions.
=> Forward port of 10.1.12 release notes

akka-http-core/src/main/java/akka/http/javadsl/model/headers/RemoteAddress.java, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MiscDirectivesSpec.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, docs/src/test/java/docs/http/javadsl/server/directives/MiscDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/MiscDirectivesExamplesSpec.scala
Migration note is already part of #3173
Refs #2924
=> Deprecate Remote-Address header

akka-http-core/src/main/mima-filters/10.1.11.backwards.excludes/2560-hide-body-and-headers-in-tostring.excludes
References https://github.com/akka/akka-http/pull/2560
In the aforementioned PR, the file `akka-http-core/src/main/mima-filters/10.1.11.backwards.excludes/2560-hide-body-and-headers-in-tostring.excludes` was added as part of a previously used solution in the same PR.
It is not longer necessary and therefore this _housekeeping_ change.
=> Remove unnecessary backward compatibility exclusion

project/Common.scala
This warning will be with us until we drop support for 2.12.
We could also consider introducing 'ccompat' wrappers for this, but I'm not
sure it's worth it.
=> Silence JavaConverters warnings

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpHeader.scala
Follow up to #2560
To avoid accidental overriding in complex inheritance scenarios.
That would prevent that people override it e.g. in cases where only some information is sensitive and they want to report the rest. So, I'm not completely sure, it's a good idea.
=> core: mark SensitiveHttpHeader.toString as final

akka-http/src/main/mima-filters/10.1.x.backwards.excludes/remove-deprecated-javadsl-Route-seal.excludes, akka-http/src/main/scala/akka/http/javadsl/server/Route.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteAdapter.scala
Has been deprecated in 10.1.1 a long time ago.
=> http: remove deprecated Route.seal

akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/remove-getDefaultPort.excludes, akka-http-core/src/main/scala/akka/http/javadsl/ConnectionContext.scala, akka-http-core/src/main/scala/akka/http/scaladsl/ConnectionContext.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
But deprecated and keep scaladsl `defaultPort` because it had not been
deprecated before.
=> core: remove getDefaultPort and its usages

akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/remove-javadsl-entrypoints-with-materializer.excludes, akka-http-core/src/main/scala/akka/http/javadsl/Http.scala, akka-http-core/src/test/scala/akka/http/javadsl/HttpExtensionApiSpec.scala, akka-http-tests/src/test/java/akka/http/javadsl/HttpAPIsTest.java, docs/src/test/java/docs/http/javadsl/CustomMediaTypesExampleTest.java, docs/src/test/java/docs/http/javadsl/CustomStatusCodesExampleTest.java, docs/src/test/java/docs/http/javadsl/HttpClientDecodingExampleTest.java, docs/src/test/java/docs/http/javadsl/server/HttpServerExampleDocTest.java, docs/src/test/java/docs/http/javadsl/server/directives/CustomHttpMethodExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/MethodDirectivesExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/SchemeDirectivesExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/TimeoutDirectivesExamplesTest.java
These have been deprecated for a while. Unfortunately, it seems we never
enabled deprecation warnings for Java files in docs so we missed out on
removing those usages from the docs earlier.
=> core: remove deprecated javadsl entrypoints taking Materializer

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
Backport of #3021 which was a fix for #1439 which was now re-observed with 10.1.12 in #3200.
Fixes #3200.
=> [10.1 backport] core: don't fail slot after previous connection failed in special condition

akka-http-tests/src/test/java/docs/http/javadsl/server/HandlerExampleDocTest.java, docs/src/test/java/docs/http/javadsl/server/DirectiveExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/PathDirectiveExampleTest.java, docs/src/test/java/docs/http/javadsl/server/RejectionHandlerExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/CustomHttpMethodExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/MethodDirectivesExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/PathDirectivesExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/RouteDirectivesExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/SchemeDirectivesExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/directives/WebSocketDirectivesExamplesTest.java
Less intrusive alternative to #3193.
=> docs: don't show `route` import in docs

akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
Tests that a chunked HTTP response stream fails when the server terminates. 
The Akka HTTP client reacts as it should with "EntityStreamException: Entity stream truncation. The HTTP parser was receiving an entity when the underlying connection was closed unexpectedly."
https://github.com/akka/akka-http/issues/1210#issuecomment-488136833 made me curious how a client will see server termination on a chunked HTTP response stream.
I expect this test to be flaky, so I'm not sure if it is worth merging.
References #1210
=> Test: Inspect chunked responses during termination

akka-http-core/src/main/mima-filters/10.1.x.backwards.excludes/host-overrides.backwards.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/settings/ConnectionPoolSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ConnectionPoolSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ConnectionPoolSettings.scala, akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/settings/ConnectionPoolSettingsSpec.scala, docs/src/main/paradox/compatibility-guidelines.md
Rebased version of #1926
Refs #996
The default connection pool object can lookup host overrides for a
particular host, but client supplied connection pools will not be
overridden
=> core: allow client setting overrides for target hosts in config

.jvmopts, .jvmopts-travis
=> build: Set build-time jvm locale to en_US.UTF-8

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala
As commented those tests touch the filesystem (which is known to have some
issues on the `johannes` jenkins node).
Refs #2733
In the [last instance](https://github.com/akka/akka-http/issues/2733#issuecomment-636641196) when it failed the log looks like it would have made progress right after shutting down after the timeout so this might help.
=> tests: increase timeout in FileUploadDirectivesSpec once again

akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
Keep one test explicitly testing disabling hostname verification
=> tests: proxy transport instead of disabling hostname verification

build.sbt, docs/src/main/paradox/common/caching.md, docs/src/main/paradox/common/json-support.md, docs/src/main/paradox/common/xml-support.md, docs/src/main/paradox/compatibility-guidelines.md, docs/src/main/paradox/introduction.md, docs/src/main/paradox/routing-dsl/directives/caching-directives/index.md, docs/src/main/paradox/routing-dsl/testkit.md, docs/src/main/paradox/server-side/http2.md, project/AkkaDependency.scala
...and pull the minimum Akka versions from the build.
=> Docs: show Akka HTTP as symbolic version

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala
Backport of #3206
As commented those tests touch the filesystem (which is known to have some
issues on the `johannes` jenkins node).
Refs #3244 (same as #2733)
=> [backport #3206] tests: increase timeout in FileUploadDirectivesSpec once again

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala, akka-http2-support/src/main/scala/akka/http/scaladsl/Http2.scala
That's necessary because JDK11 with `-release 8` does not yet know about
the backported JDK 8 APIs.
refs #3251
=> http2: use reflection for `setApplicationProtocols`

akka-http/src/main/mima-filters/10.1.x.backwards.excludes/route-to-function.backwards.excludes, akka-http/src/main/scala/akka/http/javadsl/server/Route.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteAdapter.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RouteResult.scala, akka-http2-support/src/test/scala/akka/http/h2spec/H2SpecIntegrationSpec.scala
Related to #2463
This makes H2Spec '6.4. RST_STREAM' emit a 'Trying to materialize stream after
materializer has been shutdown. Completing with 500 Internal Server Error
response.', but that might be a separate issue?
=> http: allow 'bindAndHandleAsync' to take a 'Route'

akka-http-core/src/main/scala/akka/http/scaladsl/model/ErrorInfo.scala, akka-http-marshallers-java/akka-http-jackson/src/main/java/akka/http/javadsl/marshallers/jackson/Jackson.java, akka-http-marshallers-java/akka-http-jackson/src/test/java/akka/http/javadsl/marshallers/jackson/JacksonTest.java, akka-http/src/main/scala/akka/http/scaladsl/server/directives/MarshallingDirectives.scala, build.sbt, project/Dependencies.scala
Only include the unmarshalling error details (like 'unrecognized field xyz')
when 'verbose-error-messages' is enabled.
When 'verbose-error-messages' is disabled the error messages are still shown
in the logs, but no longer in the response body.
=> Only show unmarshalling error details when 'verbose-error-messages' is on

akka-http-core/src/test/scala/akka/http/impl/util/WithLogCapturing.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/FrameLogger.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
The client-side PR introduced a new serious looking warning on the server-side because I introduced another signal which came in at an unexpected time. This PR adds another state for the regular server case, so that the warning is not shown any more.
Also, it adds a bit more tooling to allow wholesale checking for extra warnings/error log messages in tests.
Fixes #3264
=> Fix warning in Http2 server side

akka-http-core/src/main/mima-filters/10.1.12.backwards.excludes/3022-fix-server-side-cancellation-races.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerWithExplicitSchedulerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
Backport of #3022
The client-side part was backported as part of the big bunch of backports but this one came afterwards and was missed.
I looked at #3022 to find out whether a backport was intended or not but I couldn't find one. It's a rather intrusive change so there's certainly an argument to be made to not go there for 10.1.x (on the other hand, we did already change client-side behavior for 10.1.12)
Refs #3247
=> [10.1 backport] server-side streamCancellationDelay

build.sbt
akka-http-docs [just failed](https://jenkins.akka.io:8498/job/akka-http-docs/448/consoleFull) because it tried to include the compatibility tests into unidoc.
Fixes #3284.
=> docs: exclude testing projects from unidoc

akka-http-core/src/main/scala/akka/http/javadsl/model/ws/UpgradeToWebSocket.scala, docs/src/main/paradox/server-side/websocket-support.md
Refs #3278
Recommend using the higher-level handleWebSocketMessages, or the
(yet to be implemented) attributes-based approach.
=> Deprecate UpgradeToWebSocket

akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketIntegrationSpec.scala
Backport of #3276 (because that problem was first reported on 10.1.x).
Refs #3247
(cherry picked from commit 795fc85eec63b662813472c1e27635c6e38ac4cc)
=> [backport] Add test for failure propagation into websocket flows

akka-http-tests/src/test/scala/akka/http/scaladsl/coding/CoderSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/coding/DecoderSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/coding/DeflateSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/coding/EncoderSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/coding/GzipSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/coding/NoCodingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/SizeLimitSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CodingDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ExecutionDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/coding/Coders.scala, akka-http/src/main/scala/akka/http/scaladsl/coding/Deflate.scala, akka-http/src/main/scala/akka/http/scaladsl/coding/Encoder.scala, akka-http/src/main/scala/akka/http/scaladsl/coding/Gzip.scala, akka-http/src/main/scala/akka/http/scaladsl/coding/NoCoding.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/CodingDirectives.scala, docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md, docs/src/test/scala/docs/http/scaladsl/HttpClientDecodingExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/CodingDirectivesExamplesSpec.scala
Refs #2916
Previously, we exposed Scala objects as API directly which exposes implementation
details and makes it hard to evolve the implementation. Instances in coders
are upcasted to `Coder` so that implementation details are not leaked any more.
=> http: deprecate more of coding infrastructure

.travis.yml, project/release.sh, scripts/release-train-issue-template.md
Automates deploying docs when releasing and removing the need for
https://jenkins.akka.io:8498/job/akka-http-docs/
=> Publish docs from travis

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ConnectionPoolBenchmark.scala
Showcases #3324, #3325, and #3326.
```
[info] Benchmark                              (maxConnections)   Mode  Cnt      Score       Error  Units
[info] ConnectionPoolBenchmark.singleRequest                 1  thrpt    3  52257.195 ± 49604.377  ops/s
[info] ConnectionPoolBenchmark.singleRequest                10  thrpt    3  51110.097 ± 32053.322  ops/s
[info] ConnectionPoolBenchmark.singleRequest               100  thrpt    3  37155.430 ±  6851.042  ops/s
[info] ConnectionPoolBenchmark.singleRequest              1000  thrpt    3  12741.234 ±  6250.936  ops/s
[info] ConnectionPoolBenchmark.singleRequest             10000  thrpt    3   5236.162 ±  9153.993  ops/s
```
So, the pool scales badly with higher numbers of concurrent connections. Most of the slowdown is due to various linear …
=> bench: add connection pool benchmark

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/HttpEntityBenchmark.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
This will be a win for lots of situations where discardBytes is called
to ensure that no streams are leaked but where it's common that the entity
is empty or small.
Fix #3323
=> core: make HttpEntity.Strict.discardBytes a no-op

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
The 10.millis might otherwise just be too short. In this case, sending out `WINDOW_UPDATE`s should be deterministic.
Refs #2882
=> tests: more reliable waiting for WINDOW_UPDATES

akka-http-tests/src/test/scala/akka/http/scaladsl/server/RoutingSpec.scala
Otherwise, it will use the scalatest default of 150 millis.
Refs #2405.
=> tests: set a more reasonable PatienceConfig for RoutingSpecs

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerTestSetupBase.scala, docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md
It's somewhat of an obscure feature which doesn't seem to be tested well.
=> core: disable server-side HTTP pipelining by default

docs/src/test/scala/docs/http/scaladsl/server/directives/FutureDirectivesExamplesSpec.scala
See https://github.com/akka/akka-http/pull/3335#issuecomment-654077375
=> docs: use Route directly in exception handler

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
Otherwise, it would be source incompatible in a central piece of the model.
We usually prefer the `withXYZ` methods but since the case class style has
been around for such a long time maybe we should also keep the copy method
around until it becomes more of a problem.
The other alternative would be to deprecate the methods and point to the
`withXYZ` methods more prominently.
(And yes, I probably argued for the existing state at some point...)
See also https://github.com/akka/alpakka/issues/2355
=> core: keep request/response copy method public

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ConnectionPoolBenchmark.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala
Before linear scanning for idle slots was the number one hot spot for pools.
In experiments that showed for pools of size > 500.
Refs #3325
```
Before:
Benchmark                              (maxConnections)   Mode  Cnt      Score      Error  Units
ConnectionPoolBenchmark.singleRequest              1000  thrpt    3  10459.168 ±  948.674  ops/s
ConnectionPoolBenchmark.singleRequest             10000  thrpt    3   4302.828 ± 1031.308  ops/s
After:
Benchmark                              (maxConnections)   Mode  Cnt      Score       Error  Units
ConnectionPoolBenchmark.singleRequest              1000  thrpt    3  28747.105 ± 44447.131  ops/s
ConnectionPoolBenchmark.singleRequest             10000  thrpt    3  29018.001 ±  2771.695  ops/s
```
I.e.
~ 3x speedup for a size of 1000 connections
~ …
=> Track idle slots explicitly to avoid O(n^2) work for big pools

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
Solution:
* remove newly introduced and then deprecated variant that allows to set attributes
* keep deprecated original copy method
* create an internal copyImpl that allows to copy all fields
* use copyImpl internally
=> core: cleanup HttpMessage.copy chaos introduced in #3347

akka-http-core/src/main/java/akka/http/javadsl/model/AttributeKeys.java, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/ParserOutput.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/ws/Handshake.scala, akka-http-core/src/main/scala/akka/http/impl/engine/ws/UpgradeToWebSocketLowLevel.scala, akka-http-core/src/main/scala/akka/http/javadsl/model/ws/UpgradeToWebSocket.scala, akka-http-core/src/main/scala/akka/http/javadsl/model/ws/WebSocket.scala, akka-http-core/src/main/scala/akka/http/javadsl/model/ws/WebSocketUpgrade.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/AttributeKeys.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/ws/UpgradeToWebSocket.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/ws/WebSocketUpgrade.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/PrepareRequestsSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/WSServerAutobahnTest.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketIntegrationSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketServerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/TestServer.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/WSTestRequestBuilding.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/WebSocketDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/WebSocketDirectives.scala, docs/src/main/paradox/routing-dsl/directives/websocket-directives/extractUpgradeToWebSocket.md, docs/src/main/paradox/routing-dsl/directives/websocket-directives/extractWebSocketUpgrade.md, docs/src/main/paradox/routing-dsl/directives/websocket-directives/index.md, docs/src/test/java/docs/http/javadsl/server/directives/WebSocketDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/WebSocketExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/WebSocketDirectivesExamplesSpec.scala
=> Document and dogfood using the attribute for websockets

akka-http-core/src/test/scala/akka/http/impl/engine/client/HighLevelOutgoingConnectionSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/CustomStatusCodesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/TimeoutDirectivesExamplesSpec.scala
As observed here: https://jenkins.akka.io:8498/job/akka-http-nightly/196/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.2,jdk=AdoptOpenJDK%2011/testReport/junit/akka.http.scaladsl/CustomStatusCodesSpec/Http_should_allow_registering_custom_status_code/
=> tests: avoid temporaryHostNameAndPort in several tests

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ConnectionPoolBenchmark.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/pool/SlotStateSpec.scala, akka-parsing/src/main/scala/akka/macros/LogHelper.scala
By using the existing log macro that avoids logging code if not enabled.
Refs #3324
=> Avoid expensive logging in NewHostConnectionPool

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpMessageSpec.scala
Not super important since hashCode by definition doesn't give a guarantee that different objects in terms of equals will have a different hashCode. Might still be better to take everything into account so that you don't have any surprises when putting things into a HashMap.
=> core: make HttpRequest/HttpResponse.hashCode depend on attributes

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/javadsl/Http.scala, akka-http-core/src/main/scala/akka/http/javadsl/ServerBuilder.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/ServerBuilder.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala, akka-http-tests/src/multi-jvm/scala/akka/http/AkkaHttpServerLatencyMultiNodeSpec.scala, akka-http-tests/src/test/java/akka/http/javadsl/HttpAPIsTest.java, akka-http/src/main/scala/akka/http/scaladsl/server/HttpApp.scala, docs/src/main/paradox/migration-guide/migration-from-spray.md, docs/src/main/paradox/migration-guide/migration-guide-10.2.x.md, docs/src/main/paradox/release-notes/10.2.x.md, docs/src/main/paradox/server-side/http2.md, docs/src/test/java/docs/http/javadsl/server/AkkaHttp1020MigrationExample.java, docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/HttpServerHighLevel.scala, docs/src/test/scala/docs/http/scaladsl/server/AkkaHttp1020MigrationSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/HttpsServerExampleSpec.scala
* One significant change over #3362: I renamed `bind()` to `connectionSource` to make it clear that calling the method will not immediately create a binding and also to avoid overloading `bind()` (which became awkward in docs)
* Converted remaining internal and docs usages of `Http().bindXYZ` usages
* Brief release notes and migration notes entry
=> core: polishing and docs for ServerBuilder API

akka-http-core/src/main/scala/akka/http/javadsl/ServerBuilder.scala, akka-http-core/src/test/scala/akka/http/javadsl/HttpExtensionApiSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala, akka-http-tests/src/main/java/akka/http/javadsl/server/examples/petstore/PetStoreExample.java, akka-http-tests/src/main/java/akka/http/javadsl/server/examples/simple/SimpleServerApp.java, akka-http-tests/src/main/java/akka/http/javadsl/server/examples/simple/SimpleServerHttpHttpsApp.java, akka-http/src/main/java/akka/http/javadsl/server/HttpApp.java, akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/test/scala/akka/http/scaladsl/Http2BindingViaConfigSpec.scala, docs/src/main/paradox/routing-dsl/testkit.md, docs/src/test/java/docs/http/javadsl/ComposeDirectivesExampleTest.java, docs/src/test/java/docs/http/javadsl/CustomStatusCodesExampleTest.java, docs/src/test/java/docs/http/javadsl/ExceptionHandlerExample.java, docs/src/test/java/docs/http/javadsl/RespondWithHeaderHandlerExampleTest.java, docs/src/test/java/docs/http/javadsl/RouteSealExample.java, docs/src/test/java/docs/http/javadsl/server/HighLevelServerBindFailureExample.java, docs/src/test/java/docs/http/javadsl/server/HighLevelServerExample.java, docs/src/test/java/docs/http/javadsl/server/ServerShutdownExampleTest.java, docs/src/test/java/docs/http/javadsl/server/directives/TimeoutDirectivesExamplesTest.java, docs/src/test/java/docs/http/javadsl/server/testkit/MyAppService.java
Last time I missed Java examples that still used old `bindAndHandle` APIs and also a `scaladsl.Source` slipped into `javadsl.ServerBuilder`.
=> Convert more javadsl doc examples from bindAndHandle to ServerBuilder

docs/src/main/paradox/routing-dsl/directives/marshalling-directives/completeWith.md
I just removed the entire old Spray reference since I expect replacing it with a reference to one (or both) of the akka-http DSL packages would not help make thing more clear.
=> docs: removed outdated reference to the spray.httpx.marshalling package

build.sbt
Snapshot docs publishing failed because of that.
=> build: don't include scalafix submodules in unidoc

build.sbt
=> build: use older scalafix-testkit for now until we can upgrade Scala version after 10.2.0 release

project/AkkaDependency.scala
akka-actor_2.12 is one of the first artifacts published by akka-publish-nightly,
so it often happened that Akka snapshots has been published only partly and
akka http nightlies failing for that reason. By using the last artifact published
for detecting the snapshot version we try to avoid that issue.
Tried it locally and it selected 2.6.8+15 instead of 2.6.8-20. 2.6.8+15 corresponds to the last non-failing nightly snapshot build: https://jenkins.akka.io:8498/view/Nightly%20Jobs/job/akka-publish-nightly/1428/consoleFull, so that seems like a more reasonable choice.
=> build: more reliable detection of last snapshot

project/AkkaDependency.scala
release-10.1 backport of #3421
akka-actor_2.12 is one of the first artifacts published by akka-publish-nightly,
so it often happened that Akka snapshots has been published only partly and
akka http nightlies failing for that reason. By using the last artifact published
for detecting the snapshot version we try to avoid that issue.
=> [backport] build: more reliable detection of last snapshot 

akka-http-core/src/main/scala/akka/http/scaladsl/model/FormData.scala
```
overloaded method value toEntity with alternatives:
[error]   (charset: akka.http.scaladsl.model.HttpCharset)akka.http.scaladsl.model.RequestEntity <and>
[error]   => akka.http.scaladsl.model.RequestEntity
[error]  cannot be applied to ()
[error]           ).toEntity()
[error]             ^
[error] one error found
```
=> docs: fix typo in deprecation message

build.sbt, project/Dependencies.scala
To be merged only after #3419 and the release (too risky to do it so late before the release).
=> build: update to Scala 2.12.12

build.sbt, project/AkkaDependency.scala
Here, we also don't build against akka master any more but use the
latest snapshot.
Also `onlyIf` is not necessary any more.
=> build: simplify http-core test against akka master scenario

akka-http-core/src/main/scala/akka/http/impl/engine/client/HttpsProxyGraphStage.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HttpsProxyGraphStageSpec.scala
Commit 866fbf83 have broken HTTPS proxy CONNECT request structure (Proxy-Authorization header value wasn't rendered).
It affects all users using 10.2.0 release (including me)
=> core: fix HTTPS proxy CONNECT request

docs/src/test/scala/docs/http/scaladsl/server/directives/StyleGuideExamplesSpec.scala
The Java example for `path-compose` already does the right thing but the Scala example duplicates the `customer` path.
I also fixed the name of the extracted `customerId` value.
=> Updated Scala style guide example to match the Java one (removed duplication)

akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientTransportWithCustomResolverSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/EntityDiscardingSpec.scala, akka-http-core/src/test/scala/akka/testkit/SocketUtil2.scala, akka-http-tests/src/multi-jvm/scala/akka/http/AkkaHttpServerLatencyMultiNodeSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/CustomMediaTypesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/CustomHttpMethodSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/TimeoutDirectivesExamplesSpec.scala
It recently failed various times with this stack trace:
```
java.net.BindException: Cannot assign requested address
at java.base/sun.nio.ch.Net.bind0(Native Method)
at java.base/sun.nio.ch.Net.bind(Net.java:455)
at java.base/sun.nio.ch.Net.bind(Net.java:447)
at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:73)
at akka.testkit.SocketUtil$.$anonfun$temporaryServerAddresses$1(SocketUtil.scala:97)
at scala.collection.StrictOptimizedSeqFactory.fill(Factory.scala:330)
at scala.collection.StrictOptimizedSeqFactory.fill$(Factory.scala:325)
at scala.collection.immutable.Vector$.fill(Vector.scala:34)
at …
```
=> tests: use copy of SocketUtil that does not use 127.x.y.255 addresses

akka-http/src/main/scala/akka/http/scaladsl/server/Route.scala
`Route.handlerFlow` deprecation message was pointing to a non-existing `handlerFlow` method.
=> Fix Route.handlerFlow deprecation message.

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Fixes #3461
Those frames are somewhat expected at least in the case where we just sent a
RST_STREAM frame and the peer might not have yet processed it.
Of course, it might also be an indication of a misbehaving peer but as long
as there's no indication that this can lead to a non-negligible overhead on
our side, we might be fine with this simple solution.
=> http2: ignore unexpected DATA frames in state closed

build.sbt, project/MiMa.scala
* create new "fork" for 10.1 and set current to 10.2
* remove mima testing for old 10.0 versions (but keep 10.0.15 around for a while)
I guess it makes sense to wait with merging after 10.2.0 is released.
=> build: setup mima for 10.2

akka-http-core/src/test/scala/akka/http/impl/engine/client/ClientCancellationSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HighLevelOutgoingConnectionSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/EntityDiscardingSpec.scala, akka-http-core/src/test/scala/akka/testkit/SocketUtil2.scala, akka-http-tests/src/multi-jvm/scala/akka/http/AkkaHttpServerLatencyMultiNodeSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/CustomMediaTypesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/CustomStatusCodesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/IntegrationRoutingSpec.scala, akka-http2-support/src/test/scala/akka/http/scaladsl/Http2BindingViaConfigSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/CustomHttpMethodSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/TimeoutDirectivesExamplesSpec.scala
Backport of #3460 for the release-10.1 branch.
=> [10.1 backport] tests: use copy of SocketUtil that does not use 127.x.y.255 addresses

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/HttpEntityBenchmark.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala
10.1 backport of #3329
This will be a win for lots of situations where discardBytes is called
to ensure that no streams are leaked but where it's common that the entity
is empty or small.
Fix #3323
(cherry picked from commit 868d92a)
=> [10.1 backport] core: make HttpEntity.Strict.discardBytes a no-op

akka-http-tests/src/test/scala/akka/http/scaladsl/server/RouteResultSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RouteResult.scala
For better backwards compatibility with 10.1.x #3427
I think putting it in a superclass like this should avoid any
ambiguous import problems, but a second pair of eyes would not
hurt here.
=> http: provide implicit conversion from route and materializer to flow

akka-http-core/src/main/mima-filters/10.2.0.backwards.excludes/ssl-config.excludes, akka-http-core/src/main/scala/akka/http/javadsl/ConnectionContext.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/TlsEndpointVerificationSpec.scala, docs/src/main/paradox/client-side/client-https-support.md, docs/src/test/java/docs/http/javadsl/HttpsExamplesDocTest.java, docs/src/test/scala/docs/http/scaladsl/HttpsExamplesSpec.scala
Somewhat related to #3477 but not resolving it yet: no documentation on how to
do futher configuration without using the deprecated methods.
=> docs: Document how to disable hostname verification without ssl-config

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/ServerTerminator.scala, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
Fixes #3452, #2532
In 294df230af0e1e1b3a7aba575975a634bd017050, the stream-cancellation-delay was
introduced. However, at the same time I removed the lingerTimeout functionality.
While both features are related, they serve different purposes:
* `streamCancellationDelay` tries to avoid cancellation races by giving a
stream graph more time to propagate errors/completion on the forward path.
The default is 100 millis because that suffices in most conditions.
* `lingerTimeout` gives clients more time to read a response slowly when the
server is finished with a connection. lingerTimeout is set to a more generous
1 minute, because it is only a safe-guard that a connection, that isn't "managed"
any more by the server (because the server stack was already done), is
still ultimately closed if the …
=> core: reenable lingerTimeout

build.sbt, project/ParadoxSupport.scala
Fixes #3429
Previously in #3430 the wrong key was updated so that the change had no effect and the timeout was still 2 seconds which is arguably slow enough to trip over now and then.
=> build: really increase paradox parsing timeout

akka-http2-support/src/main/scala/akka/http/impl/engine/http2/client/RequestRendering.scala
https://tools.ietf.org/html/rfc7540#section-8.1.2.3
Tests for this are already in #3532
=> http2: use scheme portion of target URI in :scheme pseudo-header

akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Applying this PR will add parens to the deprecation messages for the bind-methods. Hopefully saving some confusion for people migrating.
=> Add parens to deprecation messages for bind-methods

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
Though this value is somewhat best-effort, if I'm reading the [spec](https://tools.ietf.org/html/rfc7540#section-6.8)
right we should over-estimate, not under-estimate.
This probably conflicts with the ongoing refactor in this area, I'm happy to rebase when that is done :)
=> More accurately track the last-stream-id for GOAWAY

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerProcessingBenchmark.scala
Benchmark compilation silently failed since the move of http2 into akka-http-core.
Added email notifications for akka-http-bench-nightly failures.
=> bench: fix http2 compilation

build.sbt
Since no artifacts are published from this module.
=> build: exclude akka-http-bench-jmh from whitesource

.travis.yml
Instead, PR validation on Jenkins was changed to run mima for 2.12 as well
=> build: run mima on travis only for master builds or releases

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala
To avoid uncontrolled reentry into state machine. Will conflict with #3581.
=> http2: also go through state machine for `resetStream`

build.sbt, project/plugins.sbt
This was needed until JDK 8u252 to use the Jetty ALPN agent for HTTP2.
=> Remove sbt-javaagent

akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala, akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/ScalatestRouteTestSpec.scala
=> testkit: fail noisily if trying to use `~>` together with transparent-head-requests

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala
For example, for HEAD requests.
Fixes #3530
=> core: don't dispatch onResponseEntity... events for entities that don't have to be subscribed

akka-http/src/main/scala/akka/http/scaladsl/server/directives/HeaderDirectives.scala
The existing implementation of `optionalHeaderValueByName` is costly for the `Authorization` header due to the `unapply` on `value` which evaluates the header value for each such call.
For `Authorization` header, for example in case of `OAuth2BearerToken` evaluating the `value` causes the `render` to execute which causes a new string to be created and discarded for each such call.
In our case, the header is a jwt header which is 1kb in size, and such frequent eager evaluation this adds to ~ 9% of the time spent in our flow.
```
final case class OAuth2BearerToken(token: String) extends jm.headers.OAuth2BearerToken {
def render[R <: Rendering](r: R): r.type = r ~~ "Bearer " ~~ token
override def scheme: String = "Bearer"
override def params: Map[String, String] = Map.empty
}
```
**This PR …
=> http: optimize header directives by avoiding HttpHeader.unapply

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala
I tested the current server implementation on some real projects and noticed some unexpected slowness which was caused by routing DSL code being run directly in the handler and blocking progress of the HTTP/2 infrastructure and sibling requests.
=> http2: run handler code in its own task on the server

akka-http-core/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/ResponseParsing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala
References #812 
Tried to read RFC7540 for MUST rules around headers and crosscheck with the HTTP/1.1 message parsing, but not super confident I did not miss something or get something wrong.
=> Check HTTP2 headers for correctness

build.sbt
That makes failures triggered in helper methods easier to read
=> Include stack traces in scalatest failures

akka-http-tests/src/test/java/akka/http/javadsl/server/MinimalHttpApp.java
Not sure this is the issue making it fail, because I'd expect that failure showing up in logs anyway, but it could provide more info if an exception is what is going on making the promise never complete.
References #3588
=> Make sure to fail binding promise if binding fails in MinimalHttpApp

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
Make sure the stream window resize always happens.
Previously it would only be triggered in Akka 2.6 by a earlier pull causing the test to fail
while with Akka 2.5 would pass. This adds an explicit pull to trigger the same behavior on both.
Credits for fix mostly goes to jrudolph who helped me a lot.
References #3606
=> Stream window test fail fix

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/ResponseRendering.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/RequestRendering.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/ResponseParsing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala
Now we are back to a single version of Http2SubStream that can either be supplied by `ByteString` or `ChunkStreamPart` as it fits.
I also put all of the substream <=> entity conversions into that class so that it will be more easily reused from parsing / rendering.
=> Http2SubStream cleanup

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
To reduce timing-sensitivity of tests on CI. Might (or might
not) help for #3625.
=> Increase patience in Http2ClientSpec

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> http2: more robust handling of IncomingStreamBuffer.onPull

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
References #3268
Actual fix was implemented in trailing headers work (I think)
=> Test coverage for GOAWAY on mid-stream headers 

docs/src/main/paradox/release-notes/10.1.x.md
After I reverted the big backport of fixing server-side cancellation races (88a6a75f3e59d11ef8bb03c73b0193b5ad4e78d6) because of it breaking the `lingerTimeout` there's actually not much left but a fix for the connection pool and an performance optimization for strict entities.
I'm seeing this as a good sign that maintenance on 10.1.x has naturally wound down.
=> docs: release notes for 10.1.13

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
In Http2ServerSpec information flows in 4 directions:
frames from the network to the server, requests from the server
to the user code, responses from the user code to the server, and
frames from the server to the network.
That can get fairly hard to follow at times. I wonder if it helps
when we explicitly put the test methods in 'user' and 'network'
objects?
(if we like this we should also apply it to Http2ClientSpec of
course)
=> http2 tests: Make 'network' and 'user' sides more explicit

CONTRIBUTING.md, docs/src/main/paradox/contributing.md
To have an easy page that you can refer people to when you want them to test snapshots.
Based on a page in the alpakka documentation at https://github.com/akka/alpakka/blob/master/docs/src/main/paradox/other-docs/snapshots.md.
=> docs: add section about how to configure snapshots

akka-http-core/src/test/java/akka/http/javadsl/model/UriTest.java, akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala, docs/src/main/paradox/client-side/request-and-response.md, docs/src/main/paradox/common/uri-model.md, docs/src/test/java/docs/http/javadsl/ClientSingleRequestExample.java, docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala
This is quite a common requirement and nowhere mentioned in the docs explicitely. A question on stackoverflow (with 11k views) has an [answer](https://stackoverflow.com/a/31939776/154325) to this. But I believe inclusion of a simple example in official documentation will help developers a great deal.
References #xxxx
=> docs: add example for Get request with query parameters

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
To fix nightly failure here: https://jenkins.akka.io:8498/view/Akka-http/job/akka-http-nightly-release-10.1/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.12.10,jdk=AdoptOpenJDK%208/1089/testReport/junit/akka.http.impl.engine.http2/Http2ServerSpec/The_Http_2_server_implementation_should_support_multiple_concurrent_substreams_should_close_substreams_when_connection_is_shutting_down/
(Behavior will be slightly different between latest Akka 2.6 and previous versions but we don't care to much there.)
=> tests: any exception is fine in "close substreams" test

docs/src/test/scala/docs/http/scaladsl/server/directives/FormFieldDirectivesExamplesSpec.scala
With the new `formFields` signature, parameters that extract nothing still need to be accounted for in the output. Code example is updated demonstrating that.
The discussion on magnets and signatures at the top of https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/form-field-directives/formFields.html also probably needs to be updated, but I'm not sure what to replace it with.
=> Update formFields example

docs/src/test/java/docs/http/javadsl/HttpServerActorInteractionExample.java
Serialization via Jackson will fail due to properties not being discoverable.
=> Fix the Bid class.

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/ResponseParsing.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ParserSettings.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
Started out as added HTTP/2 client test coverage but perhaps better with this as an isolated PR since it basically was about adding a feature in the end.
=> HTTP/2 client test coverage (and support for) tls session info

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
=> http2: 'pull' was lost when closing while waiting for window

project/project-info.conf
The link shows in the standardised project info section:
References #3642
=> docs: Link project info to snapshots

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala
=> Test coverage for request HTTP2 client entity stream failing

docs/src/test/scala/docs/http/scaladsl/server/directives/FutureDirectivesExamplesSpec.scala
References #3311
I think the cause is that the reset is timer based so needs to "happen" before the call, but if it is a bad JVM day those 200ms of leeway is not enough for it to complete before the sample http call expecting the breaker to have been reset/closed again.
=> FutureDirectivesExampleSpec fail fix

akka-http-core/src/test/scala/akka/http/impl/engine/client/ConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientTransportWithCustomResolverSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/EntityDiscardingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/CustomMediaTypesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/CustomHttpMethodSpec.scala
Since it has an inherent race condition.
Refs #3679. I thought we had an 'umbrella ticket' for this
but can't find it right now.
=> Avoid temporaryServerHostnameAndPort

akka-http-core/src/main/mima-filters/10.2.1.backwards.excludes/issue-3133-ignore-illegal-header-names.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpHeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/HeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ParserSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ParserSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ParserSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/HttpHeaderParserSpec.scala
* reuse ignore illegal header value configuration
* configuration now applies to both, header and key
* BREAKING: name of configuration key changed
https://github.com/akka/akka-http/issues/3133
References #3133
=> core: allow illegal header keys to be ignored #3133

docs/src/main/paradox/common/caching.md, docs/src/main/paradox/common/json-support.md, docs/src/main/paradox/common/xml-support.md, docs/src/main/paradox/compatibility-guidelines.md, docs/src/main/paradox/introduction.md, docs/src/main/paradox/routing-dsl/directives/caching-directives/index.md, docs/src/main/paradox/routing-dsl/testkit.md, docs/src/main/paradox/server-side/http2.md
WIP as it lacks a Paradox release.
This uses the new notation for BOM dependencies introduced in https://github.com/lightbend/paradox/pull/462
A bit sad that it can't yet show the use of the Akka BOM as that won't be available prior to Akka 2.6.11.
References #2665, https://github.com/akka/akka/pull/29839
=> docs: show akka-http-bom in dependencies

akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Instead of silently ignoring and binding HTTP/1.1 
Refs #3677
=> Fail if trying to bind flow/source with HTTP2 

akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTestResultComponent.scala, akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/ScalatestRouteTestSpec.scala
It is useful using `ScalatestRouteTest` but anything inside the body of `check` method ends up calling some sort of `awaitAllElements`, effectively blocking until the whole response has been retrieved.
There are cases where we might have an infinite stream (i.e. [SSE](https://doc.akka.io/docs/akka-http/10.0/sse-support.html)) and we want to verify that part of the stream is returned as expected.
I've added `chunksStream` method for this.
=> Added support to fetch chunks in the testkit without waiting for the whole response to finish

akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/ScalatestRouteTestSpec.scala
=> Fix for ScalatestRouteSpec on Scala 2.12 

akka-http-core/src/test/scala/akka/http/impl/util/WithLogCapturing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala
=> tests: ignore ChannelReadable events in Http2PersistentClientSpec

docs/src/main/paradox/client-side/connection-level.md, docs/src/main/paradox/client-side/http2.md, docs/src/main/paradox/client-side/index.md, docs/src/main/paradox/server-side/http2.md, docs/src/main/paradox/troubleshooting/unsupported-http-method-pri.md, docs/src/test/java/docs/http/javadsl/Http2Test.java, docs/src/test/scala/docs/http/scaladsl/Http2Spec.scala
Introduces the `client-side/http2.md` extracting any HTTP/2-specific there. The new page references the connection-level client-side API as extra content.
Also did a bit of cleanup on the imports of the snips.
=> Document HTTP/2 client API

akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/PersistentConnection.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala
Avoids responding with 502 responses when we fail to connect to a host at all, so we can retry (possibly to a different endpoint).
Test still fails: the reconnection seems to happen, but no request is/becomes available on `requestIn` - I can't explain that yet...
=> [h2 client] 'connecting' phase for persistent connections

akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala, akka-http-tests/src/multi-jvm/scala/akka/http/AkkaHttpServerLatencyMultiNodeSpec.scala
References #2947
Relates to https://github.com/akka/akka-http/pull/3691
=> tests: get rid of SocketUtils.temporaryHostnameAndPort in some tests

akka-http-core/src/main/java/akka/http/javadsl/model/HttpEntity.java
If I am not mistaken, since akka-http 10.1.5, we don't need to apply `HttpEntity.limitable` ourself for the entities that are not created via HTTP layer in order for them to respect the size limit. Thanks to #2185
=> Updates HttpEntity.withSizeLimit, HttpEntity.withoutSizeLimit JavaDoc

docs/src/main/paradox/security/2021-02-24-incorrect-handling-of-Transfer-Encoding-header.md
This is a simple documentation fix for a change from "does currently not" to "currently does not"
=> Grammatical typo fix

akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala
Just have a look at the tests I addded, also the title says it all:
[If a request (which is _not_ a chunked one)](https://github.com/akka/akka-http/blob/b071bd67547714bd8bed2ccd8170fbbc6c2dbd77/akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala#L202-L208) does [not have a `Content-Length` header or it is 0](https://github.com/akka/akka-http/blob/b071bd67547714bd8bed2ccd8170fbbc6c2dbd77/akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala#L362-L363), it means it will not send a body/entitiy.
Therefore we do not have to send `100 Continue`, because obviously there will be nothing to continue with from the client.
Right now akka-http _does_ send `100 Continue` and then **waits/hangs indefinitely** (=until the request timeout) …
=> core: don't send '100 Continue' if 'Content-Length' header is 0, doesn't exist or data got sent early

akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
This makes it easier to diagnose what's going on when you find this
message in your logs - for example, akka-management currently binds
using a flow (https://github.com/akka/akka-management/issues/866)
causing this message to be logged. This change would make it more
obvious that this warning is about the Akka Management port and not
the 'main' application port.
=> Include port in HTTP/2 binding warning

akka-http-core/src/main/scala/akka/http/impl/model/parser/UriParser.scala
maxValueStackSize was being passed as initialValueStackSize
before this change
```
[info] UriParserBenchmark.bench_parse_uri                                                                               http://any.hostname?param1=111&amp;param2=222  thrpt    3  572.416 ± 43.707  ops/ms
[info] UriParserBenchmark.bench_parse_uri  http://any.hostname?param1=111&amp;param2=222&param3=333&param4=444&param5=555&param6=666&param7=777&param8=888&param9=999  thrpt    3  250.080 ± 61.767  ops/ms
```
after this change
```
[info] UriParserBenchmark.bench_parse_uri                                                                               http://any.hostname?param1=111&amp;param2=222  thrpt    3  788.617 ± 579.079  ops/ms
[info] UriParserBenchmark.bench_parse_uri …
```
=> Fix UriParser constructor performance

akka-http-core/src/main/mima-filters/10.2.4.backwards.excludes/3811-http2-internals.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2AlpnSupport.scala
Fixes #3808
The former use of structural types tried to use reflection on the concrete
type of the receiver. In this case this was an internal JDK type which cannot
be accessed reflectively in JDK16 any more.
The new pattern relies on lazy class loading for accessing a compatible JDK
only after checking for the method explicitly.
=> http2: remove reflective access to alpn classes

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ClientServerBenchmark.scala, akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerProcessingBenchmark.scala, akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerSwitchBenchmark.scala, akka-http-core/src/main/java/akka/http/javadsl/model/AttributeKeys.java, akka-http-core/src/main/mima-filters/10.2.4.backwards.excludes/http2-strict-trailing-headers.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/HttpMessageRendering.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, akka-http-core/src/main/scala/akka/http/javadsl/model/Trailer.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/AttributeKeys.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/Trailer.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameHpackSupport.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala, docs/src/main/paradox/server-side/http2.md, docs/src/test/java/docs/http/javadsl/Http2Test.java, docs/src/test/scala/docs/http/scaladsl/Http2Spec.scala
Through an attribute.
First step of the first bullet in #3815.
Still to do:
It looks like there's more opportunity for optimization of strict HTTP/2 responses, but perhaps that should be a separate PR.
=> Allow trailing HTTP/2 headers on strict responses

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerProcessingBenchmark.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2ServerDemux.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala
This avoids materializing a stream for outgoing Strict entities.
Another ready result from #3822.
=> http2: support Strict entities in Http2SubStream

docs/src/test/scala/docs/http/scaladsl/HttpServerRoutingMinimal.scala
Clicking on the link in the output currently directs you to the root path of the server, displaying the message:
```
The requested resource could not be found.
```
This happens because the only path defined in the script is path("hello"), while we are directing the reader to path("").
As this is the first piece of code presented on the Akka-Http introduction page [1], it makes sense to make running the example as straightforward as possible. Showing the direct link in the terminal is the simplest way of doing that.
Alternatively, we could add a redirect in the routing, but I think that would end up too verbose:
```
val route =
concat(
path("") {
get {
redirect("/hello", StatusCodes.TemporaryRedirect)
}
},
path("hello") {
get {
complete(HttpEntity(ContentTypes.`text/html(UTF-8)`, "<h1>Say …
```
=> docs: display correct link to demo resource

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ServerProcessingBenchmark.scala, akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/StreamServerProcessingBenchmark.scala, akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ClientServerBenchmark.scala, akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerProcessingBenchmark.scala, akka-http-core/src/main/mima-filters/10.2.4.backwards.excludes/changes-in-implementation.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/HttpMessageRendering.scala, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/DateHeaderRendering.scala, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/HttpMessageRenderingSpec.scala
Previously we cached the rendering but rendering actually was not the most expensive part but calling `System.currentTimeMillis` for every response. In this scheme, we only update once a second with the trade-off that reported times may be up to 1 second in the past.
It applies both to HTTP/2 and HTTP/1.1.
Before:
```
[info] Benchmark                                          Mode  Cnt       Score       Error  Units
[info] ServerProcessingBenchmark.benchRequestProcessing  thrpt    3  209478.673 ± 48778.234  ops/s
```
After:
```
[info] Benchmark                                          Mode  Cnt       Score       Error  Units
[info] ServerProcessingBenchmark.benchRequestProcessing  thrpt    3  270904.245 ± 29405.551  ops/s
```
which shows that this was a big issue for the HTTP/1.1 pipeline. …
=> http: only render date-header once per second

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ClientServerBenchmark.scala, akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2RequestResponseBenchmark.scala, akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerProcessingBenchmark.scala, akka-http-core/src/main/mima-filters/10.2.4.backwards.excludes/http2-add-new-setting.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/Http2ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
As prototyped in #3822.
It is currently only support for request entities. I'll create an issue to also support that functionality for the client side (which should be somewhat easy to add but needs tests).
=> http2: add setting to automatically collect (request) entity data into strict entities

akka-http-core/src/main/scala/akka/http/impl/settings/ConnectionPoolSettingsImpl.scala, akka-http-core/src/test/scala/akka/http/scaladsl/settings/ConnectionPoolSettingsSpec.scala
There seems to be no practical reason for this limitation.
=> Remove the requirement of max-open-requests being a power of two

akka-http-core/src/main/mima-filters/10.2.4.backwards.excludes/keep-alive-timeout.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ConnectionPoolSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ConnectionPoolSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ConnectionPoolSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/pool/SlotStateSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/settings/PreviewServerSettingsSpec.scala, docs/src/main/paradox/common/timeouts.md
References #3806, #3759 and #3481
Adds an extra timeout following the ideas discussed in https://github.com/akka/akka-http/issues/3806#issuecomment-829137002
=> core: add pool keep-alive-timeout

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala
This was supposed to be a small optimization to avoid having to wrap data elements into `Chunks` when it was unlikely that we expected a trailing header. The heuristic was whether we have seen a `content-length` header or not. However, with more of our optimizations applied, gRPC may actually send a
content-length header on the server side which means we miss out on trailers on the client side.
Let's revert this optimization for now, so that we can receive trailing headers in all cases again.
This should help unbreak tests at https://github.com/akka/akka-grpc/pull/1365
=> http2: never create Default entity

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Compliance.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/ProtocolSwitch.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/framing/Http2FrameParsing.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderDecompression.scala, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2SpecIntegrationSpec.scala
Should also fix #3693. Before, when a failure happened, cancellation might overtake the actual error and (due to TLSStage) lead to regular closure of the connection. Now cancellation is delayed and errors need to be dealt with. There's now a very late `errorHandling` stage that outputs proper `GOAWAY` frames for error conditions and closes the connection cleanly afterwards.
=> http2: ensure unhandled error ultimately get translated into GOAWAY frames

akka-http-core/src/main/mima-filters/10.2.4.backwards.excludes/websocket-isstrict.excludes, akka-http-core/src/main/scala/akka/http/javadsl/model/ws/Message.scala
All websocket message types already define a `def isStrict: Boolean`.
The change here is just to declare `def isStrict: Boolean` on the base
class.
References #3844
=> core: move `isStrict` up a level to ws.Message

akka-http-core/src/main/scala/akka/http/impl/engine/http2/BufferedOutletSupport.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Demux.scala
A nicer solution would be to be able to use an implicit value class
which isn't possible as an inner class.
=> http2: avoid creating GenericOutlet for every out element

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Demux.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-parsing/src/main/scala/akka/macros/LogHelper.scala
For Slf4j `isDebugEnabled` calls the Slf4jLoggingFilter which needs to look up
the concrete logger with `SLFLoggerFactory.getLogger` for each invocation.
In HTTP/2 we log a lot with debug so caching the value here can make a difference.
The disadvantage is that a dynamic logger level change will not directly apply
to already existing connections but only to new ones which seems like a
useful trade-off.
=> http2: cache expensive `isDebugEnabled` call

akka-http-core/src/main/mima-filters/10.2.4.backwards.excludes/modeled-header-value-cache.excludes, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala
This prevents that cached header instances have to re-render their value every time.
The assumption is that the lazy value access / initialization cost is negligible in comparison with rendering.
=> core: cache ModeledHeader.value

akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/PersistentConnection.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala
Detected by akka-grpc tests which will hang and eventually fail otherwise.
=> http2: properly propagate completion through PersistentConnection 

README.md
This badge summarises which versions of Scala are supported by Akka HTTP (and what the latest Akka HTTP version is for each of those Scala versions):
[![akka-http-core Scala version support](https://index.scala-lang.org/akka/akka-http/akka-http-core/latest-by-scala-version.svg)](https://index.scala-lang.org/akka/akka-http/akka-http-core)
More details on the badge format: https://github.com/scalacenter/scaladex/pull/660
=> docs: add Scaladex badge to ReadMe to show Scala version support

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/framing/FrameRenderer.scala
ByteString.size is implemented by SeqOps which introduces a few more intermediate frames and indirection.
Turned up with ~ 1% in profiles.
(A better generic solution would be to be able to provide a concrete implementation in `ByteString` which isn't possible because `SeqOps.size` is marked final.)
=> http2: use ByteString.length instead of ByteString.size

akka-http-core/src/main/resources/reference.conf, docs/src/main/paradox/common/timeouts.md
To help users searching for a solution when they occur a certain error message.
=> docs: small wording updates for `keep-alive-timeout` feature

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ServerSettingsImpl.scala
This is a small optimization for HTTP/1.1.
The documentation of `request-timeout` already hints that you will get
no dynamic request-timeout support if you turn off the feature by setting
it to `infinite`. For some reason never made use of that flexibility.
It turns out that request timeout support is expensive even if it is enabled,
so this will help HTTP/1.1 performance a bit.
=> core: don't include RequestTimeoutSupport if disabled

akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/Decoder.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/DynamicTable.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/Encoder.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/HeaderField.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/HeaderListener.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/HpackUtil.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/Huffman.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/HuffmanDecoder.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/HuffmanEncoder.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/StaticTable.java, akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/package-info.java, akka-http-core/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Demux.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/ResponseParsing.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderDecompression.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/hpack/Http2HeaderParsing.scala, akka-http-core/src/main/scala/akka/http/impl/util/EnhancedByteArray.scala, akka-http-core/src/main/scala/akka/http/impl/util/StringTools.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2FrameHpackSupport.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala
Aside from the write coalescing work (which is now continued in https://github.com/akka/akka/pull/30334) this is the biggest chunk of performance improvements that I have queued.
Tests should be fine but some cleanups are still pending.
=> Optimize HTTP/2 header parsing by caching some header models directly in HPACK tables

akka-http-core/src/main/mima-filters/10.2.4.backwards.excludes/cache-content-type-rendering.excludes, akka-http-core/src/main/scala/akka/http/scaladsl/model/ContentType.scala
Because that's the underlying value and what's used in HTTP/2.
Follow up to #3830.
=> http2: use cached ContentType.value instead of toString

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala
This was previously optimized in Http2Demux but missed here as well.
=> http2: avoid calling LoggingAdapter.isDebugEnabled in multiplexer

akka-http-core/src/main/mima-filters/10.2.4.backwards.excludes/2877-better-LogByteStringTools-printByteString.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpMessageParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpResponseParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/package.scala, akka-http-core/src/main/scala/akka/http/impl/util/LogByteStringTools.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/LowLevelOutgoingConnectionSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
This PR adds detail to `onBadProtocol` error messages to better help diagnose when this error is thrown
- This PR simply allows the `detail: String` as well as the original `summary: String` to be passed into the `ErrorInfo` class.
- Note that one side effect of this change is I had to remove default parameters from `ParsingException` due to conflicts with overloaded definitions (you cannot have default parameters with overloaded functions)
`ErrorInfo` already contains a `detail: String` field designed to provide extra information about the issue, this PR simply uses that field to provide more details about the error when `onBadProtocol` is called.
=> Add detail to onBadProtocol

.github/workflows/validate-and-test.yml
To avoid that a bunch of workflows is run when you push to a PR in quick
succession.
=> build: cancel outdated builds

akka-http-core/src/test/scala/akka/http/impl/engine/ws/MessageSpec.scala
pushInput uses Probe.expectNext which uses the default remaining
timeout which is diluted as well. However, the eventually loop is
suppossed to fill up buffers but under dilation it is not guaranteed to
actual make enough process to fail within the time limit.
This failed the GH actions master job consistently since dilation was added in #3878.
=> tests: fix MessageSpec with higher test.timefactor values

project/ValidatePullRequest.scala
Avoid to slip in untested code, if breakage is caused by workflow changes like in #3878.
=> build: run full validation when workflow definition has changed

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Demux.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Multiplexer.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/StreamPrioritizer.scala
To avoid expensive frequent updates to persistent collections like Set or Vector. Beneficial side-effect: states can all be constant values.
=> http2: use mutable.Queue for state in multiplexer

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> http2: don't crash if stream is enqueued at multiplexer multiple times

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala
Computing the number of connected slots is linear over the
max number of connections for a host. This change avoids
computing the number of connected slots for the preconnect
step when the minimum number of connections is zero.
=> core: avoid calling numConnectedSlots when possible #3904

akka-http-core/src/main/mima-filters/10.2.6.backwards.excludes/3918-add-new-parsing-setting.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/model/parser/CommonRules.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/HeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ParserSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ParserSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ParserSettings.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala, docs/src/main/paradox/security.md, docs/src/main/paradox/security/2021-CVE-2021-42697-stack-overflow-parsing-user-agent.md, docs/src/main/paradox/security/2021.md
To avoid StackOverflowErrors while parsing headers based on user input.
Fixes #3918 / CVE-2021-42697
=> core: limit comment nesting in header parser

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ServerProcessingBenchmark.scala, akka-http-core/src/main/mima-filters/10.2.6.backwards.excludes/3922-safe-header-rendering.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/client/HttpsProxyGraphStage.scala, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/BodyPartRenderer.scala, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpRequestRendererFactory.scala, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala, akka-http-core/src/main/scala/akka/http/impl/util/Rendering.scala, akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala, akka-http-core/src/test/scala/akka/http/impl/util/RenderingSpec.scala
Refs #3717
To avoid accidental response splitting when applications put unsanitized request
data into outgoing responses.
We previously discussed introducing a check in the header models which could avoid
overhead during rendering. There are a lot of header models, however, which
all had to be checked one by one for potential issues. This would require a significant
effort now to check all the existing headers and would also make it easy to
reintroduce problems later on when headers are added or changed.
The approach here requires that all headers are rendered using the new overload of
`Rendering.~~`. When that method is used, we render the header and check afterwards
that the rendered data does not contain any CR or LF characters.
The performance overhead seems negligible, the new method …
=> core: discard outgoing headers containing line breaks

build.sbt
Especially when we want to update a Scala version before Scalafix has released
the latest version.
Currently, this breaks publishing snapshot documentation.
=> build: don't aggregate scalafix tests which breaks paradox too easily

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ServerProcessingBenchmark.scala, akka-http-core/src/main/mima-filters/10.1.14.backwards.excludes/safe-header-rendering.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/client/HttpsProxyGraphStage.scala, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/BodyPartRenderer.scala, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpRequestRendererFactory.scala, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala, akka-http-core/src/main/scala/akka/http/impl/util/Rendering.scala, akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala, akka-http-core/src/test/scala/akka/http/impl/util/RenderingSpec.scala
Refs akka#3717
To avoid accidental response splitting when applications put unsanitized request
data into outgoing responses.
We previously discussed introducing a check in the header models which could avoid
overhead during rendering. There are a lot of header models, however, which
all had to be checked one by one for potential issues. This would require a significant
effort now to check all the existing headers and would also make it easy to
reintroduce problems later on when headers are added or changed.
The approach here requires that all headers are rendered using the new overload of
`Rendering.~~`. When that method is used, we render the header and check afterwards
that the rendered data does not contain any CR or LF characters.
The performance overhead seems negligible, the new …
=> [10.1 backport] core: discard outgoing headers containing line breaks (#3922)

akka-http-core/src/main/mima-filters/10.1.14.backwards.excludes/add-new-parsing-setting.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/model/parser/CommonRules.scala, akka-http-core/src/main/scala/akka/http/impl/model/parser/HeaderParser.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ParserSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ParserSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ParserSettings.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
Fixes #3918
To avoid StackOverflowErrors while parsing headers based on user input.
(cherry picked from commit 6fd3c0dc2d9dc979bdc99395f39ec42e733011e4)
=> [10.1 backport] core: limit comment nesting in header parser

akka-http-core/src/main/mima-filters/10.1.14.backwards.excludes/keep-alive-timeout.excludes, akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/SlotState.scala, akka-http-core/src/main/scala/akka/http/impl/settings/ConnectionPoolSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/ConnectionPoolSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ConnectionPoolSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/pool/SlotStateSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/settings/PreviewServerSettingsSpec.scala, docs/src/main/paradox/common/timeouts.md
Co-authored-by: Arnout Engelen <arnout@bzzt.net>
Co-authored-by: Johannes Rudolph <johannes.rudolph@gmail.com>
(cherry picked from commit 814ad18fd5aad671de790995e10bb0c799ddb375)
(cherry picked from commit eb5557fa4cd2f43b453f280fbab231c115120d6e)
=> [10.1 backport] core: add pool keep-alive-timeout (#3816)

.github/workflows/publish.yml
To avoid overwriting main snapshot docs...
=> build: don't publish snapshot docs from release-10.1 branch

docs/src/main/paradox/release-notes/10.1.x.md, docs/src/main/paradox/security/2021-CVE-2021-42697-stack-overflow-parsing-user-agent.md
So, they will eventually part of the `current` docs as well.
=> docs: backport release notes from 10.1

.github/workflows/validate-and-test.yml, akka-http-core/src/main/mima-filters/10.1.14.backwards.excludes/FastFuture-generic-signature.excludes, akka-http-core/src/main/mima-filters/10.2.7.backwards.excludes/scala-2.13.7-signatures.excludes, project/Dependencies.scala
rather than both in GHA config and project/Dependencies.scala
=> build: keep Scala version in one place

akka-http-core/src/main/scala/akka/http/impl/engine/HttpConnectionIdleTimeoutBidi.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
And run ClientServerSpec also with http2 enabled.
Fixes #3959
=> core: enable idle-timeout when http2 is enabled

docs/src/main/paradox/routing-dsl/overview.md, docs/src/main/paradox/routing-dsl/rejections.md, docs/src/main/paradox/routing-dsl/routes.md
Replace deprecated functions in Routing DSL docs page:
Route.handlerFlow -> Route.toFlow
Route.asyncHandler -> Route.toFunction
RouteResult.route2HandlerFlow -> RouteResult.routeToFlow
=> docs: replace deprecated functions in Routing DSL docs

.github/workflows/validate-and-test.yml, project/Dependencies.scala, project/FuzzySwitch.scala
Keeping consistent with Akka (https://github.com/akka/akka/pull/30981)
=> build: use fuzzy `+~` to switch Scala versions

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Demux.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/H2cUpgradeSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerDemuxSpec.scala
When `SETTINGS_MAX_CONCURRENT_STREAMS` was set in the initial settings from
the `Upgrade` request, the input would be pulled twice, which is an error.
Fixes #3998
=> fix(http2): h2c via Upgrade

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/test/scala/akka/http/scaladsl/GracefulTerminationSpec.scala
Refs #3662
In the issue, it was observed that a connection might only cancel a pool
connection but would not fail it (which was the implicit assumption of the
existing code). In this case a pool might get more and more unresponsive
with slots hanging after connections being canceled but not failed.
The exact condition could not be reproduced but let's be proactive here
and fail the slot if we see unexpected cancellation.
=> core: fail pool slot if connection is canceled before it is failed

akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala
ensure PoolMaster.shutdown(…) does not hang
References #4003
=> fixes #4003 ensure PoolMaster.shutdown(…) does not hang

akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ServerProcessingBenchmark.scala, akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ClientServerBenchmark.scala, akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/http2/H2ServerProcessingBenchmark.scala, akka-http-core/src/main/mima-filters/10.2.7.backwards.excludes/4018-servertermination-http2-updates.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Demux.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/ProtocolSwitch.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/ServerTerminator.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerDemuxSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/ProtocolSwitchSpec.scala
The functionality is built directly into the Http2Demux which
has the state of all streams readily available. It supports the
same interface as the HTTP/1 version, though.
Fixes #3580
=> http2: implement graceful termination for HTTP/2 servers

akka-http-core/src/main/scala/akka/http/impl/engine/server/ServerTerminator.scala
Seems to have been in there since the beginning, it's always `false` so the branch is never taken and `false` never overwritten to `false`.
=> core: remove unused var from ServerTerminator

akka-http-core/src/main/mima-filters/10.2.8.backwards.excludes/Http-constructor-revert.excludes, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala
Refs #4045
Because it broke Telemetry support.
This partly reverts commit 7476d36aa7985d37469551b54066074370ce5d61.
=> core: revert part of "core: cleanup some unused vals (#4033)"

.github/workflows/nightly.yml
Akka 2.5 is not compatible with JDK 17
=> build: disable JDK 17 nightly tests against Akka 2.5

.github/workflows/nightly.yml, .github/workflows/validate-and-test.yml, project/Common.scala
By reducing concurrency in sbt. Previous runs have shown that compilation and tests could still run in parallel otherwise.
(Not completely sure to me how that can happen, it seems that fine-grained `concurrentRestrictions` are broken under aggregation. Also `Test/compile test` doesn't seem to guarantee sequential execution. We could use `;Test/compile;test` instead but that still seems to show the problem with aggregation, i.e. even if the project is fully compiled, just running `test` in the root project still executes test suites from multiple submodules concurrently even with `Test / parallelExecution := false`.)
=> Try to make GHA testing more reliable

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Demux.scala
Fixes #4059
With Akka 2.5, calling `shutdownStreamHandling()` in postStop was enough to abort
the substreams with an error.
Akka 2.6 has automatic substream cleanup which runs before `postStop` which would complete
substreams instead of aborting them with an error. Calling `shutdownStreamHandling` earlier
solved the problem in this case.
=> http2: when connection is aborted due to completion timeout, abort ongoing substreams (on Akka 2.6)

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/PersistentConnection.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala
To avoid race conditions.
We might want to look into whether there's a better way to report errors like that.
=> http2: add client-side cancellation propagation delay

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala
Hoppefully, these spurious messages will further be reduced by
https://github.com/akka/akka/pull/31231.
=> http2: reduce severity for more Akka IO unhandled message events in tests

akka-http/src/main/scala/akka/http/javadsl/marshalling/Marshaller.scala, akka-http/src/main/scala/akka/http/javadsl/server/RejectionHandler.scala, akka-http/src/main/scala/akka/http/javadsl/server/Rejections.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/AttributeDirectives.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/CacheConditionDirectives.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/FramedEntityStreamingDirectives.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/PathDirectives.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteDirectives.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/SecurityDirectives.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/WebSocketDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/PathDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/settings/RoutingSettings.scala, build.sbt
This mostly involves specifying types for implicit vals and adding correct parentheses in lambda types. Compilation with `-source:3.0-migration` was simple, requiring only passing some implicits explicitly in `PathDirectives`. When I removed the option, another slightly more severe issue popped up, with the compiler seemingly incorrectly inferring types used in javadsl/scaladsl mappings - because of that, the compiler was unable to find the correct implicit. This was fixed by manually specifying types in places like this. What's interesting, this only happened when going through a collection previously converted from java collection (via `scala.collections.JavaConverters`). This can be for example observed in `Rejections.scala`.
Nevertheless, now the 'akka-http' module compiles with both …
=> Allow to compile `akka-http` module with Scala 3

akka-http-caching/src/main/scala/akka/http/scaladsl/server/directives/CachingDirectives.scala, akka-http-caching/src/test/scala/akka/http/scaladsl/server/directives/CachingDirectivesSpec.scala
Threads competing to access the cache may block like this:
```
java.lang.Thread.State: BLOCKED (on object monitor)
at java.util.concurrent.ConcurrentHashMap.computeIfPresent(ConcurrentHashMap.java:1760)
- waiting to lock <0x000000073cb6b320> (a java.util.concurrent.ConcurrentHashMap$Node)
at com.github.benmanes.caffeine.cache.BoundedLocalCache.replace(BoundedLocalCache.java:2302)
at com.github.benmanes.caffeine.cache.LocalAsyncCache.lambda$handleCompletion$7(LocalAsyncCache.java:210)
at com.github.benmanes.caffeine.cache.LocalAsyncCache$$Lambda$105857/1233505965.accept(Unknown Source)
at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
at …
```
=> cache: avoid locking cache during directive processing

akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpEntity.scala
When creating an `HttpEntity` from a `String`, use
`ByteString.fromArrayUnsafe` to avoid creating an
unnecessary copy of the byte array.
=> core: avoid array copy for string entities

akka-http-caching/src/main/scala/akka/http/scaladsl/server/directives/CachingDirectives.scala, akka-http-caching/src/test/scala/akka/http/scaladsl/server/directives/CachingDirectivesSpec.scala
The `asyncRoute & ...` construction did not work as expected and also using
`check` in tests starved threads themselves.
Refs #4092, update to #4093
=> caching: fix cached execution and test

.github/workflows/validate-and-test.yml, akka-http-caching/src/main/scala/akka/http/scaladsl/server/directives/CachingDirectives.scala, akka-http-caching/src/test/scala/akka/http/scaladsl/server/directives/CachingDirectivesSpec.scala, akka-parsing/src/main/scala-2/akka/macros/LogHelperMacro.scala, akka-parsing/src/main/scala-3/akka/http/ccompat/pre213macro.scala, akka-parsing/src/main/scala-3/akka/http/ccompat/since213macro.scala, akka-parsing/src/main/scala-3/akka/macros/LogHelperMacro.scala, build.sbt, project/AkkaDependency.scala
* 2.12: does not work as long as we have no solution for the `@pre213` annotation
* 2.13: had a problem with Akka version in docs submodule
* 3: had a problem with aggregating only the current subset of supported modules
=> Scala 3: try to make PR validation work (as well as possible right now)

akka-http-marshallers-scala/akka-http-spray-json/src/test/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupportSpec.scala, akka-http-tests/src/multi-jvm/scala/akka/http/AkkaHttpServerLatencyMultiNodeSpec.scala, akka-http-tests/src/multi-jvm/scala/akka/remote/testkit/MultiNodeConfig.scala, akka-http-tests/src/multi-jvm/scala/akka/remote/testkit/PerfFlamesSupport.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/CustomMediaTypesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/FormDataSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/TestSingleRequest.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/coding/CodecSpecSupport.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/marshallers/sprayjson/SprayJsonSupportSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/FromStatusCodeAndXYZMarshallerSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/MarshallingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/BasicRouteSpecs.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/ConnectionTestApp.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/DontLeakActorsOnFailingConnectionSpecs.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/EntityStreamingSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/SizeLimitSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/TcpLeakApp.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/TestServer.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/CodingDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileAndResourceDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FormFieldDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MarshallingDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/ParameterDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/RouteDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/TimeoutDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/util/TupleOpsSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/unmarshalling/UnmarshallingSpec.scala, build.sbt
This also includes `akka-http-spray-json` and `akka-http-scala-xml `, on which the tests depend.
Because of changes to type inference, some tests had to be slightly adjusted (beyond defining types explicitly). They all compile, though running tests locally concludes with a somewhat confusing message:
```
[info] ScalaTest
[info] Run completed in 40 seconds, 36 milliseconds.
[info] Total number of tests run: 1273
[info] Suites: completed 65, aborted 0
[info] Tests: succeeded 1273, failed 0, canceled 0, ignored 0, pending 40
[info] All tests passed.
[info] multi-jvm
[info] akka.http.AkkaHttpServerLatencyMultiNodeSpec
[error] Failed: Total 1432, Failed 0, Errors 0, Passed 1432, Pending 40
[error] (akka-http-tests / Test / test) sbt.TestsFailedException: Tests unsuccessful
```
`3.0-migration` …
=> http-tests: allow to compile with Scala 3 with 3.0-migration option

akka-http-core/src/main/java/akka/http/javadsl/model/Query.java, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala, akka-http-core/src/main/scala/akka/http/javadsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ParserSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/WebSocketSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/ResponseParserSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/DateTimeSpec.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpEntitySpec.scala, akka-http-tests/src/test/scala-2.13-/src/main/akka/http/ccompat/ImplicitUtils.scala, akka-http-tests/src/test/scala-2.13/src/main/akka/http/ccompat/ImplicitUtils.scala, akka-http-tests/src/test/scala-3/src/main/akka/http/ccompat/ImplicitUtils.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/DontLeakActorsOnFailingConnectionSpecs.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/SizeLimitSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FileUploadDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/FutureDirectivesSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MiscDirectivesSpec.scala, build.sbt
References #4079, task `Make compilation work without 3.0-migration compiler option`
=> Scala 3: Remove 3.0-migration compiler option from all modules

.github/workflows/validate-and-test.yml, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/CacheDirective.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/LanguageRange.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/LinkValue.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/headers.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FormFieldDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/RespondWithDirectives.scala, build.sbt, project/Pre213Preprocessor.scala
(But hopefully get soon rid of it when we drop Scala 2.12 support)
~Only applied to akka-http-core so far.~
=> Scala 3: edit sources on-the-fly in sbt to support `@pre213` methods in shared source code

.gitignore, docs/src/main/paradox/extensions.md
Swakka appears to be abandoned (no maintainer activity in 3 years) and there's an [outstanding issue around 10.2.x support](https://github.com/jtownson/swakka/issues/9).  Additionally, it's not built for Scala 2.13.
This PR proposes to recommend `swagger-akka-http` in its place, which is more actively maintained.  Alternatively, we can decide to not endorse that extension, in which case I think there's an even weaker case for endorsing swakka.
=> docs: replace abandoned swakka with actively maintained swagger-akka-http

project/Dependencies.scala
https://github.com/lampepfl/dotty/releases/tag/3.1.3-RC3
More aggressive reduction of type selection (fixes parboiled2) https://github.com/lampepfl/dotty/pull/14987
Relax avoidance checks more for match type reduction https://github.com/lampepfl/dotty/pull/15036
=> =sbt Update Scala 3 version to 3.1.3

akka-http-core/src/main/scala/akka/http/impl/settings/ParserSettingsImpl.scala, akka-http-core/src/test/scala/akka/http/scaladsl/ClientServerSpec.scala
References https://github.com/akka/akka-http/issues/3903
- modified `maxContentLengthSetting` to allow empty bodies in requests
- added test for that in `ClientServerSpec`
=> Allow parsing.max-content-length = 0

akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/ByteRange.scala
I wasn't sure what the behavior of Suffix was. I had to dig into the source to see if it was applicable for my request (like `bytes=-100`). This should make it more clear.
=> document ByteRange suffix

akka-http-bench-jmh/src/main/scala/akka/BenchRunner.scala, akka-http/src/main/scala/akka/http/scaladsl/server/util/ConstructFromTuple.scala, build.sbt, docs/src/test/scala/docs/http/scaladsl/Http2ClientApp.scala, docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/HttpServerExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/HttpServerWithActorInteraction.scala, docs/src/test/scala/docs/http/scaladsl/HttpServerWithActorsSample.scala, docs/src/test/scala/docs/http/scaladsl/SprayJsonExample.scala, docs/src/test/scala/docs/http/scaladsl/SprayJsonExampleSpec.scala, docs/src/test/scala/docs/http/scaladsl/SprayJsonPrettyMarshalSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/CaseClassExtractionExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/ExceptionHandlerExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/RejectionHandlerExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/TestKitFragmentSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/TestKitWithActorSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/BasicDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/CodingDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/FileUploadDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/FutureDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/JsonStreamingExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/JsonStreamingFullExamples.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/MarshallingDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/MiscDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/PathDirectivesExamplesSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/RouteDirectivesExamplesSpec.scala, project/Common.scala
On top of #4079
Three errors remaining around creating case classes from parameters
=> scala 3: compile and test marshalling, JMH and docs subprojects

akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala
During connection problems, all slots will back off connection attempts,
so that effectively only a single request can make a new attempt (out of
potentially `max-connections` ones already pulled into the pool). However,
the previous order of putting requests back into the retry buffer means that
all requests in the pool get equal chances to run again. This way all requests
will fail approximately at the same time only after all requests have almost
timed out.
Using a LIFO buffer instead, makes it more likely that only a single request
at a time will get the chance to make another try, so it can be failed earlier,
then the next, etc. It does not change the overall throughput of failing requests
but decreases the average latency.
Refs #4128
=> core: use LIFO ordering in retry buffer of connection pool

akka-http-core/src/main/scala/akka/http/scaladsl/model/Uri.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/UriSpec.scala
Uri.collapseDotSegments fails on some relative paths #2507
Description:
the conclusion is that the 'collapseDotSegments' doesnt work as described in 'http://tools.ietf.org/html/rfc3986#section-5.2.4' when relative path doent start with a '/'. the easy solution is to check whether the given Uri starts with a '/' or not. and call 'process' accordingly.
=> core: Uri.collapseDotSegments fails on some relative paths #2507

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
To avoid reentering the state machine which will break setting intermediate states.
Refs #4087
=> http2: defer enqueing out streams when state machine is already running

akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/BasicDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/BasicDirectives.scala
Fixes https://github.com/akka/akka-http/issues/4134
Unsure what exactly to add to the docstring, if anything. Could be something like `Fails the route with an [IllegalRequestException] if the request framing is invalid` - thoughts?
This rethrows `EntityStreamException` as `IllegalRequestException`. This matches more things than the above issue - eg. situations such as exceeding the max entity size. Turns out, exceeding the max entity size also resulted in an internal server error previously and due to this change now results in a bad request - it really ought to be a 413 entity too large, but I can't really distinguish these errors as they currently use the same underlying exception types. But at least 400 Bad Request is better than 500 internal error.
=> Make `toStrictEntity` fail with bad request in case of entity errors

akka-http-core/src/main/java/akka/http/javadsl/model/StatusCodes.java, akka-http-core/src/main/scala/akka/http/impl/engine/parsing/HttpRequestParser.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/StatusCode.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, akka-http-tests/src/test/java/akka/http/javadsl/server/directives/MiscDirectivesTest.java, akka-http-tests/src/test/java/akka/http/javadsl/server/directives/RouteDirectivesTest.java, akka-http-tests/src/test/scala/akka/http/scaladsl/server/SizeLimitSpec.scala, akka-http-tests/src/test/scala/akka/http/scaladsl/server/directives/MiscDirectivesSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/ExceptionHandler.scala, akka-http/src/main/scala/akka/http/scaladsl/server/RejectionHandler.scala, docs/src/test/java/docs/http/javadsl/server/directives/MiscDirectivesExamplesTest.java, docs/src/test/scala/docs/http/scaladsl/server/directives/MiscDirectivesExamplesSpec.scala
I think the naming changed in RFC 9110, see https://www.rfc-editor.org/rfc/rfc9110.html#name-413-content-too-large and https://www.rfc-editor.org/rfc/rfc9110.html#name-422-unprocessable-content.
=> Update naming for status codes 413 and 422

project/Dependencies.scala
* Fixes https://nvd.nist.gov/vuln/detail/CVE-2022-42003 (even if we were not really affected out of the box).
=> Update to Jackson databind 2.13.4.1

.github/workflows/fossa.yml, .github/workflows/nightly.yml, .github/workflows/publish-test-reports.yml, .github/workflows/publish.yml, .github/workflows/validate-and-test.yml
`nightly` used Temurin JDK builds via Jabba. This switches to Temurin everywhere.
References https://github.com/akka/akka/pull/31730
=> chore: renovate GH workflows

.github/workflows/nightly.yml, .github/workflows/publish-test-reports.yml, .github/workflows/publish.yml, .github/workflows/validate-and-test.yml
The filenames for uploads may not contain `:`, splitting out the JVM name.
References #4191
=> ci: remove name from JVM selection again

.github/workflows/nightly.yml
Nightlies started failing with out of heap errors on JDK8 last week. Not obvious why it shows now on the renovated workflows. The JDK version was Temurin 8u352b08 even before switching to coursier/setup-action.
=> ci: More memory for JDK8 nightlies

.github/workflows/nightly.yml
Same setup as in akka/akka.
Applicable secrets are available.
=> ci: send email for failing nightlies

akka-parsing/src/main/scala/akka/parboiled2/CharUtils.scala
We already had this optimization but it got lost in the Scala 3 support work. Fixes a 10% throughput regression for Scala 2.13 after the Scala 3 support was added.
=> Revert parboiled upper/lowercase changes for performance

project/Common.scala
JavaDoc started failing in CI when updating to later JDKs for the `-Xlint:deprecation` flag.
https://github.com/akka/akka-http/actions/runs/3513685314/jobs/5886797573#step:5:362
=> ci: Remove linting flag from JavaDoc runs

.github/workflows/publish-test-reports.yml
See the error in https://github.com/akka/akka-http/actions/runs/3530396634/jobs/5922344320#step:2:749
References #4189
=> ci: permit checks write for test reporting

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala
=> fix: Too tight timeout in Http2PersistentClientSpec for failing with backoff

.gitignore, akka-http-core/src/main/java/akka/http/javadsl/model/HttpMethods.java, akka-http-core/src/main/mima-filters/10.4.0.backwards.excludes/4213-content-length.backwards.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/rendering/HttpResponseRendererFactory.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMethod.scala, akka-http-core/src/test/scala/akka/http/impl/engine/client/HostConnectionPoolSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/parsing/RequestParserSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/rendering/ResponseRendererSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/server/HttpServerSpec.scala, docs/src/test/scala/docs/http/scaladsl/server/directives/CustomHttpMethodSpec.scala
Adds `Content-Length: 0` header on responses that do not allow a response body (204, 205 and 304).
I did not add a specific test, as there was already a test for rendering a 304 response - I simply made that test more correct :slightly_smiling_face:
Fixes #4213
=> fix #4213: Content-Length when entity is unallowed

.fossa.yml
Exclude non-distributed modules from scanning by Fossa.
=> chore: configure Fossa scanning

akka-http-core/src/main/mima-filters/10.4.0.backwards.excludes/4226-bad-header-http2-response.excludes, akka-http-core/src/main/scala/akka/http/impl/engine/http2/FrameEvent.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/FrameLogger.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2StreamHandling.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/HttpMessageRendering.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/RequestErrorFlow.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/RequestParsing.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/ResponseParsing.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderCompression.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/hpack/HeaderDecompression.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/hpack/Http2HeaderParsing.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ClientServerSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2ServerDemuxSpec.scala, akka-http2-support/src/test/scala/akka/http/impl/engine/http2/RequestParsingSpec.scala
References #4226
Also fixes https://github.com/akka/akka-http/issues/2394
=> fix: Invalid HTTP2 request headers should lead to bad request responses

akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTest.scala, akka-http-testkit/src/test/scala/akka/http/scaladsl/testkit/RouteTestSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/server/Route.scala
=> chore: Reintroduce a way for tests to invoke a route without error handler 

akka-http-testkit/src/main/resources/reference.conf, akka-http-testkit/src/main/scala/akka/http/scaladsl/testkit/RouteTestTimeout.scala
This PR add support to changing the `RouteTestTimeout` with providing the override of the `akka.http.testkit.routes.timeout` from the typesafe config, in this way we can change the default timeout directly from the configuration instead of overriding the timeout directly from the code.
References #4238
=> add config support for RouteTestTimeout via application.conf

docs/src/main/paradox/security.md
Leaving existing announcement pages for now (but they have been duplicated to akka.io).
=> docs: New centralized security page

akka-http-core/src/test/java/akka/http/javadsl/WSEchoTestClientApp.java, akka-http-core/src/test/scala/akka/http/impl/engine/ws/EchoTestClientApp.scala, docs/src/test/java/docs/http/javadsl/WebSocketClientExampleTest.java, docs/src/test/scala/docs/http/scaladsl/SingleWebSocketRequest.scala, docs/src/test/scala/docs/http/scaladsl/WebSocketClientFlow.scala
- Replaced usages of `ws://echo.websocket.org` echo websocket that is no longer available, with `ws://ws.ifelse.io` that is currently available.
References #4265
=> #4265  Replace echo.websocket.org -> ws.ifelse.io

akka-http-core/src/main/scala/akka/http/scaladsl/model/headers/LinkValue.scala, akka-http-core/src/test/scala/akka/http/impl/model/parser/HttpHeaderSpec.scala
Refs #4264
Instead of the suggested always quoting I went for additional quoting when colon in string, keeping it closer to original behavior and also trading one more char check for two additional bytes in each Link/rel entry.
=> fix: Align better with RFC 8288 by quoting strings with colon 

akka-http2-support/src/test/scala/akka/http/impl/engine/http2/Http2PersistentClientSpec.scala
Max retry timespan was underestimated
References #4205
=> chore: Fix failing HTTP/2 retry test

.fossa.yml
Fossa was not skipping the excluded targets. Couldn't figure out why or how to make target excludes work here. Switch to path excludes (as we're using for akka).
`fossa analyze --output` before:
```
18 projects scanned;  1 skipped,  17 succeeded,  0 failed,  17 analysis warnings
* scala project in "/Users/peter/dev/akka/akka-http/akka-http-bench-jmh/target/scala-2.13/": succeeded with 1 warning
* scala project in "/Users/peter/dev/akka/akka-http/akka-http-bill-of-materials/target/scala-2.13/": succeeded with 1 warning
* scala project in "/Users/peter/dev/akka/akka-http/akka-http-caching/target/scala-2.13/": succeeded with 1 warning
* scala project in "/Users/peter/dev/akka/akka-http/akka-http-compatibility-tests/target/scala-2.13/": succeeded with 1 warning
* scala project in …
```
=> chore: fix fossa excludes using paths

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocket.scala, akka-http-core/src/main/scala/akka/http/impl/settings/WebSocketSettingsImpl.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/WebSocketSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/WebSocketSettings.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketIntegrationSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketServerReceiveIdleTimeoutSpec.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketServerSendIdleTimeoutSpec.scala
Hello all,
I would like to contribute to Akka project by providing a feature that allows to catch websocket disconnections due to network unavailability.
I have introduced two configuration parameters for websocket client:
```
akka.http.client.websocket.receive-idle-timeout
akka.http.client.websocket.send-idle-timeout
```
and server:
```
akka.http.server.websocket.receive-idle-timeout
akka.http.server.websocket.send-idle-timeout
```
that can be configured together with `akka.http.{client, server}.periodic-keep-alive-max-idle` to detect lost network connection.
The working principle is simple: if elements are not send or received (including ping/pong frames), the streams are failed with
`akka.stream.StreamIdleTimeoutException`
The default config values are `infinite` which means that this …
=> Websocket stream failure on receive/send timeout (network lost detection)

akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/ws/MessageToFrameRenderer.scala, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala
Motivation:
Change to use `statefulMap` instead when not concating.
=> =core Make use of `statefulMap` instead of `statefulMapConcat`.

project/Dependencies.scala
Use same Jackson version as in upcoming Akka 2.9. Targeting next minor release.
=> bump: Jackson 2.15.2

akka-http-tests/src/test/scala/akka/http/scaladsl/marshalling/MarshallingSpec.scala, akka-http/src/main/scala/akka/http/scaladsl/marshalling/PredefinedToEntityMarshallers.scala
References #4295
Follows the suggestion in https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset and falls back to UTF-8 when the requested Accept-Charset is not a valid charset (instead of failing with a NIO exception and logging noise)
=> fix: Fail-over to UTF-8 if Accept-Charset is invalid

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2Blueprint.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/framing/RSTFrameLimit.scala, akka-http-core/src/main/scala/akka/http/javadsl/settings/Http2ServerSettings.scala, akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala, akka-http2-tests/src/test/scala/akka/http/impl/engine/http2/Http2ServerSpec.scala
=> fix: Rate limit protection against rapid resets

.github/ISSUE_TEMPLATE/---question.md, CONTRIBUTING.md, README.md, docs/release-train-issue-template.md, docs/src/main/paradox/migration-guide/migration-from-old-http-javadsl.md, project/project-info.conf
Just happened to notice we still offer Gitter as a channel in some places.
=> chore: remove references to Gitter and other outdated things

docs/src/main/paradox/handling-blocking-operations-in-akka-http-routes.md, project/plugins.sbt
@johanandren should be ok to merge I guess.
- #4346 still is open however.
=> Upgrade dependencies to avoid repo.scala-sbt.org

akka-http-core/src/main/java/akka/http/javadsl/model/HttpMessage.java, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpHeader.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMessage.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpMessageSpec.scala, docs/src/main/paradox/common/http-model.md
See #1102.
Throws an `IllegalArgumentException` if an attempt is used to lookup a modelled custom header by class from an `HttpRequest`.
While ideally, the best thing would be to support registering modelled headers, until that gets implemented, I think it's important to make sure users know when they try to lookup a custom header using an unsupported method that it's not supported. This will save a lot of heartache.
Things I'm not sure about this change:
* Performance - it adds an `isAssignableFrom` to every `HttpRequest.header[T]` call when the header is not present.
* Whether there are any places where we depend on the request returning `None`, eg, if we have methods that try this first, and then fallback to using a method that is supported for custom headers. I couldn't find anything. …
=> Fail on attempt to look up custom modelled headers

.fossa.yml
The vulnerability scanning detects outdated libraries in the ScalaFix support.
As this is not used when running Akka HTTP-based systems, we can exclude it from scanning.
=> chore: exclude ScalaFix support from vulnerability scanning

docs/src/main/paradox/extensions.md
Add-on to https://github.com/akka/akka-http/pull/4343
=> docs: remove docs referencing external CORS lib

docs/src/main/paradox/routing-dsl/directives/tls-directives/extractClientCertificate.md
Had this small typo fix in the stash for some time.
=> docs: fix filename in example

build.sbt, project/CopyrightHeader.scala, project/Formatting.scala, project/Github.scala, project/MultiNode.scala, project/ValidatePullRequest.scala, project/plugins.sbt
=> build: Build gardening

.fossa.yml
We don't need FOSSA to scan the projects in the samples directory, so configure FOSSA to ignore that directory
References lightbend/akka-meta/issues/488
=> chore: Exclude samples from FOSSA scanning

docs/src/main/paradox/routing-dsl/directives/debugging-directives/logRequest.md, docs/src/main/paradox/routing-dsl/directives/debugging-directives/logRequestResult.md, docs/src/main/paradox/routing-dsl/directives/debugging-directives/logResult.md, docs/src/main/paradox/routing-dsl/directives/form-field-directives/formFields.md, docs/src/main/paradox/routing-dsl/directives/future-directives/onSuccess.md, docs/src/main/paradox/routing-dsl/directives/header-directives/headerValueByType.md, docs/src/main/paradox/routing-dsl/directives/header-directives/optionalHeaderValueByType.md, docs/src/main/paradox/routing-dsl/directives/parameter-directives/parameters.md, docs/src/main/paradox/routing-dsl/directives/range-directives/withRangeSupport.md, docs/src/main/paradox/routing-dsl/directives/route-directives/complete.md
This is a simple PR that replaces the links to the magnet pattern blog post with the correct one.
The previous link, `http://spray.io/blog/2012-12-13-the-magnet-pattern/`, is no longer valid - it seems that the `spray.io` domain was transferred to some other party (a Korean company from the looks of it).
I found the blog post via Google at https://spray.readthedocs.io/en/latest/blog/2012-12-13-the-magnet-pattern.html, so I thought I'd go ahead and submit a fix to the docs so other people don't get confused.
=> docs: replace magnet pattern URLs with correct one

akka-http-core/src/main/resources/reference.conf, akka-http-core/src/main/scala/akka/http/scaladsl/settings/Http2ServerSettings.scala
This fixes the documentation and error message to be correct for ping-timeout vs ping-interval configuration. It was back to front (ping-timeout must be a divisor of, not divisible by, ping-interval), and the wording was hard to grok.
=> Fixed docs for http2 ping-timeout

akka-http-bench-jmh/src/main/scala/akka/http/CorsBenchmark.scala, akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/ConnectionPoolBenchmark.scala, akka-http-bench-jmh/src/main/scala/akka/http/impl/engine/HttpEntityBenchmark.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolMasterActor.scala, akka-http-core/src/main/scala/akka/http/impl/engine/client/pool/NewHostConnectionPool.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/Http2.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/OutgoingConnectionBuilderImpl.scala, akka-http-core/src/main/scala/akka/http/impl/engine/http2/client/PersistentConnection.scala, akka-http-core/src/main/scala/akka/http/impl/engine/server/HttpServerBluePrint.scala, akka-http-core/src/main/scala/akka/http/impl/util/StreamUtils.scala, akka-http-core/src/main/scala/akka/http/javadsl/ServerBinding.scala, akka-http-core/src/main/scala/akka/http/javadsl/ServerBuilder.scala, akka-http-core/src/main/scala/akka/http/scaladsl/Http.scala, akka-http-core/src/test/scala/akka/http/impl/engine/ws/WebSocketIntegrationSpec.scala, akka-http/src/main/scala/akka/http/javadsl/server/RequestContext.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/BasicDirectives.scala, akka-http/src/main/scala/akka/http/javadsl/server/directives/RouteDirectives.scala, akka-http/src/main/scala/akka/http/scaladsl/server/directives/FileUploadDirectives.scala
Was dropped upstream here: https://github.com/akka/akka/pull/32515
=> chore: drop usage of akka.dispatch.ExecutionContexts

project/plugins.sbt
Superseds https://github.com/akka/akka-http/pull/4416.
This one is based on the latest `main` to have the latest certs.
=> bump: update sbt-ci-release from 1.6.0 to 1.6.1

project/Dependencies.scala
Superseds https://github.com/akka/akka-http/pull/4414, including the scalacheck bump.
=> bump: update scalatest to 3.2.19, scalacheck to 1.18.0

akka-http-core/src/main/java/akka/http/javadsl/model/headers/TlsSessionInfo.java, akka-http-core/src/main/mima-filters/10.6.3.backwards.excludes/tls-session-info.excludes
Fixes #4426.
When `TlsSessionInfo` was added, the only way to mark it as a header that should not be rendered was to implement `CustomHeader`, and then implement a method called `suppressRendering` to return `true`.
Obviously, this semantically didn't make sense since it's not a custom header, but not long after, a much better, more robust and semantically reasonable mechanism to ensure it didn't get rendered was provided in:
https://github.com/akka/akka/commit/a93a73ef5b0f8f56ffb99548b77a7f3fa297a594
This added `renderInRequests` and `renderInResponses` flags to headers, along with the traits `RequestHeader`, `ResponseHeader`, and `SyntheticHeader`. The Scala `Tls-Session-Info` class was modified to implement `SyntheticHeader` instead of the Scala `CustomHeader` trait, but the author …
=> Removed jm.CustomHeader from TlsSessionInfo heirarchy

.github/workflows/nightly.yml
Running the full matrix of builds every day seems to be a waste of energy as the JVM and Scala versions are very stable nowadays.
=> chore: reduce to weekly full matrix validation

akka-http-core/src/main/scala/akka/http/impl/model/parser/CommonRules.scala, akka-http-core/src/main/scala/akka/http/scaladsl/model/HttpMethod.scala, akka-http-core/src/test/scala/akka/http/scaladsl/model/HttpMethodSpec.scala
=> Validate custom HTTP method names

samples/akka-http-quickstart-java/pom.xml, samples/akka-http-quickstart-scala/build.sbt
Akka HTTP pulls in 2.10.5 but samples was on 2.10.0 so was failing in https://github.com/akka/akka-http/actions/workflows/check-samples.yml
=> docs: Fix sample Akka 2.10.5 versions
